<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>更改应用状态-运维</title>
<link media="screen" type="text/css" rel="stylesheet" href="{%$staticUrl%}/a/gb_app.css">
<style type="text/css">
<!--
html{overflow:scroll!important;}

body,td,th {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #333333;
}

a img,:link img,:visited img {
	border: 0 none;
}
div,form,dl,dt,dd,img,h1,h2,h3,h4,h5,h6,ul,ol,li,p,span,table,th,td,a{margin:0;padding:0;border:0}
img{border:none;vertical-align:middle}
body{font-family:"宋体",Verdana,Arial,Helvetica,sans-serif;font-size:12px}
button{border:none;cursor:pointer;background:none;font-size:12px;text-align:center}

#msgboxDiv {display:none;position:absolute;}

th{text-align:left}

-->
</style>
</head>
<body>
<div>
	<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
	<script src="{%$staticUrl%}/js/utils.js?v=1.0" type="text/javascript"></script>
	
	<div id="loading_area">加载正服应用状态数据<img src="{%$staticUrl%}/image/loading.gif" title="loading" /></div>
	<div id="info_area" style="display:none;">
	<table style="width:1000px;">
	<tr>
		<th>APP ID：</th>
		<td><input type="text" id="app_id" name="app_id" value="" size="30" ></input></td>
	</tr>
	<tr>
		<th>名称(英文)：</th>
		<td><input type="text" id="app_name" name="app_name" value="" size="30" ></input></td>
	</tr>
	<tr>
		<th>标题：</th>
		<td><input type="text" id="app_title" name="app_title" value="" size="30" ></input></td>
	</tr>
	<tr>
		<th>应用地址：</th>
			<td><input type="text" id="app_link" name="app_link" value="" size="80" ></input></td>
		</tr>
	<tr>
	<tr>
		<th>应用主机域名地址：</th>
			<td><input type="text" id="app_host" name="app_host" value="" size="80" ></input></td>
		</tr>
	<tr>
	<th>状态：</th>
	<td>
		<select id="slt_status" onchange="selectType(this.value)">
			<option value="0" style="color:red">停机维护</option>&nbsp;&nbsp;
			<option value="1">全体开放</option>&nbsp;&nbsp;
			<option value="2">测试人员开放</option>&nbsp;&nbsp;
			<option value="3">开发人员开放</option>&nbsp;&nbsp;
		</select>
	</td>
	</tr>
	<tr style="height:70px;">
	<th rowspan="2">停机维护公告：</th>
	<td><textarea id="notice" name="notice" style="width:540px;height:100px;"></textarea></td>
	</tr>
	<tr>
	<td>可使用HTML标签&nbsp;&nbsp;<input type="button" value="预览" onclick="preview();" id="button" /></td>
	</tr>
	<tr style="height:70px;">
		<th rowspan="2">IP白名单：</th>
		<td><textarea id="white_ip_list" name="white_ip_list" style="width:540px;height:60px;"></textarea></td>
	</tr>
	<tr>
		<td>多个之间用逗号( , )隔开</td>
	</tr>
	<tr style="height:70px;">
		<th rowspan="2">IP黑名单：</th>
		<td><textarea id="black_ip_list" name="black_ip_list" style="width:540px;height:60px;"></textarea></td>
	</tr>
	<tr>
		<td>多个之间用逗号( , )隔开</td>
	</tr>
	<tr style="height:70px;">
		<th rowspan="2">开发者ID名单：</th>
		<td><textarea id="dev_id_list" name="dev_id_list" style="width:540px;height:60px;"></textarea></td>
	</tr>
	<tr>
		<td>多个之间用逗号( , )隔开</td>
	</tr>
	<tr style="height:70px;">
		<th rowspan="2">测试者ID名单：</th>
		<td><textarea id="test_id_list" name="test_id_list" style="width:540px;height:60px;"></textarea></td>
	</tr>
	<tr>
		<td>多个之间用逗号( , )隔开</td>
	</tr>
	<tr>
		<th>内部开放API key：</th>
		<td><input type="text" id="external_api_key" name="external_api_key" value="" size="40" ></input></td>
	</tr>
	<tr>
		<th>内部开放API secret：</th>
		<td><input type="text" id="external_api_secret" name="external_api_secret" value="" size="40" ></input></td>
	</tr>
	<tr>
		<th>内部开放API开关：</th>
		<td>
		<select id="external_open" onchange="selectType(this.value)">
			<option value="0" style="color:red">关闭</option>&nbsp;&nbsp;
			<option value="1">开放</option>&nbsp;&nbsp;
		</select>
		</td>
	</tr>
	</table>
		<div style="margin:20px 300px;">
			<input type="button" value="更新" onclick="updateAppInfo();" id="button" />
		</div>
	</div>
	<div style="clear:both;"></div>
	<div style="width:417px;position:absolute;top:200px;left:100px;display:none;" class="layer_global" id="msgboxDiv">
		<div class="layer_global_main">
			<div class="layer_global_title"><h3 id="msgboxTitle"></h3><button title="关闭" id="closeQuery" onclick="closeQuery();"><span class="none">╳</span></button></div>
			<div class="layer_global_cont">
				<div style="margin: 20px;" class="wrap"><span id="msgboxContent"></span></div>
			</div>
		</div>
	</div>
	<div id="preview"></div>
</div>
<script type="text/javascript">

var APP_INFO = null;

function timeFormat(time)
{
	var timestamp = time*1000;
	return (new Date(timestamp)).format('Y-m-d H:i:s');
}

function msgbox(title, msg, x, y)
{
	if (!x) x = 50;
	if (!y) y = 100;
	$('#msgboxDiv').css({left: x, top: y});
	$('#msgboxTitle').html(title);
	$('#msgboxContent').html(msg);
	$('#msgboxDiv').show();
}

function closeQuery()
{
	$('#msgboxDiv').hide();
}

$.ajaxSetup({cache:false});

function getAppInfo()
{
	$('#loading_area').show();
	var dt = {type:2};
	$.get('/appadminapi/getappinfo?platform={%$platform%}', dt, function(data) {
		if (data.errno == 0) {
			APP_INFO = data;
			$("#app_id").val(data.app_id);
			$("#app_name").val(data.app_name);
			$("#app_title").val(data.app_title);
			$("#app_link").val(data.app_link);
			$("#app_host").val(data.app_host);
			$("#slt_status").val(data.app_status);
			$("#notice").val(data.maintance_notice);
			$("#white_ip_list").val(data.white_ip_list);
			$("#black_ip_list").val(data.black_ip_list);
			$("#dev_id_list").val(data.dev_id_list);
			$("#test_id_list").val(data.test_id_list);
			$("#external_api_key").val(data.external_api_key);
			$("#external_api_secret").val(data.external_api_secret);
			$("#external_open").val(data.external_open);
			
			$('#loading_area').hide();
			$('#info_area').show();
		} else {
			msgbox('警告', '获取数据失败', 250, 100);
		}
	}, "json");
}

function updateAppInfo()
{
	var app_id = $("#app_id").val();
	var app_name = $("#app_name").val();
	var app_title = $("#app_title").val();
	var app_link = $("#app_link").val();
	var app_host = $("#app_host").val();
	var app_status = $("#slt_status").val();
	var maintance_notice = $("#notice").val();
	var white_ip_list = $("#white_ip_list").val();
	var black_ip_list = $("#black_ip_list").val();
	var dev_id_list = $("#dev_id_list").val();
	var test_id_list = $("#test_id_list").val();
	var external_api_key = $("#external_api_key").val();
	var external_api_secret = $("#external_api_secret").val();
	var external_open = $("#external_open").val();
	
	var dt = {
		app_id:app_id, app_name:app_name, app_title:app_title, app_link:app_link, app_host:app_host,
		app_status:app_status, maintance_notice:maintance_notice, white_ip_list:white_ip_list,
		black_ip_list:black_ip_list, dev_id_list:dev_id_list, test_id_list:test_id_list,
		external_api_key:external_api_key, external_api_secret:external_api_secret, external_open:external_open
	};
	$.get('/appadminapi/updateappinfo?platform={%$platform%}', dt, function(data) {
		if(data.result == 1){
			alert('更新成功');
		} else{
			alert('请重试');
		}
	}, "json");
}

function preview()
{
	if (APP_INFO && APP_INFO.app_host != '') {
		var url = APP_INFO.app_host + '/index/maintance';
		window.open(url);
	} else {
		msgbox('警告', '应用主机域名地址未知', 250, 100);
	}
}

getAppInfo();

/*
$().ready(function() {
	$('.layer_global').Drags({
		handler: '.layer_global_title'
	});
});*/

</script>
</body>
</html>
