<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>监测[{%$uid%}] | 快乐岛主</title>
<link href="{%$staticUrl%}/apps/island/main_2011041101.css?v=1.01" rel="stylesheet" type="text/css" />
<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
<script src="{%$staticUrl%}/js/jquery.flashSlider-1.0.min.js" type="text/javascript"></script>
<style type="text/css">
<!--
a img,:link img,:visited img {
	border: 0 none;
}

object#swfcontent {
	display: inline;
}

.box {
	border: 1px solid #CCCCCC;
}
-->
</style>
</head>
<body>
<div class="main" style="height:800px;">
{%include file="menu.phtml"%}
<div style="clear:both;"></div>
	<div id="main_content" style="background-color:#7accef;width:748px;height:600px;">
		<div id="loadingdiv" style="position: absolute; left: 260px; top: 350px;"><img src="{%$staticUrl%}/apps/island/images/common/loading1.gif" title="加载中..." alt="加载中..."/></div>
		<div id="flashdiv"></div>
		<script src="{%$staticUrl%}/js/swfobject.js" type="text/javascript"></script>
		<script type="text/javascript">
			var VIEWER_ID = {%$uid%};
			var OWNER_ID = VIEWER_ID;
			var FIRST_LOGIN = {%$newuser%};

			function getCookie(name) {
				var arr = document.cookie.match(new RegExp('(^| )'+name+'=([^;]*)(;|$)'));
				if(arr != null) return unescape(arr[2]); return null;
			}
			var hf_skey = getCookie('hf_skey');
			if (hf_skey) {
				var flashVars={"ver":"5","pNum":"10","uid":"{%$uid%}","loadingUi":"{%$staticUrl%}/swf/loadingUi2.swf?v=2011070701", "interfaceUrl":"{%$hostUrl%}/api/initswf?v=2011060101","snsType":"weibo","charge":"1","pic1":"{%$staticUrl%}/html/b/images/load01.jpg","pic2":"{%$staticUrl%}/html/b/images/load02.jpg","friendhelpName":"{% $friendhelpName %}", "friendhelpCoin":"{% $friendhelpCoin %}"};
	        	var params = { base: "{%$staticUrl%}/", allowScriptAccess: "always", menu:"false", allowFullScreen: "true", bgcolor: "#7accef", align: "middle", quality: "high"};
	        	var attrs = { id: "islandLoader", name: "islandLoader" };
	        	swfobject.embedSWF("{%$staticUrl%}/swf/islandLoader.swf?v=2011070701", "flashdiv",  "748", "600", "10.0", "{%$staticUrl%}/expressInstall.swf", flashVars, params, attrs);
	        } else {
	        	var html = '<div style="padding-top:50px;color:red;font-size:14px;text-align:center;">检测到您的浏览器没有开启或接收Cookie！请尝试开启后，重新进入。</div>'
	        	$('#flashdiv').html(html);
	        }

	        function hideLoading()
	        {
	        	$('#loadingdiv').hide();
	        }
		</script>
	</div>
</div>
<script type="text/javascript">

	function showuser(uid, name, face)
	{
		OWNER_ID = uid;
		var userinfo = document.getElementById('userinfo');
		if (userinfo) {
			if (OWNER_ID != VIEWER_ID) {
				userinfo.innerHTML = ' [当前好友门牌号：' + OWNER_ID + ']';
			} else {
				userinfo.innerHTML = '';
			}
		}
	}
</script>

{%include file="footer.phtml"%}
</body>
</html>