<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>邀请朋友 - 快乐岛主</title>
<link href="{%$staticUrl%}/apps/island/css_2011041102.css?v=1.01" rel="stylesheet" type="text/css" />
<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
<script src="{%$staticUrl%}/js/jquery.flashSlider-1.0.min.js" type="text/javascript"></script>
<style type="text/css">
<!--
a img,:link img,:visited img {
	border: 0 none;
}
-->
</style>
</head>
<body>
<div class="main">
	{%include file="menu.phtml"%}
	<div id="main_content" class="content" style="padding-top:2px;">
		<div class="gift_friend_area_1" style="background-image: url('{%$staticUrl%}/apps/island/images/invite/invitehead.gif');"></div>
		<div class="gift_friend_area_2" style="width:750px;height:510px;">
    		<div class="gift_friend_left">
        		<div class="gift_item"><img src="{%$user.face%}" width="76" height="76" />
        		<div class="txt">{%$user.name|escape%}</div>
        		</div>
        		<div style="display:none">{%$friendNum%}|{%$pageSize%}|{%$pageNum%}</div>
    		</div>
    		<div id="friend_content" class="gift_friend_right" style="height:450px;"></div>
    		<div id="div_send_button" align="center" style="clear:both;padding-top:5px;">
    		{%if $friendNum > 0 %}
    			<input id="btnSend" type="image" height="30px" src="{%$staticUrl%}/apps/island/images/invite/doinvit.gif"  onclick="send();" />
    			<input id="btnSendDisabled" style="display:none;" type="image" src="{%$staticUrl%}/apps/island/images/gift/send_disabled.gif" onclick="return false;" />
    		{%/if%}
    		</div>
		</div>
		<div class="gift_friend_area_3"></div>
	</div>

<div style="width: 417px; display: none;" class="layer_global" id="queryDiv">
	<div class="layer_global_main">
		<div class="layer_global_title"><h3>邀请好友</h3><button title="close" id="closeQuery" onclick="closeQuery();"><span class="none">╳</span></button></div>
		<div class="layer_global_cont">
			<div style="margin: 20px;" class="wrap"><span id="gift_send_result"></span></div>
		</div>
	</div>
</div>
</div>
{%include file="cmscript.phtml"%}
<script type="text/javascript">
	var _hfconfig = {
        appUrl:"http://game.weibo.com/{%$smarty.const.APP_NAME%}",
        appId:"{%$appId%}",
        appKey:"{%$appKey%}",
        userId:"{%$uid%}",
		platformUid:"{%$platformUid%}",
		staticUrl:"{%$staticUrl%}",
        inviteCallbackUrl:"{%$hostUrl%}/callback/invite",
        freegiftLink:"",
        gameMode:"opaque"
    };

	var FRIEND_LIST = {%$friendList%};
	var FRIEND_NUM = {%$friendNum%};
	var FRIEND_PER_PAGE = {%$pageSize%};
	var FRIEND_PAGE_NUM = {%$pageNum%};
	var FRIEND_CURPAGE = {%$curPage%};
	var STATIC_URL = _hfconfig.staticUrl;
	var sendCounter = 0;

	function escapeHTML(html)
	{
		var escaped = html;
		/*var findReplace = [[/&/g, "&amp;"], [/</g, "&lt;"], [/>/g, "&gt;"], [/"/g, "&quot;"]];
		for(var item in findReplace) {
    		escaped = escaped.replace(item[0], item[1]);
    	}*/
		escaped = escaped.replace(/&/g, '&amp;');
		escaped = escaped.replace(/</g, '&lt;');
		escaped = escaped.replace(/>/g, '&gt;');
		escaped = escaped.replace(/"/g, '&quot;');
    	return escaped;
	}

	function check(id)
	{
		var boxid = 'boxid_' + id;
		var obj = document.getElementById(boxid);
		if(obj){
			if (obj.checked) {
				sendCounter--;
				if (FRIEND_LIST[id]) {
					FRIEND_LIST[id].selected = 1;
				}
			} else {
				sendCounter++;
				if (FRIEND_LIST[id]) {
					FRIEND_LIST[id].selected = 0;
				}
			}
        }
	}

	function send()
	{
		var fids = [];
		var fnames = [];
		//for(var i = 0 ; i < FRIEND_NUM; i++) {
		for(var i = 0 ; i < FRIEND_PER_PAGE; i++) {
			if (FRIEND_LIST[i] && FRIEND_LIST[i].selected) {
				fids.push(FRIEND_LIST[i].uid);
				fnames.push(FRIEND_LIST[i].name);
				//FRIEND_LIST[i].selected = 0;
			}
		}
		if (fids.length == 0) {
			return;
		}

		fids = fids.join(',');
		fnames = fnames.join(',');
//alert(fids);

HFApp.invite(_hfconfig.platformUid, fids, fnames, _hfconfig.inviteCallbackUrl);
return;
		//$('#btnSend').hide();
		//$('#btnSendDisabled').show();
		var pardata = {fids:fids};
	    if (_Config.hf_skey != "") {
	    	pardata['hf_skey'] = _Config.hf_skey;
	    }

		HFApp.inviteApi2(fids);
		return;

	    var param = {};
	    param[gadgets.io.RequestParameters.METHOD] = gadgets.io.MethodType.POST;
	    param[gadgets.io.RequestParameters.CONTENT_TYPE] = gadgets.io.ContentType.JSON;
	    param[gadgets.io.RequestParameters.POST_DATA] = gadgets.io.encodeValues(pardata);
	    param[gadgets.io.RequestParameters.AUTHORIZATION] = gadgets.io.AuthorizationType.NONE;
	    gadgets.io.makeRequest(_Config.giftsendUrl, function(response) {
		    var data = response.data;
	    	var html = '';
			if (data.errno != 0) {
				html = '发生错误[' + data.errno + ']';
			} else {
				html = '邀请人数:' + data.count + ',成功人数:' + data.num;
				GIFT_SEND_NUM -= data.num;
				sendCounter = GIFT_SEND_NUM;
				if (sendCounter > 0) {
					$('#btnSend').show();
					$('#btnSendDisabled').hide();
					$('#scount').html(sendCounter);
				}
				showPage(1);
			}
			$('#gift_send_result').html(html);
			$('#queryDiv').show();
	    }, param);

		/*$.post('/gift/send', dt, function(data) {
			var html = '';
			if (data.errno != 0) {
				html = 'Salah hantar data[' + data.errno + ']';
			} else {
				html = 'Jumlah kawan pilih:' + data.count + ',Jumlah berjaya hantar:' + data.num;
				GIFT_SEND_NUM -= data.num;
				sendCounter = GIFT_SEND_NUM;
				if (sendCounter > 0) {
					$('#btnSend').show();
					$('#btnSendDisabled').hide();
					$('#scount').html(sendCounter);
				}
				showPage(1);
			}
			$('#gift_send_result').html(html);
			$('#queryDiv').show();
		}, "json");*/
	}

	function closeQuery()
	{
		$('#queryDiv').hide();
	}

	function gotoPage(page)
	{
		location.href = '{%$hostUrl%}/invite/friends/page/'+page;
		return;
	}

	function showPage(i)
	{
		if (i <= 0 || (FRIEND_NUM > 0 && i > FRIEND_PAGE_NUM)) {
			return;
		}
		var html = ''
		if (FRIEND_NUM == 0) {
			html = '<div style="padding-top:100px;text-align:center">您的所有平台好友已全都加入快乐岛主!请邀请更多的站外好友!&nbsp;<a href="{%$baseUrl%}/invite/top">&gt;&gt;点击&lt;&lt;</a></div>';
		} else {
			curPage = i;
			var k = 0;
			//var start = (i-1) * FRIEND_PER_PAGE;
			var start = 0;
			var end = start + FRIEND_PER_PAGE;
			if (end > FRIEND_NUM) {
				end = FRIEND_NUM;
			}
			html = '<ul class="friendlist" style="height:420px;">';
			for(var j = start; j < end; j++) {
				if (FRIEND_LIST[j]) {
					html += '<li><div class="name_area"><div class="checkbox"><p><input name="ids[]" type="checkbox" value="'
						  + FRIEND_LIST[j].uid + '" id="boxid_' + j + '"';
					/*if (FRIEND_LIST[j].selected) {
						html+= ' checked="true"';
					} else {
						if (sendCounter <= 0) {
							html += ' disabled="true"';
						}
					}*/
					if (FRIEND_LIST[j].joint == '1') {
						html += ' disabled';
					}
					html += ' onclick="check(' + j + ');" /></p></div><div class="face"><img src="'
						 + FRIEND_LIST[j].face + '" /></div><div class="nickname">'
						 + escapeHTML(FRIEND_LIST[j].name) + '</div></div></li>';
				}
			}
			html += '</div></ul><div align="center" style="width:546px">';
			if (i > 1) {
				html += '<a href="javascript:void(0);" onclick="gotoPage(' + (i-1) + ');"> ' + '&lt; </a>&nbsp;';
			}
			for(j = 1; j <= FRIEND_PAGE_NUM; j++) {
				if (j != i) {
					html += '<a href="javascript:void(0);" onclick="gotoPage(' + j + ');"> ' + j + ' </a>&nbsp;';
				} else {
					html += ' ' + j + ' &nbsp;';
				}
			}
			if ( i < FRIEND_PAGE_NUM) {
				html += '<a href="javascript:void(0);" onclick="gotoPage(' + (i+1) + ');"> ' + '&gt; </a>&nbsp;';
			}
			html += '</div>';
		}

		$('#friend_content').html(html);
	}

	showPage(FRIEND_CURPAGE);
</script>
</body>
</html>