<?php

$swfList_0 = array(
	STATIC_HOST . '/swf/tweenMax.swf?v=2011102501',
	STATIC_HOST . '/swf/islandLib.swf?v=2011102501',
	STATIC_HOST . '/swf/newYearIcon.swf?v=2012011301',
	STATIC_HOST . '/swf/swc.swf?v=2011061402',
	STATIC_HOST . '/swf/swc2.swf?v=2011051801',
	STATIC_HOST . '/swf/swc3.swf?v=2011051801',
	STATIC_HOST . '/swf/swc4.swf?v=2011051801',
	STATIC_HOST . '/swf/swc5.swf?v=2011051801',
	STATIC_HOST . '/swf/preloadUi2.swf?v=2011051801',
	STATIC_HOST . '/swf/levelUp.swf?v=2011051801',
	STATIC_HOST . '/swf/island1.swf?v=2011051801',
	STATIC_HOST . '/swf/sky1.swf?v=2011051801',
	STATIC_HOST . '/swf/sea1.swf?v=2011051801',
	STATIC_HOST . '/swf/dock1.swf?v=2011051801',
	STATIC_HOST . '/swf/boat1.swf?v=2011051801',
	STATIC_HOST . '/swf/itemcard1.swf?v=2011060701',
	STATIC_HOST . '/swf/player1.swf?v=2011051801',
	STATIC_HOST . '/swf/sound1.swf?v=2011051801',
	STATIC_HOST . '/swf/chongzhiIcon.swf?v=2011051801',
	STATIC_HOST . '/swf/actIconSwc.swf?v=2011060701',
	STATIC_HOST . '/swf/newYearIcon.swf?v=2012011301',
	STATIC_HOST . '/swf/signWinUi.swf?v=2011052701',
	STATIC_HOST . '/swf/godCard.swf?v=2011051801',
	STATIC_HOST . '/swf/upgradeIsland.swf?v=2011062201',

	STATIC_HOST . '/swf/building1.swf?v=2011051801',
	STATIC_HOST . '/swf/building2.swf?v=2011051801',
	STATIC_HOST . '/swf/building3.swf?v=2011051801',
	STATIC_HOST . '/swf/building4.swf?v=2011051801',
	STATIC_HOST . '/swf/diary.swf?v=2011062301',
	STATIC_HOST . '/swf/synthetic.swf?v=2011062301',
	STATIC_HOST . '/swf/supervisitor1.swf?v=2011062301',
    STATIC_HOST . '/swf/SpVisitor1.swf?v=2012010301',
    STATIC_HOST . '/swf/playert.swf?v=2011090901',
    STATIC_HOST . '/swf/CatchFishjianti.swf?v=2011090901',
    STATIC_HOST . '/swf/CatchFishTask.swf?v=2011090901',
	STATIC_HOST . '/swf/CatchFishFishRace.swf?v=2011090901',
	STATIC_HOST . '/swf/CatchFishleitaisai.swf?v=2011090901',
);
$backSwfs_0 =  array(
	STATIC_HOST . '/swf/tweenMax.swf?v=2011102501',
	STATIC_HOST . '/swf/islandLib.swf?v=2011102501',
	STATIC_HOST . '/swf/building5.swf?v=2011051801',
	STATIC_HOST . '/swf/building6.swf?v=2011051801',
	STATIC_HOST . '/swf/building7.swf?v=2011051801',
	STATIC_HOST . '/swf/building8.swf?v=2011051801',
	STATIC_HOST . '/swf/building9.swf?v=2011051801',
	STATIC_HOST . '/swf/building10.swf?v=2011051801',
	STATIC_HOST . '/swf/building11.swf?v=2011051801',
	STATIC_HOST . '/swf/building12.swf?v=2011061301',
	STATIC_HOST . '/swf/building13.swf?v=2011102101',
	STATIC_HOST . '/swf/building14.swf?v=2011101901',
	STATIC_HOST . '/swf/building15.swf?v=2011112101',
	STATIC_HOST . '/swf/building16.swf?v=2011112101',
	STATIC_HOST . '/swf/building17.swf?v=2011122001',	
	STATIC_HOST . '/swf/CatchFishResource.swf?v=2011122001',	
	STATIC_HOST . '/swf/building18.swf?v=2011122001',	
	STATIC_HOST . '/swf/CatchFishIsland3.swf?v=2011090901',
);

$swfList_1 = array(
	STATIC_HOST . '/swf/tweenMax.swf?v=2011102501',
	STATIC_HOST . '/swf/islandLib.swf?v=2011102501',
	STATIC_HOST . '/swf/swc.swf?v=2011061402',
	STATIC_HOST . '/swf/swc2.swf?v=2011051801',
	STATIC_HOST . '/swf/swc3.swf?v=2011051801',
	STATIC_HOST . '/swf/swc4.swf?v=2011051801',
	STATIC_HOST . '/swf/swc5.swf?v=2011051801',
	STATIC_HOST . '/swf/preloadUi2.swf?v=2011051801',
	STATIC_HOST . '/swf/levelUp.swf?v=2011051801',
	STATIC_HOST . '/swf/island1.swf?v=2011051801',
	STATIC_HOST . '/swf/sky1.swf?v=2011051801',
	STATIC_HOST . '/swf/sea1.swf?v=2011051801',
	STATIC_HOST . '/swf/dock1.swf?v=2011051801',
	STATIC_HOST . '/swf/boat1.swf?v=2011051801',
	STATIC_HOST . '/swf/itemcard1.swf?v=2011060701',
	STATIC_HOST . '/swf/player1.swf?v=2011051801',
	STATIC_HOST . '/swf/sound1.swf?v=2011051801',
	STATIC_HOST . '/swf/chongzhiIcon.swf?v=2011051801',
	STATIC_HOST . '/swf/actIconSwc.swf?v=2011060701',
	STATIC_HOST . '/swf/newYearIcon.swf?v=2012011301',
	STATIC_HOST . '/swf/signWinUi.swf?v=2011052701',
	STATIC_HOST . '/swf/godCard.swf?v=2011051801',
	STATIC_HOST . '/swf/upgradeIsland.swf?v=2011062201',
	STATIC_HOST . '/swf/newYearIcon.swf?v=2012011301',

	STATIC_HOST . '/swf/building1.swf?v=2011051801',
	STATIC_HOST . '/swf/building2.swf?v=2011051801',
	STATIC_HOST . '/swf/building3.swf?v=2011051801',
	STATIC_HOST . '/swf/building4.swf?v=2011051801',
	STATIC_HOST . '/swf/building5.swf?v=2011051801',
	STATIC_HOST . '/swf/building6.swf?v=2011051801',
	STATIC_HOST . '/swf/building7.swf?v=2011051801',
	STATIC_HOST . '/swf/building8.swf?v=2011051801',
	STATIC_HOST . '/swf/building9.swf?v=2011051801',
	STATIC_HOST . '/swf/building10.swf?v=2011051801',
	STATIC_HOST . '/swf/building11.swf?v=2011051801',
	STATIC_HOST . '/swf/building12.swf?v=2011061301',
	STATIC_HOST . '/swf/building13.swf?v=2011102101',
	STATIC_HOST . '/swf/building14.swf?v=2011101901',
	STATIC_HOST . '/swf/building15.swf?v=2011112101',
	STATIC_HOST . '/swf/building16.swf?v=2011112101',
	STATIC_HOST . '/swf/building17.swf?v=2011122001',
	STATIC_HOST . '/swf/CatchFishResource.swf?v=2011122001',		
	STATIC_HOST . '/swf/building18.swf?v=2011122001',	
	STATIC_HOST . '/swf/signWinUi.swf?v=2011061301',
	STATIC_HOST . '/swf/diary.swf?v=2011062301',
	STATIC_HOST . '/swf/synthetic.swf?v=2011062301',
	STATIC_HOST . '/swf/supervisitor1.swf?v=2011062301',
    STATIC_HOST . '/swf/SpVisitor1.swf?v=2012010301',
    STATIC_HOST . '/swf/playert.swf?v=2011090901',
    STATIC_HOST . '/swf/CatchFishIsland2.swf?v=2011090901',
    STATIC_HOST . '/swf/CatchFishjianti.swf?v=2011090901',
    STATIC_HOST . '/swf/CatchFishTask.swf?v=2011090901',
	STATIC_HOST . '/swf/CatchFishFishRace.swf?v=2011090901',
	STATIC_HOST . '/swf/CatchFishleitaisai.swf?v=2011090901',
	STATIC_HOST . '/swf/CatchFishIsland3.swf?v=2011090901',
);
$backSwfs_1 =  array();

$otherSwfs = array(
	'localeTxt'         => STATIC_HOST . '/',
	'help'              => STATIC_HOST . '/swf/helpV2View.swf?v=2011060301',
	'news'				=> STATIC_HOST . '/swf/news.swf?v=2011061601',
	'exmall'			=> STATIC_HOST . '/swf/externalMallPanel.swf?v=2011051801',
	'tweenMax'			=> STATIC_HOST . '/swf/tweenMax.swf?v=2011102501',
	'islandLib'			=> STATIC_HOST . '/swf/islandLib.swf?v=2011102501',
	'building1'			=> STATIC_HOST . '/swf/building1.swf?v=2011051801',
	'building2'			=> STATIC_HOST . '/swf/building2.swf?v=2011051801',
	'building3'			=> STATIC_HOST . '/swf/building3.swf?v=2011051801',
	'building4'			=> STATIC_HOST . '/swf/building4.swf?v=2011051801',
	'building5'			=> STATIC_HOST . '/swf/building5.swf?v=2011051801',
	'building6'			=> STATIC_HOST . '/swf/building6.swf?v=2011051801',
	'building7'			=> STATIC_HOST . '/swf/building7.swf?v=2011051801',
	'building8'			=> STATIC_HOST . '/swf/building8.swf?v=2011051801',
	'building9'			=> STATIC_HOST . '/swf/building9.swf?v=2011051801',
	'building10'		=> STATIC_HOST . '/swf/building10.swf?v=2011051801',
	'building11'		=> STATIC_HOST . '/swf/building11.swf?v=2011051801',
	'building12'		=> STATIC_HOST . '/swf/building12.swf?v=2011061301',
	'building13'		=> STATIC_HOST . '/swf/building13.swf?v=2011061301',
	'building14'		=> STATIC_HOST . '/swf/building14.swf?v=2011061301',
	'building15'		=> STATIC_HOST . '/swf/building15.swf?v=2011061301',
	'building16'		=> STATIC_HOST . '/swf/building16.swf?v=2011061301',
	'building17'		=> STATIC_HOST . '/swf/building17.swf?v=2011122001',
	'fishcard'			=> STATIC_HOST . '/swf/CatchFishResource.swf?v=2011122001',
	//'awardBox'			=> STATIC_HOST . '/swf/awardBox.swf?v=2011060701',
	'building18'		=> STATIC_HOST . '/swf/building18.swf?v=2011122001',
	'CatchFishIsland3'	=> STATIC_HOST . '/swf/CatchFishIsland3.swf.swf?v=2012031901',

	//'awardBox'			=> STATIC_HOST . '/swf/awardBox.swf?v=2011060701',
);

$mainswf = STATIC_HOST . '/swf/piao6Sns.swf?v=2011060701';

$bgMusic = STATIC_HOST . '/swf/sound1.mp3?v=2011051801';

// interface list
$interface = array(
    'swfHostURL'        => STATIC_HOST . '/swf/',
    'jpgHostURL'        => STATIC_HOST . '/jpg/',
    'interfaceHostURL'  => HOST . '/',
    'loadFriends'       => 'api/getfriends',
    'loadInit'          => 'api/inituser?v=2011080403',
    'loadIsland'        => 'api/initisland',
    'loadDock'          => 'api/initdock',
    'recive'            => 'api/receiveboat',
    'steal'             => 'api/moochvisitor',
    'dockUpgrade'       => 'api/addboat',
    'loadShop'          => 'api/loadshop',
    'loadItems'         => 'api/loaditems',
    'saleItems'         => 'api/saleitem',
    'useItem'           => 'api/usecard',
    'buyItem'           => 'api/buyitem',
    'saveDiy'           => 'api/diyisland',
    'loadDiary'         => 'api/readfeed',
    'loadUserInfo'      => 'api/inituserinfo',
    'changeHelp'        => 'api/changehelp',
 	'getStepAward'      => 'api/gethelpgift',
    'buildingPay'       => 'api/harvestplant',
    'takeBuildingEvent' => 'api/manageplant',
    'buildingUpgrade'   => 'api/upgradeplant',
    'buildingSteal'     => 'api/moochplant',
    'readTask'          => 'api/readtask',
    'finishTask'        => 'api/finishtask',
    'loadTitles'        => 'api/readtitle',
    'selectTitle'       => 'api/changetitle',
    'loadBoatClassState'=> 'api/readship',
    'selectBoat'        => 'api/changeship',
    'unLockBoat'        => 'api/unlockship',
    'loadRemind'        => 'api/readremind',
    'sendRemind'        => 'api/addremind',
    'getGemNum'			=> 'api/getgold',
	'getGiftList'		=> 'api/getgiftpackagelist',
	'openPack'			=> 'api/opengiftpackage',
	'updateGiftNum'		=> 'api/getgiftpackagenum',
	'useAllPay'			=> 'api/harvestallplant',
	'gainDailyAward'	=> 'api/gaindailyawards',
	'getLevelGift'		=> 'api/getlevelgift',
	'getStarGift'     	=> 'api/getstargift',
	'readStarGift'     	=> 'api/readstargift',
	'openNewIsland'		=> 'api/openisland',
	'FIMapIconTipState'	=> 'api/changeislandtip',
	'cleardiy'			=> 'api/cleardiy',
	'openallgift'       => 'api/openallgift',
	'saleCard'          => 'api/salecard',
	'freshOneHonor'			=> 'api/refreshtask',
	'islandUpgrade'			=> 'api/upgradeisland',
	'firstTouch'			=> 'api/firsttouch',
	'secondTouch'			=> 'api/secondtouch',
	'getnextgiftlevel'		=> 'api/getnextgiftlevel',
	'getlevelbiggift'		=> 'api/getlevelbiggift',
	'stopboat'				=> 'api/stopboat',
    'SVCollectionInitStatic'=> 'api/initcollection',
    'svStaticInit'          => 'api/initsupervisitor',
    'takeDemand'            => 'api/getsvgift',
    'svInit'                => 'api/getsvinfo',
    'SVCollectionInit'      => 'api/getcollectioninfo',
    'SVCollectionAlwaysChange'=> 'api/changecollection',

	'readYaoQingState'		=> 'event/getinviteflowstate',
	'getYaoQingStepAward'	=> 'event/inviteaward',
	'getgifttime'     			=> 'event/getgifttime',
	'receivetimegift'     		=> 'event/receivetimegift',
	'getnexttimegift'			=> 'event/getnexttimegift',
	'getDreamGardenAward'     	=> 'event/recivedreamgardenaward',
	'starfishExchange'          =>'event/starfishexchange',
    'starfishAndExternalMall'   =>'event/getstarfishexternalmall',
	'getteamBuydata'			=> 'event/teambuy',
	'teamBuyattendcommand'		=> 'event/jointeambuy',
	'teamBuyokcommand'			=> 'event/buygoods',
	'getFlashStomStatus'		=> 'event/getflashstomstatus',
	'feedFlashStormAward'		=> 'event/addstromcoin',
	'joinFullScreen'			=> 'event/fullscreen',
	'buySalesPack'     			=> 'event/salemall',
	'getfriendlist'             =>'event/getfriendlist',
	'sendremind'                =>'event/sendremind',
	'LUpAwardBoxOpened'			=> 'event/LUpAwardBoxOpened',
	'casinoinit'				=> 'event/casinoinit',
	'casinoraffle'				=> 'event/casinoraffle',
    'getgift'     				=> 'event/getgift',
	'collectiontask'     		=> 'event/collectiontask',
	'shaketree'     			=> 'event/shaketree',
	'getBottleList'				=> 'event/getBottleList',
	'getBottleInfo'				=> 'event/getBottleInfo',
	'bottleReceive'				=> 'event/bottleReceive',
	'bottleUserList'			=> 'event/bottleUserList',
	'getRank'                   => 'event/getrank',
	'exchangeFragment'			=>'event/exchangefragment',
	'goRecharge'				=> 'event/gopayonegold',
	'oneyuaninit'				=> 'event/onegoldshop',
	'getoneyuanaward'			=> 'event/getonegoldgift',
	'getoneyuanboxinfor'		=> 'event/getboxinfo',
	'getawardboxgift'			=> 'event/getonegoldboxgift',
	'valentineActBegin'			=> 'event/loadvalentine',
	'vTransLateRose'			=> 'event/exchangevalentine',
	'toSendRose'				=> 'event/loadvalentinerose',
	'selectAndSendOutRose'		=> 'event/sendvalentinerose',
	'selectAndAskForRose'		=> 'event/askvalentinerose',
	'vToBuyRose'				=> 'event/buyvalentinerose',
	'vTogetRankList'			=> 'event/loadvalentinerank',
	'tanabataExchange'          => 'event/exchangeqixi',
	'tanabataGift'              => 'event/getqixigift',
	'initExchangeTCoin'			=> 'event/amoygoldinit',
	'exchangeTCoin'				=> 'event/getamoygoldgift',
	'HW_halloweenInit'			=> 'event/halloweeninit',
	'HW_chooseCard'				=> 'event/hallchoosecard',
	'HW_exchangeList'			=> 'event/exchangelist',
	'HW_toExchange'				=> 'event/toexchange',
	'HW_tryAgain'				=> 'event/refrushcardchance',
	'HW_toExchangeB'			=> 'event/replenishcard',
	'SD_init'					=> 'event/getbuynum',
	'SD_update'					=> 'event/gradeupbridal',
	'SD_present'				=> 'event/tosendbridal',
	'SD_friends'				=> 'event/getfriendlistbridal',
	'TG_init'					=> 'event/thdayinit',
	'TG_buyRobot'				=> 'event/thdayrobot',
	'TG_checkIn'				=> 'event/thdaycheckin',
	'TG_exchange'				=> 'event/thdayexch',
	'TG_rankingList'			=> 'event/thdayrank',
	'TG_dismiss'				=> 'event/thdaydismiss',
	'TG_replenish'				=> 'event/thdaycomplete',
	'TG_getFeed'				=> 'event/thdaysendfeed',
	'TG_buyLove'				=> 'event/thdaybuylove',
	'saleMaterial'              => 'api/salepaper',
	'buildingSynthetic'			=>'api/compound',
	'buildingResolve'           =>'api/resolve',
	'blackMarketInit'			=>'api/initsupermarket',
	'demand'                    =>'api/demandmaterial',
	'blackMarketBuy'			=>'api/buyfrommarket',
	'repairFuncBuilding'		=>'api/repairfuncbuilding',
	'initResolveRate'				=>'api/initresolverate',
	'MerryChristmasInit'			=> 'event/christmasinit',
	'MerryChristmasRequest'			=> 'event/christmastask',
	'MerryChristmasUser'			=> 'event/christmasfidlist',
	'MerryChristmasBuyBuilding'		=> 'event/chrismascomplete',
	'MerryChristmasItemVo'			=> 'event/chrismasgetplant',
	'MerryChristmasRecord'			=> 'event/christmasoncerequest',
	'MerryChristmasAwardRequest'	=> 'event/christmasgetinvitegift',
	'MerryChristmasBallRequest'		=> 'event/toexchangeprincess',
	'MerryChristmasGameStart'		=> 'event/chrismasmatchfawn',
	'initFuncBuildingBroadcast'		=>'api/getcompoundnotice',
	'DC_getConstellation'     	=> 'api/getstargift',
	'DC_buyConstellation'     	=> 'api/buygift',
	'DC_getAthena'				=> 'api/changeathena',
	'HNY_init'						=> 'event/newdaysinit',
	'HNY_smash'						=> 'event/newdaysdropegg',
	'HNY_exchange'					=> 'event/newdaystoconvert',
	'AirfieldConnectPeople'			=> 'api/compoundreceiveboat',
	'getMedalInfo'					=> 'event/atlasbookinit',
	'upgradeMedal'					=> 'event/atlasbooklevelup',
	'getMingXingExchangeInfo'		=> 'event/tochangeinit',
	'exchangeMingXingBuilding'		=> 'event/tochangeplant',
	'SpringFastivalInit'			=> 'event/springfastivalinit',
	'SFdecDumpling'					=> 'event/sfdecdumpling',
	'SFeatDumpling'					=> 'event/sfeatdumpling',
	'SFbuyLuckyBag'					=> 'event/sfbuyluckybag',
	'SFopenLuckyBag'				=> 'event/sfopenluckybag',
	'SFbuyRystal'					=> 'event/sfbuyrystal',
	'SFtoReceiveBox'				=> 'event/sftoreceivebox',
	'SFbuyFragment'					=> 'event/sfbuyfragment',
	'SFtoReceivePlant'				=> 'event/sftoreceiveplant',
	'SFupgradePlant'				=> 'event/sfupgradeplant',
	'CatchFishInitStatic'			=> 'api/getfishstatic',
	'CatchFishIllustratedHandbookInit'	=>	'api/getfishuser',
	'CatchFishRequest'				=> 'api/catchfish',
	'CatchFishInit'					=> 'api/fishinit',
	'CatchFishBuyCard'				=> 'api/fishbuycard',
	'CatchFishSetSail'				=> 'api/setsail',
	'CatchFishQuicklyGo'			=> 'api/quicklygo',
	'CatchFishStopIsland'			=> 'api/stopisland',
	'CatchFishRelicBuildingInit'	=> 'api/getuserrelic',
	'CatchFishBuildRelic'			=> 'api/relicchange',
	'CatchFishupGrade'				=> 'api/relicupgrade',
	'CatchFishCoolover'				=> 'api/reducefishtime',
	'CatchFishRelicBuildingInit'	=> 'api/getuserrelic',
	'CatchFishBuildRelic'			=> 'api/relicchange',
	'CatchFishupGrade'				=> 'api/relicupgrade',
	'CatchFishFragmentInit'			=> 'api/getuserfragment',
	'CatchFishCardExInit'			=> 'api/fishcardinit',
	'CatchFishCardEx'				=> 'api/fishchangecard',
	'CatchFishTaskInit'				=> 'api/catchfishtaskinit',
	'CatchFishGetTaskAward'			=> 'api/catchfishgettaskaward',
	'getMingXingExchangeInfo'		=> 'event/tochangeinit',
	'exchangeMingXingBuilding'		=> 'event/tochangeplant',
	'SpringFastivalInit'			=> 'event/springfastivalinit',
	'SFdecDumpling'					=> 'event/sfdecdumpling',
	'SFeatDumpling'					=> 'event/sfeatdumpling',
	'SFbuyLuckyBag'					=> 'event/sfbuyluckybag',
	'SFopenLuckyBag'				=> 'event/sfopenluckybag',
	'SFbuyRystal'					=> 'event/sfbuyrystal',
	'SFtoReceiveBox'				=> 'event/sftoreceivebox',
	'SFbuyFragment'					=> 'event/sfbuyfragment',
	'SFtoReceivePlant'				=> 'event/sftoreceiveplant',
	'SFupgradePlant'				=> 'event/sfupgradeplant',
	'getYuanXiaoInfo'				=> 'event/lanternfestivalinit',
	'getYuanXiaoBuilding'			=> 'event/getlfplant',
	'startYuanXiaoCooking'			=> 'event/tolfcook',
	'addYuanXiaoCookTimes'			=> 'event/buylfcooktimes',
	'buyYuanXiaoFood'				=> 'event/buylffood',
	'ValentinePlantInfo'			=> 'event/valentinedayinit',
	'ValentineRoseInfo'				=> 'event/valentinedayroseinfo',
	'ValentinePlant'				=> 'event/valentinedayplant',
	'ValentineFertilizer'			=> 'event/valentinedayfertilize',
	'ValentineGain'					=> 'event/valentinedaygain',
	'ValentineBuyBuilding'			=> 'event/valentinedaybuygarden',
	'ValentineExchangeInit'			=> 'event/valentinedayexchinit',
	'ValentineExchangeRequest'		=> 'event/changerose',
	'ValentineExchangeStatic'		=> 'event/initrosechange',
	'ValentinePlantSpeedUp'			=> 'event/valentinedaygainpass',
	'CatchFishAwardInit'			=>	'event/fishawardinit',
	'CatchFishAward'				=>	'event/fishawardex',
	'womenDayPackage'				=>'event/buywomenpackage',														
	'CatchFishFishGameInit'	=> 'fishmatch/initfish',
	'CatchFishGameFishChange' => 'fishmatch/switchfish',
	'CatchFishGameFishFound'	=>'fishmatch/compoundfish',
	'CatchFishGameFishLevelUp' =>'fishmatch/levelupfish',
	'CatchFishStartRace'	=>'fishmatch/pve',
	'CatchFishChartChange' 			=> 'api/changesea',
	'CatchFishEquipmentSkill'   => 'fishmatch/changeskill',
	'CatchFishAbandon'          => 'fishmatch/deletefish',
	'CatchFishEXMixCard'        => 'fishmatch/exchange',
	'CatchFishGuide'     => 'fishmatch/updateguide',
	'CatchFishBehindGetAward'=>'fishmatch/getaward',
	'CatchFishFriendRaceFishList'=>'fishmatch/getfriendfish',
	'CatchFishFriendRace'=>'fishmatch/pvp',
);
$setting = array(
	'charge'			=>  1,
	'checkOverlay'		=>  0,
	//'sixTimeGift'       =>  array(0,5,20,40,60,120),
	'sixTimeGift'       =>  array(0,0.1,0.2,0.3,0.4,0.5),
);

$swfResult_0 = array(
    'swfs'      => $swfList_0,
    'otherSwfs' => $otherSwfs,
	'backSwfs'	=> $backSwfs_0,
    'mainswf'   => $mainswf,
    'bgMusic'	=> $bgMusic,
    'interface' => $interface,
	'setting'	=> $setting,
);

$swfResult_1 = array(
    'swfs'      => $swfList_1,
    'otherSwfs' => $otherSwfs,
	'backSwfs'	=> $backSwfs_1,
    'mainswf'   => $mainswf,
    'bgMusic'	=> $bgMusic,
    'interface' => $interface,
	'setting'	=> $setting,
);