<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type">
<title>首页</title>
<link rel="stylesheet" type="text/css" href="{%$staticUrl%}/style/ozone.css">
<script src="{%$staticUrl%}/script/jquery.js" type="text/javascript"></script>
<script src="{%$staticUrl%}/script/jqext.js" type="text/javascript"></script>
<script src="{%$staticUrl%}/script/common.js" type="text/javascript"></script>
<script src="{%$staticUrl%}/script/FusionCharts.js" type="text/javascript"></script>

<!--
<link href="{%$staticUrl%}/style/DatePicker.css" type="text/css" rel="stylesheet" />
-->
<style type="text/css">@import url({%$staticUrl%}/script/calendar/jquery.datepick.css);</style>
<script src="{%$staticUrl%}/script/calendar/jquery.datepick.js" type="text/javascript"></script>
 
<style type="text/css">

.help_wrapper {background:url({%$staticUrl%}/image/infocenter/bg.png) repeat-x 0 -50px #FFF;border:#C6D3F3 solid 1px;padding:10px;margin-right:10px;}
.help_wrapper h2{font-size:16px;font-weight:bold;margin-bottom:10px;padding-bottom:5px;border-bottom:1px #f1f1e2 solid;}
.help_wrapper ul li{list-style:square;margin:20px;}
.help_wrapper ul ul{margin:15px 0 15px 30px;}
.help_wrapper ul ul li{margin:15px 0 15px 30px;list-style:disc;}

</style>

</head><body>
<div class="help_wrapper">
	<h2>系统说明</h2>
	<ul>
	   <li>本系统是为方便乐鱼数码APP运营管理的工具。</li>
	   <li>目前开放的功能:</li>
	   <ul>
		   <li>客服工具</li>
	       <li>运营工具</li>
	       <li>运维工具</li>
       </ul>
       <li>如您对此系统有任何意见或需求，可联系立军，谢谢~</li>   
	</ul>
</div>

<div style="display: none;"></div></body></html>