<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>限时抢购后台</title>
</head>
<body>
	<br />
	&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% $hostUrl %}/operate/index"><b>返回首页</b></a>
	<br /><br />
	<div>
		{% foreach from=$datavo item=data %}
			<form action="{%$hostUrl%}/operate/panicupdate" method="post">
				序号:<input type="text" name="data[sale_id]" size="2" value="{%$data.sale_id%}" />&nbsp;&nbsp;
				价格:<input type="text" name="data[sale_price]" size="5" value="{%$data.sale_price%}" />&nbsp;
				价格类型:<input type="text" name="data[sale_type]" size="4" value="{%$data.sale_type%}" />&nbsp;&nbsp;
				ID:<input type="text" name="data[cid]" size="15" value="{%$data.cid%}" />&nbsp;&nbsp;
				个数:<input type="text" name="data[num]" size="8" value="{%$data.num%}" />&nbsp;&nbsp;
				<!-- 金币:<input type="text" name="data[coin]" size="5" value="{%$data.coin%}" />&nbsp;
				海星:<input type="text" name="data[starfish]" size="4" value="{%$data.starfish%}" />&nbsp; -->
				数量限制:<input type="text" name="data[sale_num]" size="4" value="{%$data.sale_num%}" />&nbsp;&nbsp;
				开始时间:<input type="text" name="data[start_time]" size="20" value="{%$data.start_time|date_format:'%Y-%m-%d %H:%M:%S'%}" />&nbsp;&nbsp;
				结束时间:<input type="text" name="data[end_time]" size="20" value="{%$data.end_time|date_format:'%Y-%m-%d %H:%M:%S'%}" />
				<input type="submit" value="更新" />
			</form>
			<br />
		{% /foreach %}
	</div>
	<br />
	<form action="{%$hostUrl%}/operate/panicaddnew" method="post">
		<input type="submit" name="add" value="新加一条" />
	</form>
	<br />
	<form action="{%$hostUrl%}/operate/panicstatus" method="post">
		<input type="text" size="5" name="id" value="1" />
		<input type="submit" name="add" value="去除过期数据" />(输入ID)
	</form>
</body>
</html>