<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>工具首页</title>
<link media="screen" type="text/css" rel="stylesheet" href="{%$staticUrl%}/a/gb_app.css">
<style type="text/css">
<!--
html{overflow:scroll!important;}

body,td,th {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #333333;
}

a img,:link img,:visited img {
	border: 0 none;
}

.kfgj{ width:960px; height:auto;}
.title{	width:880px; height:50px; font-size:24px;color:#FFFFFF;line-height:50px;background-color: #B1CBE2;font-weight:bold; padding-left: 20px;}/*大标题*/
.title-02{ font-size:18px; color:#B1CBE2; line-height:50px; }
.cn-01{ width:850px; height:60px; padding-left: 50px; padding-top:20px; line-height:50px;}
.cn-02{	width:850px; padding-left: 50px; height:530px;   line-height:25px;}
.cn-03{	width:850px; padding-left: 50px; height:auto;line-height:25px;}

table{background-color:#B1CBE2;}
table caption{font-weight:bold;font-size:14px;}
table th{background-color:#D5E7F3;color:#333;text-align:center;font-weight:bold;border:1px;}
table td{text-align:center;font-weight:normal;background-color:#FFFFFF}

.userinfo-table{width:960px;}
.userinfo-table th{width:120px;}
.userinfo-table td{height:130px;}

.usercardinfo-table{width:800px;}
.usercardinfo-table .id{width:120px;}
.usercardinfo-table .name{width:160px;}
.usercardinfo-table .intro{width:400px;}
.usercardinfo-table .count{width:120px;}
.usercardinfo-table td{height:25px;text-align:left;padding-left:10px;}

.invitelog-table{width:800px;}
.invitelog-table .count{width:150px;}
.invitelog-table .time{width:200px;}
.invitelog-table .fid{width:450px;}
.invitelog-table td{height:25px;text-align:left;padding-left:10px;}

.goldlog-table{width:800px;}
.goldlog-table .time{width:150px;}
.goldlog-table .cost{width:150px;}
.goldlog-table .summary{width:500px;}
.goldlog-table td{height:25px;text-align:left;padding-left:10px;}

.paylog-table{width:950px;}
.paylog-table .time{width:150px;}
.paylog-table .amount{width:150px;}
.paylog-table .summary{width:430px;}
.paylog-table .orderid{width:220px;}
.paylog-table td{height:25px;text-align:left;padding-left:10px;}

.donatelog-table{width:540px;}
.donatelog-table .time{width:150px;}
.donatelog-table .amount{width:150px;}
.donatelog-table .orderid{width:220px;}
.donatelog-table td{height:25px;text-align:left;padding-left:10px;}

.leveluplog-table{width:800px;}
.leveluplog-table .from-level{width:150px;}
.leveluplog-table .to-level{width:150px;}
.leveluplog-table .time{width:500px;}
.leveluplog-table td{height:25px;text-align:left;padding-left:10px;}

.notice-table{width:900px;}
.notice-table .id{width:50px;}
.notice-table .titl{width:275px;}
.notice-table .link{width:250px;}
.notice-table .position{width:50px;}
.notice-table .opened{width:50px;}
.notice-table .time{width:125px;}
.notice-table td{height:25px;text-align:left;padding-left:10px;}

.userpraise-table{width:800px;}
.userpraise-table .cal{width:150px;}
.userpraise-table .cur{width:150px;}
.userpraise-table .info{width:500px;}
.userpraise-table td{height:25px;text-align:left;padding-left:10px;}

.logininfo-table{width:850px;}
.logininfo-table .time{width:250px;}
.logininfo-table .num{width:150px;}
.logininfo-table td{height:25px;text-align:center;padding-left:10px;}

.userplatforminfo-table{width:1000px;}
.userplatforminfo-table .time{width:250px;}
.userplatforminfo-table .txt{width:150px;}
.userplatforminfo-table .email{width:180px;}
.userplatforminfo-table td{height:25px;text-align:center;padding-left:10px;}

div,form,dl,dt,dd,img,h1,h2,h3,h4,h5,h6,ul,ol,li,p,span,table,th,td,a{margin:0;padding:0;border:0}
img{border:none;vertical-align:middle}
body{font-family:"宋体",Verdana,Arial,Helvetica,sans-serif;font-size:12px}
button{border:none;cursor:pointer;background:none;font-size:12px;text-align:center}

#msgboxDiv {display:none;position:absolute;}

-->
</style>
</head>
<body>
<div style="height:1500px; font-size:12px;">
	<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
	<script src="{%$staticUrl%}/js/utils.js?v=1.0" type="text/javascript"></script>

	<div class="cn-01">
		<label class="column" for="uid">查询用户森林门牌号：</label>
		<input type="text" class="text" style="ime-mode: disabled;" tabindex="1" name="uid" id="uid">
		<input type="checkbox" name="chkPUID" id="chkPUID" />是平台UID
		<input type="submit" tabindex="4" name="btsubmit" id="btsubmit" value="查 询" onclick="getUserInfo();">
	</div>

	<div id="userinfo_area" class="cn-02"></div>

	<div id="item_info_area" style="display:none;">
		<div class="cn-01">
			<label>选择要查询的项目：</label>
			<select id="sltItem" name="sltItem">
				<option value="0">平台扩展信息</option>
			    <!--  <option value="1">道具卡信息</option> -->
			    <!--  <option value="2">邀请好友记录</option> -->
			    <!--  <option value="3">爱心消耗记录</option> -->
			    <option value="4">升级记录</option>
			    <option value="5">金币消耗记录</option>
			    <option value="6">登录信息</option>
			    <option value="7">支付记录</option>
			    <option value="8">捐赠记录</option>
			</select>
			<input type="submit" value="查  询" id="btnItemSelect" name="btnItemSelect" onclick="showItem();">
			<div id="divLnkMore" style="display:none;"></div>
		</div>

		<div id="user_data_area" style="display:none;padding-top:10px;"></div>
	</div>

	<div style="width: 417px; display: none;" class="layer_global" id="msgboxDiv">
		<div class="layer_global_main">
			<div class="layer_global_title"><h3 id="msgboxTitle"></h3><button title="关闭" id="closeQuery" onclick="closeQuery();"><span class="none">╳</span></button></div>
			<div class="layer_global_cont">
				<div style="margin: 20px;" class="wrap"><span id="msgboxContent"></span></div>
			</div>
		</div>
	</div>

</div>
<script type="text/javascript">
var cache_uid = 0;

function timeFormat(time)
{
	var timestamp = time*1000;
	return (new Date(timestamp)).format('Y-m-d H:i:s');
}

function msgbox(title, msg, x, y)
{
	if (!x) x = 50;
	if (!y) y = 100;
	$('#msgboxDiv').css({left: x, top: y});
	$('#msgboxTitle').html(title);
	$('#msgboxContent').html(msg);
	$('#msgboxDiv').show();
}

function closeQuery()
{
	$('#msgboxDiv').hide();
	$('#divLnkMore').hide();
}

$.ajaxSetup({cache:false});

function getUserInfo()
{
	closeQuery();
	var uid = $('#uid').val();
	if (uid == '') {
		msgbox('错误', '请输入森林门牌号', 50, 100);
		return;
	}
	var ispuid = $('#chkPUID').attr("checked") ? 1:0;
	var dt = {uid:uid, ispuid:ispuid};
	$.get('/api/getuserinfo?platform={%$platform%}', dt, function(data) {
		if (data.errno == 0) {
			cache_uid = data.uid;
			var html = ['<table cellspacing="1" class="userinfo-table"><caption>用户信息</caption><tr><th>头像</th><th>平台UID</th><th>UID</th><th>用户名</th><th>个人主页</th><th>等级</th><th>经验</th><th>爱心</th><th>金币</th><th>状态</th><th></th></tr>'];
			html.push('<tr><td><img src="', data.face, '"/></td><td>', data.puid, '</td><td>', data.uid, '</td><td>', data.nickname, '</td><td><a href="', data.homeurl, '" target="_blank">访问</a></td><td>', data.level, '</td><td>', data.exp, '</td><td>', data.love, '</td><td>', data.gold, '</td>');

			if (data.status == 0) {
				html.push('<td id="user_status"><span style="color:green;">正常</span>&nbsp;&nbsp;<a href="javascript:void(0);" onclick="blockUser(', data.uid, ')" style="color:red;font-weight:bold;">封号</a></td>');
			} else {
				html.push('<td id="user_status"><span style="color:red;">不正常[', data.status, ']</span>&nbsp;&nbsp;<a href="javascript:void(0);" onclick="unblockUser(', data.uid, ')" style="color:green;font-weight:bold;">恢复</a></td>');
			}
			html.push('<td><a href="/api/watchuser?platform={%$platform%}&uid=', data.uid, '" target="_blank">查看森林</a></td>', '</tr></table>');

			html.push('<form action="{%$hostUrl%}/mail/sendmail" method="post" target="tgIframe" onsubmit="return sendMail();">');
			html.push('<table border=0 style="padding-top:20px;background:#fff">');
			html.push('<tr><td width="100%" colspan=2 style="text-align:left;"><h2>邮件发送</h2></td></tr>');
			html.push('<tr><td width="15%">邮件标题:</td><td style="text-align:left;"><input type="text" name="subject" id="subject" value="" style="width:400px;"></td></tr>');
			html.push('<tr><td>邮件内容:</td><td style="text-align:left;"><textarea style="width:400px;height:80px;" id="content" name="content"></textarea></td></tr>');
			html.push('<tr><td>内容模版:</td><td style="text-align:left"><input type="radio" name="demo" value="0" checked onclick="changeDemo(this.value);">无模版<input type="radio" name="demo" value="1" onclick="changeDemo(this.value);">森林玩家召回<td></tr>');
			html.push('<tr><td>目标邮箱:</td><td style="text-align:left"><textarea style="width:400px;height:100px;" id="email" name="email">' ,data.email, '</textarea></td></tr>');
			html.push('<tr><td></td><td style="text-align:left">[多个请用逗号分开 如:test_aa@qq.com,test_bb@qq.com]</td></tr>');
			html.push('<tr><td colspan=2 align=center><input type="submit" value="确认发送"></td></tr>');
			html.push('</table>');
			html.push('<input type="hidden" name="platform" value="{%$platform%}">');
			html.push('<input type="hidden" name="demoId" id="demoId" value="0">');
			html.push('</form>');
			
			$('#userinfo_area').html(html.join(''));
			$('#user_data_area').hide();
			$('#user_data_area').html('');
			$('#item_info_area').show();
		} else {
			$('#userinfo_area').html('');
			$('#item_info_area').hide();
			msgbox('错误', data.errmsg, 50, 100);
		}
	}, "json");
}

function changeDemo(v)
{
	$('#demoId').val(v);
}

function sendMail()
{
	var subject = $('#subject').val();
	var email = $('#email').val();
	if(subject == "" || email == "") {
		alert('标题、邮箱不能为空，请填写完整!');
		return false;
	}
	return true;
}

function getUserPlatformInfo()
{
	//var uid = $('#uid').val();
	var uid = cache_uid;
	var dt = {uid:uid};
	$.get('/api/getuserplatforminfo?platform={%$platform%}', dt, function(data) {
		if (data.errno == 0) {

			var html = ['<div class="cn-03"><table border="0" cellspacing="1" class="userplatforminfo-table"><caption>用户平台扩展信息</caption><tr><th class="txt">平台UID</th><th class="txt">用户昵称</th><th class="email">联系人email</th><th class="time">注册时间</th><th class="txt">用户类型</th><th class="txt">vip信息</th><th class="txt">是否开过店</th><th class="email">支付宝账户</th><th class="txt">支付宝ID</th></tr>'];
			if (data.info && data.info.user_id) {
				var info = data.info;
				html.push('<tr><td>', info.user_id, '</td><td>', info.nick, '</td><td>', info.email, '</td><td>', timeFormat(info.created), '</td><td>', info.type, '</td><td>', info.vip_info, '</td><td>', info.has_shop, '</td><td>', info.alipay_account, '</td><td>', info.alipay_no, '</td></tr>');
			}
			html.push('</table></div>');
			$('#user_data_area').html(html.join(''));
			$('#user_data_area').show();
		} else {
			msgbox('错误', data.errmsg, 50, 350);
		}
	}, "json");
}

function getLoginInfo()
{
	//var uid = $('#uid').val();
	var uid = cache_uid;
	var dt = {uid:uid};
	$.get('/api/getlogininfo?platform={%$platform%}', dt, function(data) {
		if (data.errno == 0) {
			var html = ['<div class="cn-03"><table border="0" cellspacing="1" class="logininfo-table"><caption>登陆信息</caption><tr><th class="time">最新登陆时间</th><th class="num">今日登陆次数</th><th class="num">连续登陆次数</th><th class="num">最大连续登陆次数</th><th class="num">登陆总次数</th></tr>'];
			html.push('<tr><td>', timeFormat(data.last_login_time), '</td><td>', data.today_login_count, '</td><td>', data.active_login_count, '</td><td>', data.max_active_login_count, '</td><td>', data.all_login_count, '</td></tr>');
			html.push('</table></div>');
			$('#user_data_area').html(html.join(''));
			$('#user_data_area').show();
		} else {
			msgbox('错误', data.errmsg, 50, 350);
		}
	}, "json");
}

function getGoldLog(isPrevMonth)
{
	//var uid = $('#uid').val();
	var uid = cache_uid;
	var dt = {uid:uid};
	var isPrev = '';
	if (isPrevMonth) {
		dt.prev = 1;
	}
	$.get('/api/getgoldlog?platform={%$platform%}', dt, function(data) {
		if (data.errno == 0) {
			var html = ['<div class="cn-03"><table border="0" cellspacing="1" class="goldlog-table"><caption>金币消耗记录</caption><tr><th class="time">时间</th><th class="cost">消耗金币</th><th class="summary">用途</th></tr>'];
			var logs = data.logs;
			if (logs.length == 0) {
				html.push('<tr><td colspan="3" style="text-align:center;">没有记录</td></tr>');
			} else {
				for(var i in logs) {
					html.push('<tr><td>', timeFormat(logs[i].create_time), '</td><td>', logs[i].cost, '</td><td>', logs[i].summary, '</td></tr>');
				}
			}
			html.push('</table></div>');
			$('#user_data_area').html(html.join(''));
			$('#user_data_area').show();
		} else {
			msgbox('错误', data.errmsg, 50, 350);
		}
	}, "json");
}

function getPayLog()
{
	//var uid = $('#uid').val();
	var uid = cache_uid;
	var dt = {uid:uid};
	$.get('/api/getpaylog?platform={%$platform%}', dt, function(data) {
		if (data.errno == 0) {
			var html = ['<div class="cn-03"><table border="0" cellspacing="1" class="paylog-table"><caption>充值记录</caption><tr><th class="time">时间</th><th class="amount">充值金额</th><th class="summary">描述</th><th class="orderid">订单号</th></tr>'];
			var logs = data.logs;
			if (logs.length == 0) {
				html.push('<tr><td colspan="4" style="text-align:center;">没有记录</td></tr>');
			} else {
				for(var i in logs) {
					html.push('<tr><td>', timeFormat(logs[i].create_time), '</td><td>', logs[i].amount, '</td><td>', logs[i].summary, '</td><td>', logs[i].orderid, '</td></tr>');
				}
			}
			html.push('</table></div>');
			$('#user_data_area').html(html.join(''));
			$('#user_data_area').show();
		} else {
			msgbox('错误', data.errmsg, 50, 350);
		}
	}, "json");
}

function getDonateLog()
{
	//var uid = $('#uid').val();
	var uid = cache_uid;
	var dt = {uid:uid};
	$.get('/api/getdonatelog?platform={%$platform%}', dt, function(data) {
		if (data.errno == 0) {
			var html = ['<div class="cn-03"><table border="0" cellspacing="1" class="donatelog-table"><caption>捐赠记录</caption><tr><th class="time">时间</th><th class="amount">捐赠金额</th><th class="orderid">订单号</th></tr>'];
			var logs = data.logs;
			if (logs.length == 0) {
				html.push('<tr><td colspan="3" style="text-align:center;">没有记录</td></tr>');
			} else {
				for(var i in logs) {
					html.push('<tr><td>', timeFormat(logs[i].create_time), '</td><td>', logs[i].amount, '</td><td>', logs[i].donateid, '</td></tr>');
				}
			}
			html.push('</table></div>');
			$('#user_data_area').html(html.join(''));
			$('#user_data_area').show();
		} else {
			msgbox('错误', data.errmsg, 50, 350);
		}
	}, "json");
}

function getLevelUpLog()
{
	//var uid = $('#uid').val();
	var uid = cache_uid;
	var dt = {uid:uid};
	$.get('/api/getleveluplog?platform={%$platform%}', dt, function(data) {
		if (data.errno == 0) {
			var html = ['<div class="cn-03"><table border="0" cellspacing="1" class="leveluplog-table"><caption>升级记录</caption><tr><th class="from-level">升级前等级</th><th class="to-level">升级后等级</th><th class="time">时间</th></tr>'];
			var logs = data.logs;
			if (logs.length == 0) {
				html.push('<tr><td colspan="3" style="text-align:center;">没有记录</td></tr>');
			} else {
				for(var i in logs) {
					html.push('<tr><td>', logs[i].from_level, '</td><td>', logs[i].to_level, '</td><td>', timeFormat(logs[i].create_time), '</td></tr>');
				}
			}
			html.push('</table></div>');
			$('#user_data_area').html(html.join(''));
			$('#user_data_area').show();
		} else {
			msgbox('错误', data.errmsg, 50, 350);
		}
	}, "json");
}

function blockUser(uid)
{
	var dt = {uid:uid};
	$.get('/api/blockuser?platform={%$platform%}', dt, function(data) {
		if (data.errno == 0) {
			msgbox('操作成功', '该用户已经被封禁', 250, 150);
			var html = '<span style="color:red;">不正常[1]</span>&nbsp;&nbsp;<a href="javascript:void(0);" onclick="unblockUser(' + uid + ')" style="color:green;font-weight:bold;">恢复</a>';
			$('#user_status').html(html);
		} else {
			msgbox('错误', data.errmsg, 250, 150);
		}
	}, "json");
}

function unblockUser(uid)
{
	var dt = {uid:uid};
	$.get('/api/unblockuser?platform={%$platform%}', dt, function(data) {
		if (data.errno == 0) {
			msgbox('操作成功', '该用户已经恢复正常', 250, 150);
			var html = '<span style="color:green;">正常</span>&nbsp;&nbsp;<a href="javascript:void(0);" onclick="blockUser(' + uid + ')" style="color:red;font-weight:bold;">封号</a>';
			$('#user_status').html(html);
		} else {
			msgbox('错误', data.errmsg, 250, 150);
		}
	}, "json");
}

function showItem()
{
	closeQuery();
	var item = $('#sltItem').val();
	switch (item) {
		case '0':
			getUserPlatformInfo();break;
		case '4':
			getLevelUpLog();break;
		case '5':
			var html = '<a href="javascript:void(0);" onclick="getGoldLog(1);">上一月</a> | <a href="javascript:void(0);" onclick="getGoldLog();">本月</a>';
			$('#divLnkMore').html(html).show();
			getGoldLog();break;
		case '6':
			getLoginInfo();break;
		case '7':
			getPayLog();break;
		case '8':
			getDonateLog();break;
	}
}

</script>
<iframe name="tgIframe" id="tgIframe" style="display:none;width:0;height:0;"></iframe>
</body>
</html>
