<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>魔幻炼金</title>
<link media="screen" type="text/css" rel="stylesheet" href="{%$staticUrl%}/a/gb_app.css">
<style type="text/css">
<!--
html{overflow:scroll!important;}

body,td,th {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #333333;
}

a img,:link img,:visited img {
	border: 0 none;
}

#data_area {
	margin-top:20px;
}

table{font-size:12px;border-collapse: collapse;border-spacing: 0;empty-cells: show;width: 1100px;}
table caption {
	font-weight:bold; font-size: 16px; color:#FF0000;
}
th, td {border: 1px solid #B1CBE2;}
th{background-color: #D5E7F3;padding:5px 5px;}
td{padding:2px 5px;}
-->
</style>
</head>
<body>
<br />
<br />
<div style="height:1500px; font-size:12px;">
	<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
	<span style="font-size:15px;font-weight:bold;">选择比较表:</span>
		<select id="slt_type" onchange="selectType(this.value)">
			<option value="-1">请选表名</option >&nbsp;&nbsp;
			{% foreach from=$list item=data key=key%}
			<option value="{%$key%}">{%$data%}</option>&nbsp;&nbsp;
			{% /foreach %}
		</select>
		<input type="hidden" id="table" value="all">
		<input type="button" value="全部比对" onclick="contrast();">
	<div id="data_area"></div>
</div>
<script type="text/javascript">

$.ajaxSetup({cache:false});

function getdata()
{	var table = $("#table").val();
	var dt = {table:table};
	$.get('/statapi/contrast?platform={%$platform%}', dt, function(data) {
		if (data) {
			var html = [];
			html.push('<table><tr><th>表名</th><th>开发服数据</th><th>正服</th></tr>');
			var content = data;
			if (content) {
				for(var i in content) {
					html.push('<tr');
	    			if (i%2 ==0) {
	    				html.push(' class="odd"');
	    			}
	    			html.push('><td>',content[i].table,'</td><td>', content[i].devdata, '</td><td>', content[i].data, '</td><tr/>');
				}
			}
			html.push('</table>');
			$('#data_area').html(html.join(''));
		} else {
			$('#data_area').html('获取数据失败');
		}
	}, "json");
}
function selectType(table)
{
	$("#table").val(table);
	getdata();
}
function contrast()
{
	$("#table").val('all');
	getdata();
}
</script>
</body>
</html>
