<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>捐赠金额走势</title>
<link media="screen" type="text/css" rel="stylesheet" href="{%$staticUrl%}/a/gb_app.css">
<link type="text/css" rel="stylesheet" href="{%$staticUrl%}/style/itil.css">
<style type="text/css">
<!--
html{overflow:scroll!important;}

body,td,th {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #333333;
}

a img,:link img,:visited img {
	border: 0 none;
}

table{font-size:12px;border-collapse: collapse;border-spacing: 0;empty-cells: show;margin-bottom:10px;width: 1100px;}
th, td {border: 1px solid #B1CBE2;}
th{background-color: #D5E7F3;padding:4px;}
td{padding:2px;}
.odd{background-color: #EAF2F5;}
.total{font-weight:bold;}
.memo{color: #FF0000;}
.low{display:none;}
-->
</style>
<style type="text/css">@import url({%$staticUrl%}/script/calendar/jquery.datepick.css);</style>
</head>
<body>
<div style="height:1500px; font-size:12px;">
	<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
	<script src="{%$staticUrl%}/js/utils.js?v=1.0" type="text/javascript"></script>
	<script src="{%$staticUrl%}/script/calendar/jquery.datepick.js?v=20110107" type="text/javascript"></script>
	<script src="{%$staticUrl%}/ofc/js/swfobject.js" type="text/javascript"></script>
	<div>
		<div id="searchTab" class="div7">
			<label style="padding-left: 15px;">统计开始日期：<input type="text" value="{%$startday%}" class="DatePicker" name="startday" id="startday"></label>
			<label style="padding-left: 15px;">统计结束日期：<input type="text" value="{%$endday%}" class="DatePicker" name="endday" id="endday"></label>
			<input type="button" name="submit" id="submit" onclick="javascript:getContent();" value="查看" />
		</div>
		<div id="div_chart" class="div1">
			<div id="chart1"></div>
			<div style="margin:20px;"></div>
		</div>
	</div>
	<div id="data_area" style="margin:10px;overflow-x:auto;"></div>

	<div id="rank_area" style="margin:10px;overflow-x:auto;"></div>

	<script type="text/javascript">
		var chart_data_1 = '{%$chart1%}';
		var swfReady = false;

		function findSWF(movieName)
		{
		  if (navigator.appName.indexOf("Microsoft")!= -1) {
		    return window[movieName];
		  } else {
		    return document[movieName];
		  }
		}

		function ofc_ready()
		{
			swfReady = true;
		}

		function open_flash_chart_data_1()
		{
		    return chart_data_1;
		}

		function showChart1()
		{
		  var tmp = swfobject.getObjectById('chart1');
		  if (tmp) {
		  	tmp.load(chart_data_1);
		  }
		}

		var params = { allowScriptAccess: "always", menu:"false", wmode: "opaque", allowFullScreen: "false", bgcolor: "#ffffff", align: "middle", quality: "high"};
		var flashvars1 = {'get-data': 'open_flash_chart_data_1'};
		swfobject.embedSWF("{%$staticUrl%}/ofc/open-flash-chart.swf", "chart1", "100%", "200", "9.0.0", null, flashvars1, params);
	</script>

</div>
<script type="text/javascript">

$.ajaxSetup({cache:false});

var cachedata = null;

function editMemo(id)
{
	var txtMemo = $('#txt_memo_' + id);
	var lblMemo = $('#memo_' + id);
	var editMemo = $('#edit_memo_' + id);
	if (txtMemo) {
		var val = lblMemo.text();
		txtMemo.val(val);
		txtMemo.show();
		txtMemo.focus();
		lblMemo.hide();
		editMemo.hide();
	}
}

function saveMemo(id, d)
{
	var txtMemo = $('#txt_memo_' + id);
	var lblMemo = $('#memo_' + id);
	var editMemo = $('#edit_memo_' + id);
	if (txtMemo) {
		var val = txtMemo.val();
		var oldVal = lblMemo.text();
		if (val != oldVal) {
			lblMemo.text(val);
			$.post('/statapi/editmemo?platform={%$platform%}', {day:d, memo:val});
		}
		txtMemo.hide();
		editMemo.show();
		lblMemo.show();
	}
}

function toggle()
{
	var name = $('#toggle').text();
	if (name == '>>|') {
		expand();
		$('#toggle').html('|&lt;&lt;');
	} else {
		shrink();
		$('#toggle').html('&gt;&gt;|');
	}
}

function expand()
{
	showTable(cachedata, false);
	$('#tb_retention_content').width(2200);
}

function shrink()
{
	showTable(cachedata, true);
	$('#tb_retention_content').width(1100);
}

function formateDate(day)
{
	return day.substr(0,4) + '-' + day.substr(4,2) + '-' + day.substr(6,2);
}

function showTable(content)
{
	var html = ['<table id="tb_retention_content"><tr><th rowspan="2">日期</th><th colspan="6">额度（元）</th></tr><tr><th>1</th><th>5</th><th>10</th><th>50</th><th>100</th><th>All</th></tr>'];

	if (content) {
		var sum0 = sum1 = sum5 = sum10 = sum50 = sum100 = 0;
		for(var i in content) {
			sum1 += content[i].donate[1];
			sum5 += content[i].donate[5];
			sum10 += content[i].donate[10];
			sum50 += content[i].donate[50];
			sum100 += content[i].donate[100];
			sum0 += content[i].donate[1] + content[i].donate[5] + content[i].donate[10] + content[i].donate[50] + content[i].donate[100];
			html.push('<tr');
			if (i%2 ==0) {
				html.push(' class="odd"');
			}
			html.push('><td style="text-align:center;width:100px;">', formateDate(content[i].log_time), '</td>');
			html.push('<td style="text-align:right">', content[i].donate[1], '</td>');
			html.push('<td style="text-align:right">', content[i].donate[5], '</td>');
			html.push('<td style="text-align:right">', content[i].donate[10], '</td>');
			html.push('<td style="text-align:right">', content[i].donate[50], '</td>');
			html.push('<td style="text-align:right">', content[i].donate[100], '</td>');
			html.push('<td style="text-align:right">', content[i].donate[0], '</td>');

			html.push('</tr>');
    	    /*html.push('<td id="td_memo_', i, '" align="center"><input id="txt_memo_', i, '" style="display:none;" onblur="saveMemo(\'', i, '\', \'',
				  content[i].log_time, '\');" /><lable id="edit_memo_', i, '"><span class="memo" id="memo_', i, '">', content[i].memo,
				  '</span>&nbsp;&nbsp;<a href="javascript:void(0);" onclick="editMemo(\'', i, '\')">编辑</a></lable></td></tr>');*/
		}

		html.push('<tr class="odd" style="font-weight:bold;"><td>合计(金额)</td>');
		html.push('<td style="text-align:right;font-weight:bold;">￥ ' + sum1 + '</td>');
		html.push('<td style="text-align:right;font-weight:bold;">￥ ' + sum5 + '</td>');
		html.push('<td style="text-align:right;font-weight:bold;">￥ ' + sum10 + '</td>');
		html.push('<td style="text-align:right;font-weight:bold;">￥ ' + sum50 + '</td>');
		html.push('<td style="text-align:right;font-weight:bold;">￥ ' + sum100 + '</td>');
		html.push('<td style="text-align:right;font-weight:bold;">￥ ' + sum0 + '</td>');
		html.push('</tr>');

	}

	html.push('</table>');
	$('#data_area').html(html.join(''));
}

function showRank(content)
{
	var html = ['捐赠排行<br/>','<table id="tb_ranking_content"><tr><th width="100">排名No</th><th width="160">UID</th><!--<th width="200">名字</th>--><th width="100">金额</th></tr>'];

	if (content) {
		for(var i in content) {
			html.push('<tr');
			if (i%2 ==0) {
				html.push(' class="odd"');
			}
			html.push('><td style="text-align:center;width:100px;">', (parseInt(i)+1), '</td>');
			html.push('<td>', content[i].uid, '</td>');
			//html.push('<td>', content[i].name, '</td>');
			html.push('<td style="text-align:right">', content[i].amt, '</td>');

			html.push('</tr>');
    	    /*html.push('<td id="td_memo_', i, '" align="center"><input id="txt_memo_', i, '" style="display:none;" onblur="saveMemo(\'', i, '\', \'',
				  content[i].log_time, '\');" /><lable id="edit_memo_', i, '"><span class="memo" id="memo_', i, '">', content[i].memo,
				  '</span>&nbsp;&nbsp;<a href="javascript:void(0);" onclick="editMemo(\'', i, '\')">编辑</a></lable></td></tr>');*/
		}
	}

	html.push('</table>');
	$('#rank_area').html(html.join(''));
}

function getContent()
{
	var startday = $("#startday").val();
	var endday = $("#endday").val();
	var dt = {startday:startday, endday:endday};
	$.get('/statapi/donateall?platform={%$platform%}', dt, function(data) {
		if (data.errno == 0) {
			var content = data.data;
			cachedata = content;
			showTable(content, true);
			if (data.chart1) {
				chart_data_1 = data.chart1;
				showChart1();
			}

			if (data.rank) {
				showRank(data.rank);
			}
		} else {
			$('#data_area').html('获取数据失败');
		}
	}, "json");
}

getContent();

</script>
</body>
</html>
