<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>粉丝数·熊猫问答数</title>
<link media="screen" type="text/css" rel="stylesheet" href="{%$staticUrl%}/a/gb_app.css">
<link type="text/css" rel="stylesheet" href="{%$staticUrl%}/style/itil.css">
<style type="text/css">
<!--
html{overflow:scroll!important;}

body,td,th {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #333333;
}

a img,:link img,:visited img {
	border: 0 none;
}

table{font-size:12px;border-collapse: collapse;border-spacing: 0;empty-cells: show;width: 100%;}
th, td {border: 1px solid #B1CBE2;}
th{background-color: #D5E7F3;}
td{padding:2px;}
.odd{background-color: #EAF2F5;}
.total{font-weight:bold;}
.right{text-align:right;}
-->
</style>
<style type="text/css">@import url({%$staticUrl%}/script/calendar/jquery.datepick.css);</style>
</head>
<body>
<div style="height:1500px; font-size:12px;">
	<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
	<script src="{%$staticUrl%}/js/utils.js?v=1.0" type="text/javascript"></script>
	<script src="{%$staticUrl%}/script/calendar/jquery.datepick.js?v=20110107" type="text/javascript"></script>
	<div id="searchTab" class="div7">
		<label style="padding-left: 15px;">开始日期:<input type="text" value="{%$startday%}" class="DatePicker" name="startday" id="startday"></label>
		<label style="padding-left: 15px;">结束日期:<input type="text" value="{%$endday%}" class="DatePicker" name="endday" id="endday"></label>
		<input type="button" name="submit" id="submit" onclick="javascript:getContent();" value="查看" />
	</div>
	<div id="data_area1" style="margin:10px;"></div>
	<br />
	<div id="data_area2" style="margin:10px;"></div>
	<br />
	<div id="data_area3" style="margin:10px;"></div>
</div>

<script type="text/javascript">
    $.ajaxSetup({cache:false});

    $(document).ready(function() {
    	getContent();
    });

    function getContent()
    {
    	var startday = $("#startday").val();
    	var endday = $("#endday").val();
    	var dt = {startday:startday, endday:endday};
    	$.get('/statapi/fans?platform={%$platform%}', dt, function(data) {
    		if (data.errno == 0) {
				//fans
    			var html = '每日粉丝加入数:<br/><table style="width:200px">';
    			var strHead = '<tr><th width="80px">日期</th><th>加入粉丝人数</th></tr>';
    			html += strHead;

    			var content = data.data;
    			if (content) {
    				for(var i in content) {
        				var log_time = content[i].log_time;
        				var ary_content = content[i].ary_content;
        				var strTd = '';
    					strTd += '<td align="right">' + ary_content.befan +'</td>';

    					var oddStyle = '';
        				if (i%2 == 1) {
        					oddStyle = 'odd';
        				}
            			html += '<tr class="'+ oddStyle +'">'
            				  + '<td >' + log_time + '</td>'
    						  + strTd
            				  + '</tr>';
    				}
    			}
    			html += '</table>';
    			$('#data_area1').html(html);

    			//question
    			var html = '熊猫问答数:<br/><table>';
    			var head1 = data.head1;
    			var strHead = '<tr><th> </th><th colspan="'+ head1.length +'">问题编号<br /> (被回答次数)</th></tr>';
    			strHead += '<tr><th>日期</th>';
    			for(var h in head1) {
    				if (head1[h] == '0') {
    					strHead += '<th>全部</th>';
    				}
    				else {
        				var strCol = head1[h];
        				//if (strCol == '20001') {strCol = '旺旺每日焦点推广';}
        				//else if (strCol == '20002') {strCol = '未知';}

    					strHead += '<th title="' + head1[h] + '">' + strCol + '</th>';
    				}
    			}
    			strHead += '</tr>';
    			html += strHead;

    			var content = data.data;
    			if (content) {
    				for(var i in content) {
        				var log_time = content[i].log_time;
        				var ary_content = content[i].ary_content;
        				var strTd = '';
        				for(var j in ary_content.pandaquestion) {
    						strTd += '<td>' + ary_content.pandaquestion[j] +'</td>';
        				}

    					var oddStyle = '';
        				if (i%2 == 1) {
        					oddStyle = 'odd';
        				}
            			html += '<tr class="'+ oddStyle +'">'
            				  + '<td >' + log_time + '</td>'
    						  + strTd
            				  + '</tr>';
    				}
    			}
    			html += '</table>';
    			$('#data_area2').html(html);


    			//guide
    			var html = '新手引导:<br/><table>';
    			var head2 = data.head2;
    			var strHead = '<tr><th> </th><th colspan="'+ head2.length +'">引导编号<br /> (完成比率)</th></tr>';
    			strHead += '<tr><th>日期</th>';
    			for(var h in head2) {
    				if (head2[h] == '0') {
    					strHead += '<th>当日新用户</th>';
    				}
    				else {
        				var strCol = head2[h];

    					strHead += '<th title="' + head2[h] + '">' + strCol + '</th>';
    				}
    			}
    			strHead += '</tr>';
    			html += strHead;

    			var content = data.data;
    			if (content) {
    				for(var i in content) {
        				var log_time = content[i].log_time;
        				var ary_content = content[i].ary_content;
        				var strTd = '';
        				for(var j in ary_content.guide) {
            				if (j == 0) {
            					strTd += '<td>' + ary_content.guide[j] +'</td>';
            				}
            				else {
            					var per = ((ary_content.guide[j]/ary_content.guide[0])*100).toFixed(2) + '%';
            					strTd += '<td title="' + ary_content.guide[j] + '">' + per +'</td>';
            				}

        				}

    					var oddStyle = '';
        				if (i%2 == 1) {
        					oddStyle = 'odd';
        				}
            			html += '<tr class="'+ oddStyle +'">'
            				  + '<td >' + log_time + '</td>'
    						  + strTd
            				  + '</tr>';
    				}
    			}
    			html += '</table>';
    			$('#data_area3').html(html);

    		} else {
    			$('#data_area1').html('获取数据失败');
    			$('#data_area2').html('获取数据失败');
    			$('#data_area3').html('获取数据失败');
    		}
    	}, "json");
    }
</script>
</body>
</html>