<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>平台feed数据统计</title>
<link media="screen" type="text/css" rel="stylesheet" href="{%$staticUrl%}/a/gb_app.css">
<link type="text/css" rel="stylesheet" href="{%$staticUrl%}/style/itil.css">
<style type="text/css">
<!--
html{overflow:scroll!important;}

body,td,th {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #333333;
}

a img,:link img,:visited img {
	border: 0 none;
}

table{font-size:12px;border-collapse: collapse;border-spacing: 0;empty-cells: show;width: 100%;}
th, td {border: 1px solid #B1CBE2;}
th{background-color: #D5E7F3;}
td{padding:2px;}
.odd{background-color: #EAF2F5;}
.total{font-weight:bold;}
.right{text-align:right;}
-->
</style>
<style type="text/css">@import url({%$staticUrl%}/script/calendar/jquery.datepick.css);</style>
</head>
<body>
<div style="height:1500px; font-size:12px;">
	<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
	<script src="{%$staticUrl%}/js/utils.js?v=1.0" type="text/javascript"></script>
	<script src="{%$staticUrl%}/script/calendar/jquery.datepick.js?v=20110107" type="text/javascript"></script>
	<div id="searchTab" class="div7">
		<label style="padding-left: 15px;">开始日期:<input type="text" value="{%$startday%}" class="DatePicker" name="startday" id="startday"></label>
		<label style="padding-left: 15px;">结束日期:<input type="text" value="{%$endday%}" class="DatePicker" name="endday" id="endday"></label>
		<input type="button" name="submit" id="submit" onclick="javascript:getContent();" value="查看" />
	</div>
	<div id="data_area" style="margin:10px;"></div>
</div>

<script type="text/javascript">
    $.ajaxSetup({cache:false});

    $(document).ready(function() {
    	getContent();
    });

    function getContent()
    {
    	var startday = $("#startday").val();
    	var endday = $("#endday").val();
    	var dt = {startday:startday, endday:endday};
    	$.get('/statapi/feed?platform={%$platform%}', dt, function(data) {
    		if (data.errno == 0) {
    			var html = '<table>';
    			var head1 = data.head;
    			var strHead = '<tr><th> </th><th colspan="'+ head1.length +'">feed编号<br /> (feed被发送数 / feed连接被点击数 / 通过feed连接进入游戏新用户数)</th></tr>';
    			strHead += '<tr><th>日期</th>';
    			for(var h in head1) {
    				if (head1[h] == '0') {
    					strHead += '<th>全部</th>';
    				}
    				else {
        				var strCol = head1[h];
        				if (strCol == '10001') {strCol = '用户升级';}
        				else if (strCol == '10002') {strCol = '扩地';}
        				else if (strCol == '10003') {strCol = '建设培育屋';}
        				else if (strCol == '10004') {strCol = '正确回答熊猫问题';}
        				else if (strCol == '10005') {strCol = '邀请好友';}
        				else if (strCol == '10006') {strCol = '动物死亡';}
        				else if (strCol == '10007') {strCol = '建筑升级';}
        				else if (strCol == '10008') {strCol = '解锁动物';}
        				else if (strCol == '10009') {strCol = '任务完成';}
        				else if (strCol == '10010') {strCol = '获得成就';}
        				else if (strCol == '10011') {strCol = '医治成功';}
        				else if (strCol == '10012') {strCol = '缺少材料';}
        				else if (strCol == '10013') {strCol = '缺少能量';}
        				else if (strCol == '10014') {strCol = '建造医院1';}
        				else if (strCol == '10015') {strCol = '建造医院2';}
        				else if (strCol == '10016') {strCol = '建造医院3';}
        				else if (strCol == '10017') {strCol = '建造医院4';}
    					strHead += '<th title="' + head1[h] + '">' + strCol + '</th>';
    				}
    			}
    			strHead += '</tr>';
    			html += strHead;

    			var content = data.data;
    			if (content) {
    				for(var i in content) {
        				var log_time = content[i].log_time;
        				var ary_feed_spread = content[i].ary_feed_spread;
        				var strTd = '';
        				for(var j in ary_feed_spread) {
            				//var aryStr = ary_feed_spread[j].split("|");
    						//strTd += '<td>'+aryStr[0] + aryStr[1] + aryStr[2] + '</td>';
    						strTd += '<td>' + ary_feed_spread[j].replace(/\|/g, ' / ') +'</td>';
        				}

    					var oddStyle = '';
        				if (i%2 == 1) {
        					oddStyle = 'odd';
        				}
            			html += '<tr class="'+ oddStyle +'">'
            				  + '<td >' + log_time + '</td>'
    						  + strTd
            				  + '</tr>';
    				}
    			}
    			html += '</table>';
    			$('#data_area').html(html);

    		} else {
    			$('#data_area').html('获取数据失败');
    		}
    	}, "json");
    }
</script>
</body>
</html>