<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>战斗信息</title>
<link media="screen" type="text/css" rel="stylesheet" href="{%$staticUrl%}/a/gb_app.css">
<link type="text/css" rel="stylesheet" href="{%$staticUrl%}/style/itil.css">
<style type="text/css">
<!--
html{overflow:scroll!important;}

body,td,th {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #333333;
}

a img,:link img,:visited img {
	border: 0 none;
}
#monterDiv {display:none;position:absolute;}
table{font-size:12px;border-collapse: collapse;border-spacing: 0;empty-cells: show;width: 100%;}
th, td {border: 1px solid #B1CBE2;}
th{background-color: #D5E7F3;padding:5px 5px;}
td{padding:2px 5px;}
.odd{background-color: #EAF2F5;}
.total{font-weight:bold;}
.memo{color: #FF0000;}
.end{background: none repeat scroll 0 0 #EAF2F5;font-weight:bold;text-align:right;}
-->
</style>
<style type="text/css">@import url({%$staticUrl%}/script/calendar/jquery.datepick.css);</style>
</head>
<body>
<div style="height:1500px; font-size:12px;">
	<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
	<script src="{%$staticUrl%}/js/utils.js?v=1.0" type="text/javascript"></script>
	<script src="{%$staticUrl%}/script/calendar/jquery.datepick.js?v=20110107" type="text/javascript"></script>
	<script src="{%$staticUrl%}/ofc/js/swfobject.js" type="text/javascript"></script>
	<div>
		<div id="searchTab" class="div7">
			<label style="padding-left: 15px;">统计开始日期：<input type="text" value="{%$startday%}" class="DatePicker" name="startday" id="startday"></label>
			<label style="padding-left: 15px;">统计结束日期：<input type="text" value="{%$endday%}" class="DatePicker" name="endday" id="endday"></label>
			<input type="button" name="submit" id="submit" onclick="javascript:getContent();" value="查看" />
		</div>
		<div id="div_chart" class="div1">
			<div id="main_chart"></div>
		</div>
	</div>
	<div id="data_area" style="margin:10px;"></div>
	<div style="display: none;"></div>

<div style="width:95%; height:1px; display: none;" class="layer_global" id="monterDiv">
	<div class="layer_global_main">
		<div class="layer_global_title"><h3 id="monter"></h3><button title="关闭" id="closeQuery" onclick="closeQuery();"><span class="none">╳</span></button></div>
		<div class="layer_global_cont">
			<div id="monterinfo"></div>
		</div>
	</div>
</div>
	<script type="text/javascript">
		var chart_data = '{%$chart%}';
		var editId = 0;
		var swfReady = false;
		
		function findSWF(movieName)
		{
		  if (navigator.appName.indexOf("Microsoft")!= -1) {
		    return window[movieName];
		  } else {
		    return document[movieName];
		  }
		}
		
		function ofc_ready()
		{
			swfReady = true;
		}
		
		function open_flash_chart_data()
		{
		    return chart_data;
		}
		
		function showChart()
		{
		  var tmp = findSWF('main_chart');
		  if (tmp) {
		  	tmp.load(chart_data);
		  }
		}

		var params = { allowScriptAccess: "always", menu:"false", wmode: "opaque", allowFullScreen: "false", bgcolor: "#ffffff", align: "middle", quality: "high"};
		//swfobject.embedSWF("{%$staticUrl%}/ofc/open-flash-chart.swf", "main_chart", "100%", "250", "9.0.0", null, null, params);
	</script>

</div>
<script type="text/javascript">

$.ajaxSetup({cache:false});

function formateDate(day)
{
	return day.substr(0,4) + '-' + day.substr(4,2) + '-' + day.substr(6,2);
}

function getContent()
{
	var startday = $("#startday").val();
	var endday = $("#endday").val();
	var dt = {startday:startday, endday:endday};
	$.get('/statapi/fightmain?platform={%$platform%}', dt, function(data) {
		if (data.errno == 0) {
			var html = '<table><tr><th rowspan="3">日期</th><th rowspan="3" style="border-right: 2px solid #CD00CD;">副本</th><th rowspan="2" colspan="2" style="border-right: 2px solid #CD00CD;">副本进入</th><th colspan="6" style="border-right: 2px solid #CD00CD;">打怪</th><th colspan="4">材料</th></tr>';
			html +='<tr><th colspan="3" style="border-right: 2px solid #CD00CD;">怪物</th><th colspan="3" style="border-right: 2px solid #CD00CD;">boss</th><th colspan="2" style="border-right: 2px solid #CD00CD;">打怪获得材料</th><th colspan="3">采集获得材料</th></tr>';
			html +='<tr><th>次数</th><th style="border-right: 2px solid #CD00CD;">人数</th><th>总数</th><th>人数</th><th style="border-right: 2px solid #CD00CD;">win</th><th>总数</th><th>人数</th><th style="border-right: 2px solid #CD00CD;">Win</th><th>总数</th><th style="border-right: 2px solid #CD00CD;">人数</th><th>总数</th><th>人数</th></tr>';

			var content = data.data;
			if (content) {
				var num = 0;
				for(var i in content) {
					num++;
	    			html += '<tr';
	    			if (i%2 == 0) {
	    				html += ' class="odd"';
	    			}
	    			html += '><td>' + formateDate(content[i].date) + '</td>'
	    				  + '<td style="border-right: 2px solid #CD00CD;">' + content[i].map + '</td>'
	    				  + '<td>' + content[i].copy + '</td>'
	    				  + '<td style="border-right: 2px solid #CD00CD;">' + content[i].copypnum + '</td>'
	    				  + '<td><a href="javascript:void(0)" onclick="showmonter('+content[i].map+',1,'+content[i].date+')">' + content[i].monster + '</td>'
	    				  + '<td>' + content[i].monspnum + '</td>'
	    				  + '<td style="border-right: 2px solid #CD00CD;">' + content[i].monwin + '</td>'
	    				  + '<td><a href="javascript:void(0)" onclick="showmonter('+content[i].map+',2,'+content[i].date+')">' + content[i].boss + '</td>'
	    				  + '<td>' + content[i].bosspnum + '</td>'
	    				  + '<td style="border-right: 2px solid #CD00CD;">' + content[i].bosswin + '</td>'
	    				  + '<td><a href="javascript:void(0)" onclick="showmater('+content[i].map+',1,'+content[i].date+')">' + content[i].mm + '</td>'
	    				  + '<td style="border-right: 2px solid #CD00CD;">' + content[i].mmp + '</td>'
	    				  + '<td><a href="javascript:void(0)" onclick="showmater('+content[i].map+',2,'+content[i].date+')">' + content[i].cm + '</td>'
	    				  + '<td>' + content[i].cmp + '</td>'
	    				  + '</tr>';
				}
			}

			html += '</table>';
			$('#data_area').html(html);
			
			var chartData = data.chart;
			if (chartData) {
				chart_data = chartData;
				showChart();
			}
		} else {
			$('#data_area').html('获取数据失败');
		}
	}, "json");
}
getContent();
function showmonter(map,type,date)
{
	var dt = {map:map,type:type,date:date};
	if(type == 1){
		var w = '怪物';
	}else{
		var w = 'boss';
		}
	title = '副本'+map+w+'分布';
	$.get('/statapi/monter?platform={%$platform%}', dt, function(data) {
	if (data.errno == 0) {
		var html = '<table><tr><th>日期</th><th>副本</th><th>怪物id</th><th>杀怪总数</th><th>人数</th><th>win</th></tr>';
		var content = data.data;
		if (content) {
			var num = 0;
			for(var i in content) {
				num++;
    			html += '<tr';
    			if (i%2 == 0) {
    				html += ' class="odd"';
    			}
    			html += '><td>' + formateDate(content[i].date) + '</td>'
    				  + '<td>' + content[i].map + '</td>'
    				  + '<td>' + content[i].cid + '</td>'
    				  + '<td>' + content[i].totalNum + '</td>'
    				  + '<td>' + content[i].pNum + '</td>'
    				  + '<td>' + content[i].win + '</td>'
    				  + '</tr>';
			}
		}

		html += '</table>';
		$('#monterDiv').css({left: 0, top: 210});
		$('#monter').html(title);
		$('#monterinfo').html(html);
		$('#monterDiv').show();
		
		var chartData = data.chart;
		if (chartData) {
			chart_data = chartData;
			showChart();
		}
	} else {
		$('#monterinfo').html('获取数据失败');
	}
}, "json");
	
}
function showmater(map,type,date)
{
	var dt = {map:map,type:type,date:date};
	if(type == 1){
		var w = '打怪';
	}else{
		var w = '采集';
		}
	title = '副本'+map+w+'材料分布';
	$.get('/statapi/mater?platform={%$platform%}', dt, function(data) {
	if (data.errno == 0) {
		var html = '<table><tr><th>日期</th><th>副本</th><th>材料id</th><th>材料总数</th><th>人数</th></tr>';
		var content = data.data;
		if (content) {
			var num = 0;
			for(var i in content) {
				num++;
    			html += '<tr';
    			if (i%2 == 0) {
    				html += ' class="odd"';
    			}
    			html += '><td>' + formateDate(content[i].date) + '</td>'
    				  + '<td>' + content[i].map + '</td>'
    				  + '<td>' + content[i].cid + '</td>'
    				  + '<td>' + content[i].totalNum + '</td>'
    				  + '<td>' + content[i].pNum + '</td>'
    				  + '</tr>';
			}
		}
		html += '</table>';
		$('#monterDiv').css({left: 0, top: 210});
		$('#monter').html(title);
		$('#monterinfo').html(html);
		$('#monterDiv').show();
		
		var chartData = data.chart;
		if (chartData) {
			chart_data = chartData;
			showChart();
		}
	} else {
		$('#monterinfo').html('获取数据失败');
	}
}, "json");
	
}
function closeQuery()
{
	$('#monterDiv').hide();
}
</script>
</body>
</html>
