<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>七天未登录用户-基础信息</title>
<link media="screen" type="text/css" rel="stylesheet" href="{%$staticUrl%}/a/gb_app.css">
<link type="text/css" rel="stylesheet" href="{%$staticUrl%}/style/itil.css">
<style type="text/css">
<!--
html{overflow:scroll!important;}

body,td,th {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #333333;
}

a img,:link img,:visited img {
	border: 0 none;
}

table{font-size:12px;border-collapse: collapse;border-spacing: 0;empty-cells: show;width: 100%;}
th, td {border: 1px solid #B1CBE2;}
th{background-color: #D5E7F3;padding:5px 5px;}
td{padding:2px 5px;}
.odd{background-color: #EAF2F5;}
.total{font-weight:bold;}
.memo{color: #FF0000;}
.end{background: none repeat scroll 0 0 #EAF2F5;font-weight:bold;text-align:right;}
-->
</style>
<style type="text/css">@import url({%$staticUrl%}/script/calendar/jquery.datepick.css);</style>
</head>
<body>
<div style="height:1500px; font-size:12px;">
	<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
	<script src="{%$staticUrl%}/js/utils.js?v=1.0" type="text/javascript"></script>
	<script src="{%$staticUrl%}/script/calendar/jquery.datepick.js?v=20110107" type="text/javascript"></script>
	<script src="{%$staticUrl%}/ofc/js/swfobject.js" type="text/javascript"></script>
	<div>
		<div id="searchTab" class="div7">
			<label style="padding-left: 15px;">统计开始日期：<input type="text" value="{%$startday%}" class="DatePicker" name="startday" id="startday"></label>
			<label style="padding-left: 15px;">统计结束日期：<input type="text" value="{%$endday%}" class="DatePicker" name="endday" id="endday"></label>
			<input type="button" name="submit" id="submit" onclick="javascript:getContent();" value="查看" />
		</div>
	</div>
	<div id="data_area" style="margin:10px;"></div>
	<script type="text/javascript">
		var chart_data = '{%$chart%}';
		var editId = 0;
		var swfReady = false;
		
		function findSWF(movieName)
		{
		  if (navigator.appName.indexOf("Microsoft")!= -1) {
		    return window[movieName];
		  } else {
		    return document[movieName];
		  }
		}
		
		function ofc_ready()
		{
			swfReady = true;
		}
		
		function open_flash_chart_data()
		{
		    return chart_data;
		}
		
		function showChart()
		{
		  var tmp = findSWF('main_chart');
		  if (tmp) {
		  	tmp.load(chart_data);
		  }
		}

		var params = { allowScriptAccess: "always", menu:"false", wmode: "opaque", allowFullScreen: "false", bgcolor: "#ffffff", align: "middle", quality: "high"};
		swfobject.embedSWF("{%$staticUrl%}/ofc/open-flash-chart.swf", "main_chart", "100%", "250", "9.0.0", null, null, params);
	</script>

</div>
<script type="text/javascript">

$.ajaxSetup({cache:false});

function editMemo(id)
{
	var txtMemo = $('#txt_memo_' + id);
	var lblMemo = $('#memo_' + id);
	var editMemo = $('#edit_memo_' + id);
	if (txtMemo) {
		var val = lblMemo.text();
		txtMemo.val(val);
		txtMemo.show();
		txtMemo.focus();
		lblMemo.hide();
		editMemo.hide();
	}
}

function saveMemo(id, d)
{
	var txtMemo = $('#txt_memo_' + id);
	var lblMemo = $('#memo_' + id);
	var editMemo = $('#edit_memo_' + id);
	if (txtMemo) {
		var val = txtMemo.val();
		var oldVal = lblMemo.text();
		if (val != oldVal) {
			lblMemo.text(val);
			$.post('/statapi/editmemo?platform={%$platform%}', {day:d, memo:val});
		}
		txtMemo.hide();
		editMemo.show();
		lblMemo.show();
	}
}

function formateDate(day)
{
	return day.substr(0,4) + '-' + day.substr(4,2) + '-' + day.substr(6,2);
}

function getContent()
{
	var startday = $("#startday").val();
	var endday = $("#endday").val();
	var dt = {startday:startday, endday:endday};

	$.get('/statapi/lossuserinfo?platform={%$platform%}', dt, function(data) {
		if (data.errno == 0) {
			var html = '<table><tr><th>日期</th><th>7天未登录用户数</th><th>平均拥有木头数</th><th>平均拥有石头数</th></tr>';

			var content = data.data;
			if (content) {
				for(var i in content) {
	    			html += '<tr';
	    			if (i%2 == 0) {
	    				html += ' class="odd"';
	    			}
	    			html += '><td>' + formateDate(content[i].log_time) + '</td>'
	    				  + '<td>' + content[i].user_count + '</td>'
	    				  + '<td>' + content[i].avg_wood + '</td>'
	    				  + '<td>' + content[i].avg_stone + '</td>'
	    				  + '</tr>';

				}
			}
			
			html += '<tr><th>日期</th><th>7天未登录用户数</th><th>平均拥有木头数</th><th>平均拥有石头数</th></tr>';

			html += '</table>';
			$('#data_area').html(html);
			
			var chartData = data.chart;
			if (chartData) {
				chart_data = chartData;
				showChart();
			}
		} else {
			$('#data_area').html('获取数据失败');
		}
	}, "json");
}

getContent();

</script>
</body>
</html>
