<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>快乐岛主</title>
<link media="screen" type="text/css" rel="stylesheet" href="{%$staticUrl%}/a/gb_app.css">
<link type="text/css" rel="stylesheet" href="{%$staticUrl%}/style/itil.css">
<style type="text/css">
<!--
html{overflow:scroll!important;}

body,td,th {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #333333;
}

a img,:link img,:visited img {
	border: 0 none;
}

table{font-size:12px;border-collapse: collapse;border-spacing: 0;empty-cells: show;width: 100%;}
th, td {border: 1px solid #B1CBE2;}
th{background-color: #D5E7F3;padding:5px 5px;}
td{padding:2px 5px;}
.odd{background-color: #EAF2F5;}
.total{font-weight:bold;}
.memo{color: #FF0000;}
.end{background: none repeat scroll 0 0 #EAF2F5;font-weight:bold;text-align:right;}
.targetok{color:#FF0000;font-weight:bold;}
-->
</style>
<style type="text/css">@import url({%$staticUrl%}/script/calendar/jquery.datepick.css);</style>
</head>
<body>
<div style="height:1500px; font-size:12px;">
	<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
	<script src="{%$staticUrl%}/js/utils.js?v=1.0" type="text/javascript"></script>
	<script src="{%$staticUrl%}/script/calendar/jquery.datepick.js?v=20110107" type="text/javascript"></script>
	<script src="{%$staticUrl%}/ofc/js/swfobject.js" type="text/javascript"></script>
	<div>
		<div id="searchTab" class="div7">
			<label style="padding-left: 15px;">统计开始日期：<input type="text" value="{%$startday%}" class="DatePicker" name="startday" id="startday"></label>
			<label style="padding-left: 15px;">统计结束日期：<input type="text" value="{%$endday%}" class="DatePicker" name="endday" id="endday"></label>
			<input type="button" name="submit" id="submit" onclick="javascript:getContent();" value="查看" />
		</div>
		<div id="div_chart" class="div1">
			<div id="main_chart"></div>
		</div>
	</div>
	<div id="data_area" style="margin:10px;"></div>
	<script type="text/javascript">
		var chart_data = '{%$chart%}';
		var editId = 0;
		var swfReady = false;
		
		function findSWF(movieName)
		{
		  if (navigator.appName.indexOf("Microsoft")!= -1) {
		    return window[movieName];
		  } else {
		    return document[movieName];
		  }
		}
		
		function ofc_ready()
		{
			swfReady = true;
		}
		
		function open_flash_chart_data()
		{
		    return chart_data;
		}
		
		function showChart()
		{
		  var tmp = findSWF('main_chart');
		  if (tmp) {
		  	tmp.load(chart_data);
		  }
		}

		var params = { allowScriptAccess: "always", menu:"false", wmode: "opaque", allowFullScreen: "false", bgcolor: "#ffffff", align: "middle", quality: "high"};
		swfobject.embedSWF("{%$staticUrl%}/ofc/open-flash-chart.swf", "main_chart", "100%", "300", "9.0.0", null, null, params);
	</script>

</div>
<script type="text/javascript">

$.ajaxSetup({cache:false});

function editMemo(id)
{
	var txtMemo = $('#txt_memo_' + id);
	var lblMemo = $('#memo_' + id);
	var editMemo = $('#edit_memo_' + id);
	if (txtMemo) {
		var val = lblMemo.text();
		txtMemo.val(val);
		txtMemo.show();
		txtMemo.focus();
		lblMemo.hide();
		editMemo.hide();
	}
}

function saveMemo(id, d)
{
	var txtMemo = $('#txt_memo_' + id);
	var lblMemo = $('#memo_' + id);
	var editMemo = $('#edit_memo_' + id);
	if (txtMemo) {
		var val = txtMemo.val();
		var oldVal = lblMemo.text();
		if (val != oldVal) {
			lblMemo.text(val);
			$.post('/statapi/editmemo?platform={%$platform%}', {day:d, memo:val});
		}
		txtMemo.hide();
		editMemo.show();
		lblMemo.show();
	}
}

function formateDate(day)
{
	return day.substr(0,4) + '-' + day.substr(4,2) + '-' + day.substr(6,2);
}

function getContent()
{
	var startday = $("#startday").val();
	var endday = $("#endday").val();
	var dt = {startday:startday, endday:endday};
	$.get('/statapi/main?platform={%$platform%}', dt, function(data) {
		if (data.errno == 0) {
			var html = '<table><tr><th>日期</th><th>总用户数</th><th>新增用户</th><th>活跃用户</th><th>活跃率</th>'
					 + '<th>当日消费</th><th>当日消费次数</th><th>消费人数</th><th>消费率</th><th>ACPU值</th><th>DACPU值</th><th width="120">备注</th></tr>';

			var content = data.data;
			if (content) {
				var activeRate = 0;
				var payRate = 0;
				var arpu = 0;
				var num = 0;
				var t_add_user = 0, t_active = 0, t_pay_total_amount = 0, t_arpu = 0;
				var a_add_user = 0, a_active = 0, a_pay_total_amount = 0, a_arpu = 0;
				var target = 0;
				var dacpu = 0;
				for(var i in content) {
					num++;
					t_add_user += parseInt(content[i].add_user);
					t_active += parseInt(content[i].active);
					t_pay_total_amount += parseInt(content[i].pay_total_amount);
					if (parseInt(content[i].active) == 0 || parseInt(content[i].total_count) == 0) {
						activeRate = 0;
					} else {
						activeRate = Math.round(parseInt(content[i].active)*10000.0/parseInt(content[i].total_count))/100 + '%';
					}
					if (parseInt(content[i].pay_user_count) == 0 || parseInt(content[i].active) == 0) {
						payRate = 0;
					} else {
						payRate = Math.round(parseInt(content[i].pay_user_count)*10000.0/parseInt(content[i].active))/100 + '%';
					}
					if (parseInt(content[i].pay_user_count) == 0) {
						arpu = 0;
					} else {
						arpu = Math.round(parseInt(content[i].pay_total_amount)*100.0/parseInt(content[i].pay_user_count))/100;
					}

					if (parseInt(content[i].active) == 0) {
						dacpu = 0;
					} else {
						dacpu = Math.round(parseInt(content[i].pay_total_amount)*10000.0/parseInt(content[i].active))/10000;
					}
					
					t_arpu += arpu;
					target = parseInt(content[i].active) + parseInt(content[i].pay_total_amount)*10;
	    			html += '<tr';
	    			if (i%2 == 0) {
	    				html += ' class="odd"';
	    			}
	    			html += '><td>' + formateDate(content[i].log_time) + '</td>'
	    				  + '<td>' + content[i].total_count + '</td>'
	    				  + '<td>' + content[i].add_user  + '</td>'
	    				  + '<td>' + content[i].active + '</td>'
	    				  + '<td>' + activeRate + '</td>'
	    				  + '<td>' + content[i].pay_total_amount + '</td>'
	    				  + '<td>' + content[i].pay_user_count + '</td>'
	    				  + '<td>' + content[i].pay_count + '</td>'
	    				  + '<td>' + payRate + '</td>'
	    				  + '<td>' + arpu + '</td>'
	    				  + '<td>' + dacpu + '</td>'
	    				  + '<td id="td_memo_' + i + '" align="center"><input id="txt_memo_' + i + '" style="display:none;" onblur="saveMemo(\'' + i + '\', \'' + content[i].log_time + '\');" /><lable id="edit_memo_' + i + '"><span class="memo" id="memo_' + i + '">' + content[i].memo + '</span>&nbsp;&nbsp;<a href="javascript:void(0);" onclick="editMemo(\'' + i + '\')">编辑</a></lable></td>'
	    				  + '</tr>';
				}
				if (num > 0) {
					a_add_user = Math.round(t_add_user/num);
					a_active = Math.round(t_active/num);
					a_pay_total_amount = Math.round(t_pay_total_amount/num);
					a_arpu = Math.round(t_arpu*100/num)/100;
				}
				
				html += '<tr class="end"><td>合计</td><td></td><td>' + t_add_user + '</td><td></td><td></td><td>' + t_pay_total_amount + '</td><td></td><td></td><td></td><td></td><td></td><td></td></tr>'
					  + '<tr class="end"><td>平均</td><td></td><td>' + a_add_user + '</td><td>' + a_active + '</td><td></td><td>' + a_pay_total_amount + '</td><td></td><td></td><td>' + a_arpu + '</td><td></td><td></td><td></td></tr>';
			}

			html += '</table>';
			$('#data_area').html(html);
			
			var chartData = data.chart;
			if (chartData) {
				chart_data = chartData;
				showChart();
			}
		} else {
			$('#data_area').html('获取数据失败');
		}
	}, "json");
}

getContent();

</script>
</body>
</html>
