<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>收入概览统计</title>
<link media="screen" type="text/css" rel="stylesheet" href="{%$staticUrl%}/a/gb_app.css">
<link type="text/css" rel="stylesheet" href="{%$staticUrl%}/style/itil.css">
<style type="text/css">
<!--
html{overflow:scroll!important;}

body,td,th {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #333333;
}

a img,:link img,:visited img {
	border: 0 none;
}

table{font-size:12px;border-collapse: collapse;border-spacing: 0;empty-cells: show;width: 100%;}
th, td {border: 1px solid #B1CBE2;}
th{background-color: #D5E7F3;}
td{padding:2px;}
.odd{background-color: #EAF2F5;}
.total{font-weight:bold;}

-->
</style>
<style type="text/css">@import url({%$staticUrl%}/script/calendar/jquery.datepick.css);</style>
</head>
<body>
<div style="height:1500px; font-size:12px;">
	<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
	<script src="{%$staticUrl%}/js/utils.js?v=1.0" type="text/javascript"></script>
	<script src="{%$staticUrl%}/script/calendar/jquery.datepick.js?v=20110107" type="text/javascript"></script>
	<div id="searchTab" class="div7">
		<label style="padding-left: 15px;">统计开始日期:<input type="text" value="{%$startday%}" class="DatePicker" name="startday" id="startday"></label>
		<label style="padding-left: 15px;">统计结束日期:<input type="text" value="{%$endday%}" class="DatePicker" name="endday" id="endday"></label>
		<input type="button" name="submit" id="submit" onclick="javascript:getContent();" value="查看" />
	</div>
	<div id="data_area" style="margin:10px;"></div>


</div>
<script type="text/javascript">

$.ajaxSetup({cache:false});

function getContent()
{
	var startday = $("#startday").val();
	var endday = $("#endday").val();
	var dt = {startday:startday, endday:endday};
	$.get('/statapi/pay2?platform={%$platform%}', dt, function(data) {
		if (data.errno == 0) {
			var html = '<table><tr><th rowspan="2" style="width:100px;">日期</th><th rowspan="2" style="width:100px;">实际收入(元)</th><th colspan="4">校友</th><th colspan="4">Qzone平台</th></tr>'
					 + '<tr><th>岛钻币(个)</th><th>损失岛钻币(个)</th><th>消费人数</th><th>消费次数</th>'
					 + '<th>岛钻币(个)</th><th>损失岛钻币(个)</th><th>消费人数</th><th>消费次数</th></tr>';

			var content = data.data;
			if (content) {
				var tl = [0,0,0,0,0,0,0,0,0];
				var tm,d,h,total;
				for(var i in content) {
					tm = new Date(content[i].day_time * 1000);
					d = tm.format('Y-m-d');
					total = parseInt(content[i].payment_amount_0) + parseInt(content[i].payment_amount_1) - parseInt(content[i].payment_lose_amount_0) - parseInt(content[i].payment_lose_amount_1);
					tl[0] += total;
					tl[1] += parseInt(content[i].payment_amount_0);
					tl[2] += parseInt(content[i].payment_lose_amount_0);
					tl[3] += parseInt(content[i].payment_user_count_0);
					tl[4] += parseInt(content[i].payment_all_count_0);
					tl[5] += parseInt(content[i].payment_amount_1);
					tl[6] += parseInt(content[i].payment_lose_amount_1);
					tl[7] += parseInt(content[i].payment_user_count_1);
					tl[8] += parseInt(content[i].payment_all_count_1);
					
	    			html += '<tr><td>' + d + '</td>'
	    				  + '<td>' + (total/10) + '</td>'
	    				  + '<td>' + content[i].payment_amount_0 + '</td>'
	    				  + '<td>' + content[i].payment_lose_amount_0 + '</td>'
	    				  + '<td>' + content[i].payment_user_count_0 + '</td>'
	    				  + '<td>' + content[i].payment_all_count_0 + '</td>'
	    				  + '<td>' + content[i].payment_amount_1 + '</td>'
	    				  + '<td>' + content[i].payment_lose_amount_1 + '</td>'
	    				  + '<td>' + content[i].payment_user_count_1 + '</td>'
	    				  + '<td>' + content[i].payment_all_count_1 + '</td>'
	    				  + '</tr>';
				}
				
	    		html += '<tr class="total"><td>合计</td>'
	    				  + '<td>' + (tl[0]/10) + '</td>'
	    				  + '<td>' + tl[1] + '</td>'
	    				  + '<td>' + tl[2] + '</td>'
	    				  + '<td>' + tl[3] + '</td>'
	    				  + '<td>' + tl[4] + '</td>'
	    				  + '<td>' + tl[5] + '</td>'
	    				  + '<td>' + tl[6] + '</td>'
	    				  + '<td>' + tl[7] + '</td>'
	    				  + '<td>' + tl[8] + '</td>'
	    				  + '</tr>';
			}

			html += '</table>';
			$('#data_area').html(html);
		} else {
			$('#data_area').html('获取数据失败');
		}
	}, "json");
}

getContent();

</script>
</body>
</html>
