<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>充值点击统计</title>
<link media="screen" type="text/css" rel="stylesheet" href="{%$staticUrl%}/a/gb_app.css">
<link type="text/css" rel="stylesheet" href="{%$staticUrl%}/style/itil.css">
<style type="text/css">
<!--
html{overflow:scroll!important;}

body,td,th {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #333333;
}

a img,:link img,:visited img {
	border: 0 none;
}

table{font-size:12px;border-collapse: collapse;border-spacing: 0;empty-cells: show;width: 100%;}
th, td {border: 1px solid #B1CBE2;}
th{background-color: #D5E7F3;}
td{padding:2px;}
.odd{background-color: #EAF2F5;}
.total{font-weight:bold;}

-->
</style>
<style type="text/css">@import url({%$staticUrl%}/script/calendar/jquery.datepick.css);</style>
</head>
<body>
<div style="height:1500px; font-size:12px;">
	<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
	<script src="{%$staticUrl%}/js/utils.js?v=1.0" type="text/javascript"></script>
	<script src="{%$staticUrl%}/script/calendar/jquery.datepick.js?v=20110107" type="text/javascript"></script>
	<div id="searchTab" class="div7">
		<label style="padding-left: 15px;">统计开始日期:<input type="text" value="{%$startday%}" class="DatePicker" name="startday" id="startday"></label>
		<label style="padding-left: 15px;">统计结束日期:<input type="text" value="{%$endday%}" class="DatePicker" name="endday" id="endday"></label>
		<input type="button" name="submit" id="submit" onclick="javascript:getContent();" value="查看" />
	</div>
	<div id="data_area" style="margin:10px;"></div>
</div>
<script type="text/javascript">

$.ajaxSetup({cache:false});

function getContent()
{
	var startday = $("#startday").val();
	var endday = $("#endday").val();
	var dt = {startday:startday, endday:endday};
	$.get('/statapi/payclick?platform={%$platform%}', dt, function(data) {
		if (data.errno == 0) {
			var html = '<table><tr><th>日期</th><th>Menu充值按钮</th><th>进入充值页面</th><th>关闭页面</th><th>按钮(12)</th><th>按钮(24)</th><th>按钮(40)</th><th>按钮(120)</th><th>按钮(280)</th><th>总计</th></tr>';
			var content = data.data;
			if (content) {
				for(var i in content) {
					var create_time = content[i].create_time;
					var type1 = parseInt(content[i].type1);
					var type2 = parseInt(content[i].type2);
					var type3 = parseInt(content[i].type3);
					var type4 = parseInt(content[i].type4);
					var type5 = parseInt(content[i].type5);
					var type6 = parseInt(content[i].type6);
					var type7 = parseInt(content[i].type7);
					var type8 = parseInt(content[i].type8);

					var allTimes= type1+type2+type3+type4+type5+type6+type7+type8;
					
					var prop1 = (type1/allTimes*100).toFixed(2);
					var prop2 = (type2/allTimes*100).toFixed(2);
					var prop3 = (type3/allTimes*100).toFixed(2);
					var prop4 = (type4/allTimes*100).toFixed(2);
					var prop5 = (type5/allTimes*100).toFixed(2);
					var prop6 = (type6/allTimes*100).toFixed(2);
					var prop7 = (type7/allTimes*100).toFixed(2);
					var prop8 = (type8/allTimes*100).toFixed(2);

					
					html += '<tr><td align=center>'+create_time+'</td>'
							+ '<td align=center>' + type1 + '('+ prop1 +'%)</td>'
							+ '<td align=center>' + type2 + '('+ prop2 +'%)</td>'
							+ '<td align=center>' + type3 + '('+ prop3 +'%)</td>'
							+ '<td align=center>' + type4 + '('+ prop4 +'%)</td>'
							+ '<td align=center>' + type5 + '('+ prop5 +'%)</td>'
							+ '<td align=center>' + type6 + '('+ prop6 +'%)</td>'
							+ '<td align=center>' + type7 + '('+ prop7 +'%)</td>'
							+ '<td align=center>' + type8 + '('+ prop8 +'%)</td>'
							+ '<td align=center>' + allTimes + '</td>';
						
				}
			}
			html += '</table>';
			$('#data_area').html(html);
		} else {
			$('#data_area').html('获取数据失败');
		}
	}, "json");
}
</script>
</body>
</html>
