<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>发出岛钻</title>
<link media="screen" type="text/css" rel="stylesheet" href="{%$staticUrl%}/a/gb_app.css">
<link type="text/css" rel="stylesheet" href="{%$staticUrl%}/style/itil.css">
<style type="text/css">
<!--
html{overflow:scroll!important;}

body,td,th {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #333333;
}

a img,:link img,:visited img {
	border: 0 none;
}

table{font-size:12px;border-collapse: collapse;border-spacing: 0;empty-cells: show;width: 100%;}
th, td {border: 1px solid #B1CBE2;}
th{background-color: #D5E7F3;}
td{padding:2px;}
.odd{background-color: #EAF2F5;}
.total{font-weight:bold;}

-->
</style>
<style type="text/css">@import url({%$staticUrl%}/script/calendar/jquery.datepick.css);</style>
</head>
<body>
<div style="height:1500px; font-size:12px;">
	<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
	<script src="{%$staticUrl%}/js/utils.js?v=1.0" type="text/javascript"></script>
	<script src="{%$staticUrl%}/script/calendar/jquery.datepick.js?v=20110107" type="text/javascript"></script>
	<div id="searchTab" class="div7">
		<label style="padding-left: 15px;">统计开始日期:<input type="text" value="{%$startday%}" class="DatePicker" name="startday" id="startday"></label>
		<label style="padding-left: 15px;">统计结束日期:<input type="text" value="{%$endday%}" class="DatePicker" name="endday" id="endday"></label>
		<input type="button" name="submit" id="submit" onclick="javascript:getContent();" value="查看" />
	</div>
	<div id="data_area" style="margin:10px;"></div>
</div>
<script type="text/javascript">

$.ajaxSetup({cache:false});

function getContent()
{
	var startday = $("#startday").val();
	var endday = $("#endday").val();
	var dt = {startday:startday, endday:endday};
	$.get('/statapi/sendgold?platform={%$platform%}', dt, function(data) {
		if (data.errno == 0) {
			var html = '<table><tr><th>日期</th><th>充值</th><th>一元店</th><th>限时抢购</th><th>新手引导</th><th>升级奖励</th><th>阶段礼包</th><th>时间礼包</th><th>连续登入</th><th>邀请</th><th>海盗宝箱</th><th>大转盘</th><th>捕鱼</th><th>其他</th><th>总计</th></tr>';
			var content = data.data;
			if (content) {
				for(var i in content) {
					var create_time = content[i].create_time;
					var type0 = parseInt(content[i].type0);
					var type1 = parseInt(content[i].type1);
					var type2 = parseInt(content[i].type2);
					var type3 = parseInt(content[i].type3);
					var type4 = parseInt(content[i].type4);
					var type5 = parseInt(content[i].type5);
					var type6 = parseInt(content[i].type6);
					var type7 = parseInt(content[i].type7);
					var type8 = parseInt(content[i].type8);
					var type9 = parseInt(content[i].type9);
					var type10 = parseInt(content[i].type10);
					var type11 = parseInt(content[i].type11);
					var type12 = parseInt(content[i].type12);

					var allGold = type0+type1+type2+type3+type4+type5+type6+type7+type8+type9+type10+type11+type12;

					var prop0 = (type0/allGold*100).toFixed(2);
					var prop1 = (type1/allGold*100).toFixed(2);
					var prop2 = (type2/allGold*100).toFixed(2);
					var prop3 = (type3/allGold*100).toFixed(2);
					var prop4 = (type4/allGold*100).toFixed(2);
					var prop5 = (type5/allGold*100).toFixed(2);
					var prop6 = (type6/allGold*100).toFixed(2);
					var prop7 = (type7/allGold*100).toFixed(2);
					var prop8 = (type8/allGold*100).toFixed(2);
					var prop9 = (type9/allGold*100).toFixed(2);
					var prop10 = (type10/allGold*100).toFixed(2);
					var prop11 = (type11/allGold*100).toFixed(2);
					var prop12 = (type12/allGold*100).toFixed(2);
					
					html += '<tr><td align=center>'+create_time+'</td>'
							+ '<td align=center>' + type1 + '('+ prop1 +'%)</td>'
							+ '<td align=center>' + type2 + '('+ prop2 +'%)</td>'
							+ '<td align=center>' + type3 + '('+ prop3 +'%)</td>'
							+ '<td align=center>' + type4 + '('+ prop4 +'%)</td>'
							+ '<td align=center>' + type5 + '('+ prop5 +'%)</td>'
							+ '<td align=center>' + type6 + '('+ prop6 +'%)</td>'
							+ '<td align=center>' + type7 + '('+ prop7 +'%)</td>'
							+ '<td align=center>' + type8 + '('+ prop8 +'%)</td>'
							+ '<td align=center>' + type9 + '('+ prop9 +'%)</td>'
							+ '<td align=center>' + type10 + '('+ prop10 +'%)</td>'
							+ '<td align=center>' + type11 + '('+ prop11 +'%)</td>'
							+ '<td align=center>' + type12 + '('+ prop12 +'%)</td>'
							+ '<td align=center>' + type0 + '('+ prop0 +'%)</td>'
							+ '<td align=center>' + allGold + '</td>';
						
				}
			}
			html += '</table>';
			$('#data_area').html(html);
		} else {
			$('#data_area').html('获取数据失败');
		}
	}, "json");
}
</script>
</body>
</html>
