<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>建筑升级-等级分布</title>
<link media="screen" type="text/css" rel="stylesheet" href="{%$staticUrl%}/a/gb_app.css">
<link type="text/css" rel="stylesheet" href="{%$staticUrl%}/style/itil.css">
<style type="text/css">
<!--
html{overflow:scroll!important;}

body,td,th {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #333333;
}

a img,:link img,:visited img {
	border: 0 none;
}

table{font-size:12px;border-collapse: collapse;border-spacing: 0;empty-cells: show;width: 100%;}
th, td {border: 1px solid #B1CBE2;}
th{background-color: #D5E7F3;}
td{padding:2px;}
.odd{background-color: #EAF2F5;}
.total{font-weight:bold;}

-->
</style>
<style type="text/css">@import url({%$staticUrl%}/script/calendar/jquery.datepick.css);</style>
</head>
<body>
<div style="height:1500px; font-size:12px;">
	<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
	<script src="{%$staticUrl%}/js/utils.js?v=1.0" type="text/javascript"></script>
	<script src="{%$staticUrl%}/script/calendar/jquery.datepick.js?v=20110107" type="text/javascript"></script>
	<script src="{%$staticUrl%}/ofc/js/swfobject.js" type="text/javascript"></script>
	<div>
		<div id="searchTab" class="div7">
			<label style="padding-left: 15px;">统计开始日期：<input type="text" value="{%$startday%}" class="DatePicker" name="startday" id="startday"></label>
			<label style="padding-left: 15px;">统计结束日期：<input type="text" value="{%$endday%}" class="DatePicker" name="endday" id="endday"></label>
			<input type="button" name="submit" id="submit" onclick="javascript:getContent();" value="查看" />
		</div>
		<div id="div_chart" class="div1">
			<div id="main_chart"></div>
		</div>
	</div>
	<div id="data_area" style="margin:10px;"></div>

</div>
<script type="text/javascript">
$.ajaxSetup({cache:false});

function formateDate(day)
{
	return day.substr(0,4) + '-' + day.substr(4,2) + '-' + day.substr(6,2);
}
function getContent()
{
	var startday = $("#startday").val();
	var endday = $("#endday").val();
	var dt = {startday:startday, endday:endday};
	$.get('/statapi/upgrademain?platform={%$platform%}', dt, function(data) {
		if (data.errno == 0) {
			var html = '<table><tr><th rowspan="2" style="border-right: 2px solid #CD00CD;">日期</th><th colspan="3" style="border-right: 2px solid #CD00CD;">主角屋</th><th colspan="3" style="border-right: 2px solid #CD00CD;">酒馆1</th><th colspan="3" style="border-right: 2px solid #CD00CD;">酒馆2</th><th colspan="3" style="border-right: 2px solid #CD00CD;">酒馆3</th><th colspan="3" >铁匠铺</th></tr>';
			html += '<tr><th>次数</th><th>人数</th><th style="border-right: 2px solid #CD00CD;">花费</th><th>次数</th><th>人数</th><th style="border-right: 2px solid #CD00CD;">花费</th><th>次数</th><th>人数</th><th style="border-right: 2px solid #CD00CD;">花费</th><th>次数</th><th>人数</th><th style="border-right: 2px solid #CD00CD;">花费</th><th>次数</th><th>人数</th><th>花费</th></tr>';

			var content = data.data;
			if (content) {
				var num = 0;
				for(var i in content) {
					num++;
	    			html += '<tr';
	    			if (i%2 == 0) {
	    				html += ' class="odd"';
	    			}
	    			html += '><td style="border-right: 2px solid #CD00CD;">' + formateDate(content[i].date) + '</td>'
	    				  + '<td >' + content[i].home.total + '</td>'
	    				  + '<td>' + content[i].home.pnum + '</td>'
	    				  + '<td style="border-right: 2px solid #CD00CD;">' + content[i].home.sum + '</td>'
	    				  + '<td >' + content[i].tavern1.total + '</td>'
	    				  + '<td>' + content[i].tavern1.pnum + '</td>'
	    				  + '<td style="border-right: 2px solid #CD00CD;">' + content[i].tavern1.sum + '</td>'
	    				  + '<td >' + content[i].tavern2.total + '</td>'
	    				  + '<td>' + content[i].tavern2.pnum + '</td>'
	    				  + '<td style="border-right: 2px solid #CD00CD;">' + content[i].tavern2.sum + '</td>'
	    				  + '<td >' + content[i].tavern3.total + '</td>'
	    				  + '<td>' + content[i].tavern3.pnum + '</td>'
	    				  + '<td style="border-right: 2px solid #CD00CD;">' + content[i].tavern3.sum + '</td>'
	    				  + '<td >' + content[i].smithy.total + '</td>'
	    				  + '<td>' + content[i].smithy.pnum + '</td>'
	    				  + '<td >' + content[i].smithy.sum + '</td>'
	    				  + '</tr>';
				}
			}

			html += '</table>';
			$('#data_area').html(html);
			
			var chartData = data.chart;
			if (chartData) {
				chart_data = chartData;
				showChart();
			}
		} else {
			$('#data_area').html('获取数据失败');
		}
	}, "json");
}

getContent();

$("#stattime").change(function (){
	getContent();
});

function loadPre()
{
	var stattime = $("#stattime").val();
	var d = new Date(stattime.replace(/-/g, '/'));
	d.setDate(d.getDate()-1);
	$("#stattime").val(d.format('Y-m-d'));
	
	getContent();
}

function loadNext()
{
	var stattime = $("#stattime").val();
	var d = new Date(stattime.replace(/-/g, '/'));
	d.setDate(d.getDate()+1);
	$("#stattime").val(d.format('Y-m-d'));
	
	getContent();
}
</script>
</body>
</html>
