<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>建筑升级-等级分布</title>
<link media="screen" type="text/css" rel="stylesheet" href="{%$staticUrl%}/a/gb_app.css">
<link type="text/css" rel="stylesheet" href="{%$staticUrl%}/style/itil.css">
<style type="text/css">
<!--
html{overflow:scroll!important;}

body,td,th {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #333333;
}

a img,:link img,:visited img {
	border: 0 none;
}

table{font-size:12px;border-collapse: collapse;border-spacing: 0;empty-cells: show;width: 400px;}
th, td {border: 1px solid #B1CBE2;}
th{background-color: #D5E7F3;}
td{padding:2px;}
.odd{background-color: #EAF2F5;}
.total{font-weight:bold;}

-->
</style>
<style type="text/css">@import url({%$staticUrl%}/script/calendar/jquery.datepick.css);</style>
</head>
<body>
<div style="height:1500px; font-size:12px;">
	<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
	<script src="{%$staticUrl%}/js/utils.js?v=1.0" type="text/javascript"></script>
	<script src="{%$staticUrl%}/script/calendar/jquery.datepick.js?v=20110107" type="text/javascript"></script>
	<script src="{%$staticUrl%}/ofc/js/swfobject.js" type="text/javascript"></script>
	<div>
		<div  id="searchTab" class="div7">
			<label style="padding-left: 15px;">统计日期：<input type="text" value="{%$today%}" class="DatePicker" name="begtime" id="stattime"></label>
			<input type="button" name="btnPre" id="btnPre" onclick="javascript:loadPre();" value=" 前一天 " />
			<input type="button" name="btnNext" id="btnNext" onclick="javascript:loadNext();" value=" 后一天 " />
			<input type="hidden" name="type" id="upgarde" value="1" />
		</div>
		<span style="font-size:15px;font-weight:bold;">选择查询建筑:</span>
		<select id="slt_type" onchange="selectType(this.value)">
			<option value="-1">请选择建筑</option >&nbsp;&nbsp;
			<option value="1">主角屋</option>&nbsp;&nbsp;
			<option value="2">酒馆1</option>&nbsp;&nbsp;
			<option value="3">酒馆2</option>&nbsp;&nbsp;
			<option value="4">酒馆3</option>&nbsp;&nbsp;
			<option value="5">铁匠铺</option>&nbsp;&nbsp;
		</select>
		<div id="div_chart" class="div1">
			<div id="level_chart"></div>
		</div>
	</div>
	<div id="data_area" style="margin:10px;"></div>
	<script type="text/javascript">
		var chart_data = '{%$chart%}';
		var swfReady = false;
		
		function findSWF(movieName)
		{
		  if (navigator.appName.indexOf("Microsoft")!= -1) {
		    return window[movieName];
		  } else {
		    return document[movieName];
		  }
		}
		
		function ofc_ready()
		{
			swfReady = true;
		}
		
		function open_flash_chart_data()
		{
		    return chart_data;
		}
		
		function showChart()
		{
		  var tmp = swfobject.getObjectById('level_chart');
		  if (tmp) {
		  	tmp.load(chart_data);
		  }
		}
		
		var params = { allowScriptAccess: "always", menu:"false", wmode: "opaque", allowFullScreen: "false", bgcolor: "#ffffff", align: "middle", quality: "high"};
		swfobject.embedSWF("{%$staticUrl%}/ofc/open-flash-chart.swf", "level_chart", "100%", "300", "9.0.0", null, null, params);
	</script>

</div>
<script type="text/javascript">

$.ajaxSetup({cache:false});

function getContent()
{	
	type = $("#upgarde").val();
	day = $("#stattime").val();
	var dt = {day:day,type:type};
	$.get('/statapi/upgradelevel?platform={%$platform%}', dt, function(data) {
		if (data.errno == 0) {
			var content = data.data;
			var html = [];
			html.push('<table><tr><th>建筑等级</th><th>人数</th><th>比重(%)</th></tr>');
			var total = 0;
			var i;
			var count = 0, rate = 0, allCnt = 0;
			for(i in content) {
				total += parseInt(content[i].count);
			}
			for(i in content) {
				count = parseInt(content[i].count);
				allCnt += count;
				rate = Math.round((count*10000.0)/total)/100;
    			html.push('<tr');
    			if (i%2 ==0) {
    				html.push(' class="odd"');
    			}
    			html.push('><td>', content[i].level, '</td>',
    				  '<td>', content[i].count, '</td>',
    				  '<td>');
    			if (rate == 0) {
    				html.push('>');
    			}
    			html.push(rate, '</td>', '</tr>');
			}
			html.push('<tr><th>总数</th><th>', allCnt, '</th><th></th></tr>');
			html.push('</table><br/><br/>');
			$('#data_area').html(html.join(''));
			
			var chartData = data.chart;
			if (chartData) {
				chart_data = chartData;
				showChart();
			}
		} else {
			$('#data_area').html('获取数据失败');
		}
	}, "json");
}

getContent();

$("#stattime").change(function (){
	getContent();
});

function loadPre()
{
	var stattime = $("#stattime").val();
	var d = new Date(stattime.replace(/-/g, '/'));
	d.setDate(d.getDate()-1);
	$("#stattime").val(d.format('Y-m-d'));
	
	getContent();
}

function loadNext()
{
	var stattime = $("#stattime").val();
	var d = new Date(stattime.replace(/-/g, '/'));
	d.setDate(d.getDate()+1);
	$("#stattime").val(d.format('Y-m-d'));
	
	getContent();
}

function selectType(type)
{
	$("#upgarde").val(type);
	getContent();
}

</script>
</body>
</html>
