<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>用户等级分布 - 统计系统[内部] - 欢乐海岛</title>
<link media="screen" type="text/css" rel="stylesheet" href="http://imgcache.qq.com/qzonestyle/xiaoyou_app/css/gb_app.css">
<style type="text/css">
<!--
html{overflow:scroll!important;}

body,td,th {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #333333;
}

a img,:link img,:visited img {
	border: 0 none;
}

table{font-size:12px;border-collapse: collapse;border-spacing: 0;empty-cells: show;width: 100%;}
th, td {border: 1px solid #B1CBE2;}
th{background-color: #D5E7F3;}
td{padding:2px;}
.odd{background-color: #EAF2F5;}
.total{font-weight:bold;}

-->
</style>
<style type="text/css">@import url({%$staticUrl%}/script/calendar/jquery.datepick.css);</style>
</head>
<body>
<div style="height:1500px; font-size:12px;">
	<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
	<script src="{%$staticUrl%}/js/utils.js?v=1.0" type="text/javascript"></script>
	<script src="{%$staticUrl%}/script/calendar/jquery.datepick.js?v=20110107" type="text/javascript"></script>
	<div><label style="padding-left: 15px;">统计日期:
  	<input type="text" value="{%$today%}" class="DatePicker" name="begtime" id="stattime">
  	</label></div>
	<div id="data_area"></div>


</div>
<script type="text/javascript">

$.ajaxSetup({cache:false});

function getContent()
{
			var html = '<table><tr><th rowspan="3" style="width:100px;">等级</th><th colspan="6">数量</th></tr><tr><th colspan="3">全部</th><th colspan="3">活跃</th></tr><tr><th>总</th><th>男</th><th>女</th><th>总</th><th>男</th><th>女</th></tr>';
			for(var i=1;i<100;i++) {
				html += '<tr><td> ' + i + '</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>'; 
			}

			html += '</table>';
			$('#data_area').html(html);
}

getContent();

$("#stattime").change(function (){
	getContent();
});

</script>
</body>
</html>
