<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>快乐岛主</title>
<link media="screen" type="text/css" rel="stylesheet" href="{%$staticUrl%}/a/gb_app.css">
<style type="text/css">
<!--
html{overflow:scroll!important;}

body,td,th {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #333333;
}

a img,:link img,:visited img {
	border: 0 none;
}

#data_area {
	margin-top:20px;
}

table{font-size:12px;border-collapse: collapse;border-spacing: 0;empty-cells: show;width: 1100px;}
table caption {
	font-weight:bold; font-size: 16px; color:#FF0000;
}
th, td {border: 1px solid #B1CBE2;}
th{background-color: #D5E7F3;padding:5px 5px;}
td{padding:2px 5px;}
-->
</style>
</head>
<body>
<div style="height:1500px; font-size:12px;">
	<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
	<div>
	<table>
	<tr><th>名称</th><th>标识</th><th>类型</th></tr>
	{% if $servers %}
	{% foreach from=$servers item=data %}
	<tr><td>{%$data.name%}</td><td><a href="javascript:void(0);" onclick="getData('{%$data.sid%}', '{%$data.name%}.{%$data.area_name%}');">{%$data.name%}.{%$data.area_name%}</a></td><td>{%$data.type%}</td></tr>
	{% /foreach %}
	{% /if %}
	</table>
	</div>
	<div>
	</div>
	<div id="data_area"></div>
</div>
<script type="text/javascript">

$.ajaxSetup({cache:false});

function getData(sid, caption)
{
	var dt = {sid:sid};
	$.get('/monitorapi/serverinfo?platform={%$platform%}', dt, function(data) {
		if (data.errno == 0) {
			var html = '<table><caption>' + caption + '</caption>';
			var content = data.data;
			if (content) {
				for(var i in content) {
	    			html += '<tr><td colspan="2">' + content[i].key + '</td></tr>'
	    				  + '<tr><td><img src="' + content[i].value.day + '" /></td>'
	    				  + '<td><img src="' + content[i].value.week + '" /></td><tr>';
				}
			}

			html += '</table>';
			$('#data_area').html(html);
		} else {
			$('#data_area').html('获取数据失败');
		}
	}, "json");
}

</script>
</body>
</html>
