<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>快乐岛主</title>
<link media="screen" type="text/css" rel="stylesheet" href="{%$staticUrl%}/a/gb_app.css">
<style type="text/css">
<!--
html{overflow:scroll!important;}

body,td,th {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #333333;
}

a img,:link img,:visited img {
	border: 0 none;
}

#data_area {
	margin-top:20px;
}

table{font-size:12px;border-collapse: collapse;border-spacing: 0;empty-cells: show;width: 1100px;}
table caption {
	font-weight:bold; font-size: 16px; color:#FF0000;
}
th, td {border: 1px solid #B1CBE2;}
th{background-color: #D5E7F3;padding:5px 5px;}
td{padding:2px 5px;}
-->
</style>
</head>
<body>
<div style="height:1500px; font-size:12px;">
	<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
	<div>
	<table>
	<tr><th colspan="4">自动化更新</th></tr>
	<tr>
	   <td><a href="javascript:void(0);" onclick="updateApp('1', '1');">测服动态（PHP）</a></td>
	   <td><a href="javascript:void(0);" onclick="updateApp('1', '2');">测服静态（SWF）</a></td>
       <td><a href="javascript:void(0);" onclick="updateApp('2', '1');">正服动态（PHP）</a></td>
       <td><a href="javascript:void(0);" onclick="updateApp('2', '2');">正服静态（SWF）</a></td>
	</tr>
	<tr>
       <th colspan="4"><a href="javascript:void(0);" onclick="stopUpdateApi();">结束请求</a></th>
    </tr>
	</table>
	</div>
	<div>
	</div>
	<div id="data_area"></div>
</div>
<script type="text/javascript">
var API;
var updateCount = 1;
$.ajaxSetup({cache:false});

//appType:平台类型，1->测服，2->正服
//codeType:代码类型，1->PHP，2->SWF
function updateApp(appType, codeType)
{
    API = setInterval("updateAppResult("+appType+", "+codeType+")", 5000);
    var dt = {appType:appType, codeType:codeType};
    $.get('/monitorapi/updateapp?platform={%$platform%}', dt, function(data) {
        if (data.errno == 0) {
            var html = '<table><caption>' + data.content + '</caption></table>';
            html += '<table><caption>' + data.data.updateLastLine + '</caption></table>';
            html += '<table><caption>' + data.data.updateResult + '</caption></table>';
            $('#data_area').html(html);
            
        } else {
            $('#data_area').html('<table><caption>更新失败，请稍候再试</caption></table>');
        }
    }, "json");
}

function updateAppResult(appType, codeType) 
{
    var dt = {appType:appType, codeType:codeType};
    $.get('/monitorapi/updateappresult?platform={%$platform%}', dt, function(data) {
        if (data.errno == 0) {
        	updateCount++;
            var html = '<table><caption>第 '+ updateCount +' 次请求结果</caption></table>';
            html += '<table><caption>' + data.content + '</caption></table>';
            var updateRst = data.data.updateResult;
            var i = 0;
            var iCount = updateRst.length;
            for ( i=0,iCount=iCount; i<iCount; i++ ) {
            	html += '<table><caption>' + updateRst[i] + '</caption></table>';
            }
            
            $('#data_area').html(html);
        } else {
            $('#data_area').html('<table><caption>更新失败，请稍候再试</caption></table>');
        }
    }, "json");
}

function updateAppApi(appType, codeType) 
{
    var dt = {appType:appType, codeType:codeType};
    $.get('/monitorapi/updateapp?platform={%$platform%}', dt, function(data) {
        if (data.errno == 0) {
            var html = '<table><caption>' + data.content + '</caption></table>';
            html += '<table><caption>' + data.data.updateLastLine + '</caption></table>';
            html += '<table><caption>' + data.data.updateResult + '</caption></table>';
            $('#data_area').html(html);
        } else {
            $('#data_area').html('<table><caption>更新失败，请稍候再试</caption></table>');
        }
    }, "json");
}

function stopUpdateApi()
{
	clearInterval(API);
	var html = $('#data_area').html();
	html += '<table><caption>更新结束！</caption></table>';
	$('#data_area').html(html);
}

</script>
</body>
</html>
