<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>运营</title>
<link media="screen" type="text/css" rel="stylesheet" href="{%$staticUrl%}/a/gb_app.css">
<style type="text/css">
<!--
html{overflow:scroll!important;}

body,td,th {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #333333;
}

a img,:link img,:visited img {
	border: 0 none;
}

.kfgj{ width:960px; height:auto;}
.title{	width:880px; height:50px; font-size:24px;color:#FFFFFF;line-height:50px;background-color: #108ac6;font-weight:bold; padding-left: 20px;}/*大标题*/
.title-02{ font-size:18px; color:#108ac6; line-height:50px; }
.cn-01{ width:850px; height:60px; padding-left: 50px; padding-top:20px; line-height:50px;}
.cn-02{	width:850px; padding-left: 50px; height:180px;   line-height:25px;}
.cn-03{	width:850px; padding-left: 50px; height:auto;line-height:25px;}

.userinfo-table{width:800px;background-color:#108ac6;}
.userinfo-table caption{font-weight:bold;font-size:14px;}
.userinfo-table th{width:133px;background-color:#afe4fe;color:#333;text-align:center;font-weight:bold;border:1px;}
.userinfo-table td{height:130px;text-align:center;font-weight:normal;background-color:#FFFFFF}

.usercardinfo-table{width:800px;background-color:#108ac6;}
.usercardinfo-table caption{font-weight:bold;font-size:14px;}
.usercardinfo-table th{background-color:#afe4fe;color:#333;text-align:center;font-weight:bold;border:1px;}
.usercardinfo-table .id{width:120px;}
.usercardinfo-table .name{width:160px;}
.usercardinfo-table .intro{width:400px;}
.usercardinfo-table .count{width:120px;}
.usercardinfo-table td{height:25px;text-align:left;padding-left:10px;font-weight:normal;background-color:#FFFFFF}

.invitelog-table{width:800px;background-color:#108ac6;}
.invitelog-table caption{font-weight:bold;font-size:14px;}
.invitelog-table th{background-color:#afe4fe;color:#333;text-align:center;font-weight:bold;border:1px;}
.invitelog-table .count{width:150px;}
.invitelog-table .time{width:200px;}
.invitelog-table .fid{width:450px;}
.invitelog-table td{height:25px;text-align:left;padding-left:10px;font-weight:normal;background-color:#FFFFFF}

.coinlog-table{width:800px;background-color:#108ac6;}
.coinlog-table caption{font-weight:bold;font-size:14px;}
.coinlog-table th{background-color:#afe4fe;color:#333;text-align:center;font-weight:bold;border:1px;}
.coinlog-table .time{width:150px;}
.coinlog-table .cost{width:150px;}
.coinlog-table .summary{width:500px;}
.coinlog-table td{height:25px;text-align:left;padding-left:10px;font-weight:normal;background-color:#FFFFFF}

.notice-table{width:900px;background-color:#108ac6;}
.notice-table caption{font-weight:bold;font-size:14px;}
.notice-table th{background-color:#afe4fe;color:#333;text-align:center;font-weight:bold;border:1px;}
.notice-table .id{width:50px;}
.notice-table .titl{width:275px;}
.notice-table .link{width:250px;}
.notice-table .position{width:50px;}
.notice-table .opened{width:50px;}
.notice-table .time{width:125px;}
.notice-table td{height:25px;text-align:left;padding-left:10px;font-weight:normal;background-color:#FFFFFF}

div,form,dl,dt,dd,img,h1,h2,h3,h4,h5,h6,ul,ol,li,p,span,table,th,td,a{margin:0;padding:0;border:0}
img{border:none;vertical-align:middle}
body{font-family:"宋体",Verdana,Arial,Helvetica,sans-serif;font-size:12px}
button{border:none;cursor:pointer;background:none;font-size:12px;text-align:center}

#msgboxDiv {display:none;position:absolute;}

-->
</style>
</head>
<body>
<div style="height:1500px; font-size:12px;">
	<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
	<script src="{%$staticUrl%}/js/utils.js?v=1.0" type="text/javascript"></script>
	<div id="top" style="padding:5px;background-color:#FEF5D8;">
		<label style="font-weight:bold;">本次登录时间：{%$ts|date_format:"%Y-%m-%d %H:%M:%S"%}</label>&nbsp;&nbsp;<a href="/index/logout" target="_self">注销</a>
	</div>

	<div class="cn-01">
		<label class="column" for="uid">查询用户小岛门牌号：</label>
		<input type="text" class="text" style="ime-mode: disabled;" tabindex="1" name="uid" id="uid">
		<input type="submit" tabindex="4" name="btsubmit" id="btsubmit" value="查 询" onclick="getUserInfo();">
	</div>

	<div id="userinfo_area" class="cn-02"></div>

	<div id="item_info_area" style="display:none;">
		<div class="cn-01">
			<label>选择要查询的项目：</label>
			<select id="sltItem" name="sltItem">
			    <option value="1">道具卡信息</option>
			    <option value="2">邀请好友记录</option>
			    <option value="3">金币消耗记录</option>
			</select>
			<input type="submit" value="查  询" id="btnItemSelect" name="btnItemSelect" onclick="showItem();">
		</div>

		<div id="user_data_area" style="display:none;padding-top:10px;"></div>
	</div>

	<div>
		<label>公告管理</label>
		<label>选择显示公告类型：</label>
		<select id="noticeType" name="noticeType">
		    <option value="1">所有</option>
		    <option value="2">缓存</option>
		    <option value="3">web</option>
		</select>
		<input type="submit" tabindex="4" name="btnShowNotice" id="btnShowNotice" value="显 示" onclick="getNotice();">
		<div id="notice_data_area"></div>
	</div>

	<div style="width: 417px; display: none;" class="layer_global" id="msgboxDiv">
		<div class="layer_global_main">
			<div class="layer_global_title"><h3 id="msgboxTitle"></h3><button title="关闭" id="closeQuery" onclick="closeQuery();"><span class="none">╳</span></button></div>
			<div class="layer_global_cont">
				<div style="margin: 20px;" class="wrap"><span id="msgboxContent"></span></div>
			</div>
		</div>
	</div>

</div>
<script type="text/javascript">
function timeFormat(time)
{
	var timestamp = time*1000;
	return (new Date(timestamp)).format('Y-m-d H:i:s');
}

function msgbox(title, msg, x, y)
{
	if (!x) x = 50;
	if (!y) y = 100;
	$('#msgboxDiv').css({left: x, top: y});
	$('#msgboxTitle').html(title);
	$('#msgboxContent').html(msg);
	$('#msgboxDiv').show();
}

function closeQuery()
{
	$('#msgboxDiv').hide();
}

$.ajaxSetup({cache:false});

function getUserInfo()
{
	closeQuery();
	var uid = $('#uid').val();
	var dt = {uid:uid};
	$.get('/api/getuserinfo', dt, function(data) {
		if (data.errno == 0) {
			var html = '<table cellspacing="1" class="userinfo-table"><caption>用户信息</caption><tr><th>头像</th><th>UID</th><th>呢称</th><th>等级</th><th>经验</th><th>金币</th><th></th></tr>';
			html += '<tr><td><img src="' 
				 + data.face + '"/></td><td>'
				 + data.uid + '</td><td>'
				 + data.nickname + '</td><td>'
				 + data.level + '</td><td>'
				 + data.exp + '</td><td>'
				 + data.coin + '</td><td>'
				 + '<a href="/api/watchuser?uid=' + data.uid + '" target="_blank">查看小岛</a></td>'
				 + '</tr></table>';

			$('#userinfo_area').html(html);
			$('#user_data_area').hide();
			$('#user_data_area').html('');
			$('#item_info_area').show();
		} else {
			$('#userinfo_area').html('');
			$('#item_info_area').hide();
			msgbox('错误', data.errmsg, 50, 100);
		}
	}, "json");
}

function getUserCardInfo()
{
	var uid = $('#uid').val();
	var dt = {uid:uid};
	$.get('/api/getusercardinfo', dt, function(data) {
		if (data.errno == 0) {
			var html = '<div class="cn-03"><table border="0" cellspacing="1" class="usercardinfo-table"><caption>道具卡信息</caption><tr><th class="id">ID</th><th class="name">名称</th><th class="intro">介绍</th><th class="count">数量</th></tr>';
			var cards = data.cards;
			if (cards.length == 0) {
				html += '<tr><td colspan="2" style="text-align:center;">没有记录</td></tr>';
			} else {
				for(var i in cards) {
				html += '<tr><td>' + cards[i].cid + '</td><td>'
					 + cards[i].name + '</td><td>'
					 + cards[i].introduce + '</td><td>'
					 + cards[i].count + '</td></tr>';
				}
			}
			html += '</table></div>';
			$('#user_data_area').html(html);
			$('#user_data_area').show();
		} else {
			msgbox('错误', data.errmsg, 50, 350);
		}
	}, "json");
}

function getInviteLog()
{
	var uid = $('#uid').val();
	var dt = {uid:uid};
	$.get('/api/getinvitelog', dt, function(data) {
		if (data.errno == 0) {
			var html = '<div class="cn-03"><table border="0" cellspacing="1" class="invitelog-table"><caption>邀请朋友记录</caption><tr><th class="count">个数</th><th class="time">时间</th><th class="fid">邀请好友ID</th></tr>';
			var logs = data.logs;
			var count = logs.length;
			if (count == 0) {
				html += '<tr><td colspan="3" style="text-align:center;">没有记录</td></tr>';
			} else {
				html += '<tr><td rowspan="' + count +'" style="text-align:center;padding-left:0px;">' + count + '</td><td>'
						 + timeFormat(logs[0].time) + '</td><td>'
						 + logs[0].fid + '</td></tr>';
				for(var i = 1; i < count; i++) {
					html += '<tr><td>'
						 + timeFormat(logs[i].time) + '</td><td>'
						 + logs[i].fid + '</td></tr>';
				}
			}
			html += '</table></div>';
			$('#user_data_area').html(html);
			$('#user_data_area').show();
		} else {
			msgbox('错误', data.errmsg, 50, 350);
		}
	}, "json");
}

function getCoinLog()
{
	var uid = $('#uid').val();
	var dt = {uid:uid};
	$.get('/api/getcoinlog', dt, function(data) {
		if (data.errno == 0) {
			var html = '<div class="cn-03"><table border="0" cellspacing="1" class="coinlog-table"><caption>金币消耗记录</caption><tr><th class="time">时间</th><th class="cost">消耗金币</th><th class="summary">用途</th></tr>';
			var logs = data.logs;
			if (logs.length == 0) {
				html += '<tr><td colspan="3" style="text-align:center;">没有记录</td></tr>';
			} else {
				for(var i in logs) {
				html += '<tr><td>' + timeFormat(logs[i].create_time) + '</td><td>'
					 + logs[i].cost + '</td><td>'
					 + logs[i].summary + '</td></tr>';
				}
			}
			html += '</table></div>';
			$('#user_data_area').html(html);
			$('#user_data_area').show();
		} else {
			msgbox('错误', data.errmsg, 50, 350);
		}
	}, "json");
}

function showItem()
{
	closeQuery();
	var item = $('#sltItem').val();
	switch (item) {
		case '1':
			getUserCardInfo();
			break;
		case '2':
			getInviteLog();
			break;
		case '3':
			getCoinLog();
			break;
	
	}
}

function getNotice()
{
	var type = $('#noticeType').val();
	var dt = {type:type};
	$.get('/api/getnotice', dt, function(data) {
		if (data.errno == 0) {
			var html = '<div class="cn-03"><table border="0" cellspacing="1" class="notice-table"><caption>公告</caption><tr><th class="id">ID</th><th class="titl">标题</th><th class="link">连接</th><th class="position">位置</th><th class="opened">开放</th><th class="time">时间</th><th></th></tr>';
			var notice = data.notice;
			if (notice.length == 0) {
				html += '<tr><td colspan="3" style="text-align:center;">没有记录</td></tr>';
			} else {
				for(var i = 0; i < notice.length; i++) {
				html += '<tr><td>' + + notice[i].id + '</td><td>'
					 + notice[i].title + '</td><td>'
					 + notice[i].link + '</td><td>'
					 + notice[i].position + '</td><td>'
					 + ((notice[i].opened)? '开' : '关') + '</td><td>'
					 + timeFormat(notice[i].create_time) + '</td><td>'
					 + '<a href="javascript:void(0);">修改</a>&nbsp;&nbsp;<a href="javascript:void(0);">删除</a></td>'
				}
			}
			html += '</table></div>';
			$('#notice_data_area').html(html);
			$('#notice_data_area').show();
		} else {
			msgbox('错误', data.errmsg, 50, 350);
		}
	}, "json");
}
</script>
</body>
</html>
