<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>用户数据迁移</title>
<link type="text/css" rel="stylesheet" href="{%$staticUrl%}/style/notice.css?v=1.0" />
<script src="{%$staticUrl%}/script/jquery.js" type="text/javascript"></script>
<style type="">
#notice_edit_area table {width:800px;}
.id {width:60px; text-align:center;}
.time {width:100px; text-align:center;}
.title {width:300px; text-align:center;}
.link {width:300px; text-align:center;}
.priority {width:40px; text-align:center;}
#msgboxDiv {display:none;position:absolute;}
</style>
</head>
<body>
<div>

<div id="movedata_edit_area" style="margin:10px 5px 5px 15px;">
	<select id="selectApi" name="selectApi">
	{% if $accessList %}
		{% foreach from=$accessList item=data %}
			{% if $data.project == "island" %}
				{% if $data.pid <> $thispid %}
					{% if $data.name == 'qq' || $data.name == 'weibo' || $data.name == 'renren' %}
					<option value="{%$data.name%}">{%$data.title%}</option>
					{% /if %}
				{% /if %}	
			{% /if %}
		{% /foreach %}
	{% else %}
		<span>对不起，没有权限操作</span>
	{% /if %}
	</select>
      &nbsp;&nbsp;&nbsp;
	源数据平台用户小岛门牌号：  <input type="text" id="old_uid" name="old_uid" />
	&nbsp;&nbsp;&nbsp;&nbsp;===>&nbsp;&nbsp;&nbsp;&nbsp;
  	目标平台用户小岛门牌号： <input type="text" id="new_uid" name="new_uid" />
  	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  	<input type="submit" value="确认迁移" onclick="moveData();" />
</div>
</div>
<script src="{%$staticUrl%}/js/utils.js?v=1.0" type="text/javascript"></script>
<script type="text/javascript">

$.ajaxSetup({cache:false});

var old_user = '';
var uid = '';
var selectApi = '';
var oldApi = {% $thispid %};

function moveData()
{
	old_user = $('#old_uid').val();
	uid = $('#new_uid').val();
	selectApi = $('#selectApi').val();

	if ((old_user == '') || (uid == '') || (selectApi == '')) {
		alert('错误,数据缺失');
		return false;
	}

	var pardata = {uid:uid, old_uid:old_user, selectApi:selectApi};
	$.get('/movedata/movedata?platform={%$platform%}', pardata, function(data) {
		if (data.errno == 0) {
			alert('成功');
		} else {
			alert('错误');
		}
	}, "json");	
}

</script>
</body>
</html>
