<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>邀请朋友 - 欢乐海岛</title>
<link href="{%$staticUrl%}/apps/island/css_2011041201.css?v=1.01" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--
a img,:link img,:visited img {
	border: 0 none;
}
-->
</style>
</head>
<body>
<div class="main">
{%include file="menu.phtml"%}

<div id="main_content" class="content" style="height:820px;padding-top:2px;">
<div id="invite_award">
<table width="748" border="0" cellspacing="0" cellpadding="0">
	<tr>
		<td height="39" colspan="5" background="{%$staticUrl%}/apps/island/images/invite/bg_01.gif">
		<table width="100" border="0" align="right" cellpadding="0" cellspacing="0">
			<tr>
				<td><a href="javascript:void(0);" onclick="goHome();return false;">返回游戏&gt;&gt;</a></td>
			</tr>
		</table>
		</td>
	</tr>
	<tr>
		<td height="355" width="43" background="{%$staticUrl%}/apps/island/images/invite/bg_02.gif"></td>
		<td height="355" width="191" background="{%$staticUrl%}/apps/island/images/invite/{%$epath%}bg_013.gif"></td>
		<td height="355" width="315" background="{%$staticUrl%}/apps/island/images/invite/{%$epath%}bg_24.gif"></td>
		<td height="355" width="157" background="{%$staticUrl%}/apps/island/images/invite/{%$epath%}bg_15.gif"></td>
		<td height="355" width="42" background="{%$staticUrl%}/apps/island/images/invite/bg_06.gif"></td>
	</tr>
	<tr>
		<td height="34" width="43" background="{%$staticUrl%}/apps/island/images/invite/bg_07.gif"></td>
		<td colspan="3" bgcolor="#E5F6FD" align="center">
			<a href="javascript:void(0);" onclick="showInviteFriend();"><img src="{%$staticUrl%}/apps/island/images/invite/btnInvite.gif" alt="邀请好友" width="129" height="33" border="0" /></a>
		</td>
		<td height="34" width="42" background="{%$staticUrl%}/apps/island/images/invite/bg_12.gif"></td>
	</tr>
	<tr>
		<td height="37" colspan="5" background="{%$staticUrl%}/apps/island/images/invite/bg_13.gif"></td>
	</tr>
</table>
</div>
<div id="invite_friend" style="padding-left:2px;">
<iframe id="invite_frame" width="750" height="700" scrolling="no" frameborder="0" src="#" style="display:none;"></iframe>
</div>
</div>

{%include file="cmscript.phtml"%}
<script type="text/javascript">
	function showInviteFriend()
	{
		/*HF.Island.inviteFriend('invite_frame');
		$('#invite_friend').show();
		$('#invite_frame').show();
		$('#invite_award').hide();
		*/
		HFApp.sendInvite();
	}
</script>
</body>
</html>

