<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>

<div id="slider">
	<ul>
		<li style="display:inline"><a href='http://apps.renren.com/hellocake/?channel=5&source=49' target="_blank"><img src="{%$staticUrl%}/apps/island/images/slider/newitem-20110929.jpg" style="display:none;"/></a></li>
		<li style="display:inline"><a href='http://apps.renren.com/hellocake/?channel=5&source=49' target="_blank"><img src="{%$staticUrl%}/apps/island/images/slider/newitem-20110617.jpg" style="display:none;"/></a></li>
   </ul>
</div>
<div class="title">
	<div class="menu">
        <ul style="padding-left:170px;width:700px;">
        	<li style="width:76px;"><a href="http://apps.renren.com/{%$smarty.const.APP_NAME%}/" target="_top"><img src="{%$staticUrl%}/apps/island/images/menu/v2/home.gif" title="我的小岛" alt="我的小岛" /></a></li>
        	<li style="width:88px;"><a href="/invite/top"><img src="{%$staticUrl%}/apps/island/images/menu/v2/invite.gif" title="邀请好友" alt="邀请好友" /></a></li>
        	<li style="width:76px;"><a href="/gift/top"><img src="{%$staticUrl%}/apps/island/images/menu/v2/gift.gif" title="赠送礼物" alt="赠送礼物" /></a></li>
        	<li style="width:95px; margin-top:-6px;"><a href="/pay/top"><img src="{%$staticUrl%}/apps/island/images/menu/v2/pay20111025.gif" title="兑换宝石" alt="兑换宝石" /></a></li>
        	<li style="width:68px;"><a href="http://group.renren.com/GetTribe.do?id=320022384" target="_blank"><img src="{%$staticUrl%}/apps/island/images/menu/v2/forum.gif" title="玩家论坛" alt="玩家论坛" /></a></li>
        	<li style="width:68px;"><a href="http://group.renren.com/GetThread.do?id=330727427&parentpage=&curpage=0&label=&tribeId=320022384" target="_blank"><img src="{%$staticUrl%}/apps/island/images/menu/v2/help.gif" title="帮助" alt="帮助" /></a></li>
        </ul>
	</div>
</div>
    {% if $showNotice == true %}
	  <div class="guang">
    	  <div class="guang_b" style="clear:both;">
    	<div style="display:block;float:right; padding-top:3px;"><iframe scrolling="no" frameborder="0" allowtransparency="true" src="http://www.connect.renren.com/like?url=http%3A%2F%2Fpage.renren.com%2Frrisland" style="width: 140px;height: 22px;"></iframe></div>
    	  </div>
    	  <div style="clear:both;"></div>
	  {% foreach from=$mainNotice item=data %}
    	  <div class="zleft guang_z">{%if $data.link%}<a href="{%$data.link%}" target="_blank">[{%$data.create_time|date_format:"%Y-%m-%d"%}]  {%$data.title%}</a>{%else%}[{%$data.create_time|date_format:"%Y-%m-%d"%}]  {%$data.title%}{%/if%}</div>
    	 {% /foreach %}
</div>
{% /if %}
<script src="{%$staticUrl%}/js/jquery.flashSlider-1.0.min.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery("#slider").flashSlider({controlsShow: false,vertical: true, speed: 1500, pause: 6000});
    });
</script>