<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>防沉迷| 快乐岛主</title>
    <link href="{%$staticUrl%}/apps/island/main_2011041101.css?v=1.01" rel="stylesheet" type="text/css" />
    <link href="{%$staticUrl%}/apps/island/pay_2011031501.css?v=1.00" rel="stylesheet" type="text/css" />
    <style type="text/css">
        html, body { height:100%; }
        body { margin:0; }
    </style>
    <script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
</head>
<body>
<div class="main">
{%include file="menu.phtml"%}
<table width="537" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td height="274" background="{%$staticUrl%}/apps/island/images/indulge.gif">
    <table width="270" border="0" align="right" cellpadding="0" cellspacing="0">
      <tr>
        <td width="188" height="24"></td>
        <td width="82" rowspan="2"></td>
      </tr>
      <tr>
        <td  height="83" style="width:200px">
        <table width="93%" border="0" align="center" cellpadding="0" cellspacing="0">
        <tr>
            <td>亲爱的玩家，您好!<br />
                        快乐岛主充值系统正在调整，请您稍候再来哦。<br />
            </td>
        </tr>
        <tr><td align="right">&nbsp;&nbsp;</td></tr>
        </table>
        </td>
      </tr>
    </table>
    </td>
  </tr>
</table>
    
</div>
</body>
</html>