<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>充值| 快乐岛主</title>
    <link href="{%$staticUrl%}/apps/island/main_2011041101.css?v=1.01" rel="stylesheet" type="text/css" />
    <link href="{%$staticUrl%}/apps/island/pay_2011031501.css?v=1.00" rel="stylesheet" type="text/css" />
    <style type="text/css">
        html, body { height:100%; }
        body { margin:0; }
    </style>
    <script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
</head>
<body>
<div class="main">
{%include file="menu.phtml"%}

	<div class="chongzhicontent">
		<img src="{%$user.face%}" width="59" height="60" />
		<div class="xinxi">
			<div class="cname">{%$user.name|escape%}</div>
			<div class="shuzi">宝石： <span style="color:#3c7e9a;font-weight:bold;">{%$user.gold%}</span></div>
			<div class="fhyx"><a href="http://apps.renren.com/{%$smarty.const.APP_NAME%}" target="_top"><img style="border:medium none;" src="{%$staticUrl%}/apps/island/images/pay/back.gif" width="80" height="35" /></a></div>
		</div>
	</div>

	<div class="table">
		<ul>
		<li style="width:50px"></li>
		<li><a href="{%$baseUrl%}/pay/top"><div class="nav_01">充值宝石</div></a></li>
		<li><a href="{%$baseUrl%}/pay/log"><div class="nav_02">充值记录</div></a></li>
		<li><a href="{%$baseUrl%}/consumelogs/gold"><div class="nav_02">消费记录</div></a></li>
		</ul>
	</div>

	<div class="content" style="padding-top:10px;padding-left:40px;width:740px;">
		<div align=center>充值已经关闭</div>
		<!-- <div style="color:red;padding:0 0 10px 0;">
充值送好礼！升级更快！宝石更多！<br />
<font color="blue">
一次性兑换 10人人豆 即可获赠“加送5宝石、五星建筑吸血鬼男爵”<br />
一次性兑换 20人人豆 即可获赠“加送10宝石、5星建筑吸血鬼夫人”<br />
一次性兑换 50人人豆 即可获赠“加送80宝石、5星建筑吸血鬼男爵、5星建筑吸血鬼夫人”<br />
一次性兑换 100人人豆 即可获赠“加送200宝石、5星建筑吸血鬼男爵、5星建筑吸血鬼夫人”</font>
		</div> -->
		<!--<form id="frmPayOrder" method="post" action="http://app.renren.com/pay/web/submitOrder" target="_top">
			<input type="hidden" value="{%$smarty.const.APP_ID%}" name="app_id" />
			<input type="hidden" value="" id="order_number" name="order_number" />
			<input type="hidden" value="" id="token" name="token" size="50" />
			<input type="hidden" value="http://apps.renren.com/{%$smarty.const.APP_NAME%}/" id="redirect_url" name="redirect_url" size="50" />
			<input type="hidden" value="" id="order_desc" name="desc" size="50" />
			<div class="chongzhi" style="margin:40px 0 0 0;">
				<div align="center">
					<p><img src="{%$staticUrl%}/apps/island/images/pay/v20111025/pay_10.gif"  id="dm1" class="diamond" onclick="payOrder('frmPayOrder', 10);" title="兑换100宝石" /><br />
						价格：10人人豆<br />
						<input type="button" name="btnOrder1" id="btnOrder1" onclick="payOrder('frmPayOrder', 10);" value="充值" class="orderbtn" class="diamond" />
					</p>
					<label></label>
				</div>
			</div>
			<div class="chongzhi" style="margin:40px 0 0 0;">
				<div align="center">
					<p><img src="{%$staticUrl%}/apps/island/images/pay/v20111025/pay_20.gif" id="dm2" class="diamond" onclick="payOrder('frmPayOrder', 20);" title="兑换200宝石，送20宝石" /><br />
						价格：20人人豆<br />
						<input type="button" name="btnOrder2" id="btnOrder2" onclick="payOrder('frmPayOrder', 20);" value="充值" class="orderbtn" class="diamond" />
					</p>
					<label></label>
				</div>
			</div>
			<div class="chongzhi" style="margin:40px 0 0 0 ;">
				<div align="center">
					<p><img src="{%$staticUrl%}/apps/island/images/pay/v20111025/pay_50.gif" id="dm3" class="diamond" onclick="payOrder('frmPayOrder', 50);" title="兑换500宝石，送60宝石"/><br />
						价格：50人人豆<br />
						<input type="button" name="btnOrder3" id="btnOrder3" onclick="payOrder('frmPayOrder', 50);" value="充值" class="orderbtn" class="diamond" />
					</p>
					<label></label>
				</div>
			</div>
			<div class="chongzhi" style="margin:40px 0 0 0;">
				<div align="center">
					<p><img src="{%$staticUrl%}/apps/island/images/pay/v20111025/pay_100.gif" id="dm4" class="diamond" onclick="payOrder('frmPayOrder', 100);" title="兑换1000宝石，送140宝石"/><br />
						价格：100人人豆<br />
						<input type="button" name="btnOrder4" id="btnOrder4" onclick="payOrder('frmPayOrder', 100);" value="充值" class="orderbtn" class="diamond" />
					</p>
					<label></label>
				</div>
			</div>
			<div class="chongzhi" style="margin:40px 0 0 0;">
				<div align="center">
					<p><img src="{%$staticUrl%}/apps/island/images/pay/4_9.gif" id="dm5" class="diamond" onclick="payOrder('frmPayOrder', 500);" title="兑换5000宝石，送800宝石"/><br />
						价格：500人人豆<br />
						<input type="button" name="btnOrder5" id="btnOrder5" onclick="payOrder('frmPayOrder', 500);" value="充值" class="orderbtn" class="diamond" />
					</p>
					<label></label>
				</div>
				</div>
		</form>-->
        <script type="text/javascript">

            function enableSubmit()
            {
            	document.getElementById('btnOrder1').disabled = false;
            	document.getElementById('btnOrder2').disabled = false;
            	document.getElementById('btnOrder3').disabled = false;
            	document.getElementById('btnOrder4').disabled = false;

            }

            function disableSubmit()
            {
            	document.getElementById('btnOrder1').disabled = false;
            	document.getElementById('btnOrder2').disabled = false;
            	document.getElementById('btnOrder3').disabled = false;
            	document.getElementById('btnOrder4').disabled = false;

            }

            function submit(f, num)
            {
                var pForm = document.getElementById(f);
                var url = '{%$hostUrl%}/callback/pay';
                var params = {'amount': num};
                ajaxRequest(url, params, pForm);
            }

			function ajaxRequest(url, params, pForm)
			{
				$.ajax({type:'post',
					url:url,
					data:params,
					dataType:'json',
					success:function(data){
						if(data != '') {
	                    	$('#token').val(data.token);
	                    	$('#order_number').val(data.orderid);
	                    	$('#order_desc').val(data.amount + "个人人豆兑换" + data.gold + "个宝石");
	                    	pForm.submit();
						} else{
							alert("[出现错误啦]: 暂时无法提交订单，请稍后重试。");
						}
						enableSubmit();
					},
					error:function(){
						alert("[出现错误啦]: 暂时无法提交订单，请稍后重试。");
						enableSubmit();
					}
				});
			}

            function payOrder(f, num)
            {
            	disableSubmit();
                submit(f, num);
            }

			enableSubmit();
        </script>
	</div>
</div>
</body>
</html>