<?php

// swf list
$swfList = array(
    STATIC_HOST . '/new_swf/swc.swf?v=2010111701',
    STATIC_HOST . '/new_swf/swc2.swf?v=2010111701',
    STATIC_HOST . '/new_swf/swc3.swf?v=2010111701',
    STATIC_HOST . '/new_swf/levelUp.swf?v=2010111701',
    STATIC_HOST . '/new_swf/building1.swf?v=2010111701',
    STATIC_HOST . '/new_swf/building2.swf?v=2010111701',
    STATIC_HOST . '/new_swf/building3.swf?v=2010111701',
    STATIC_HOST . '/new_swf/building4.swf?v=2010111701',
    STATIC_HOST . '/new_swf/building5.swf?v=2010122001',
    STATIC_HOST . '/new_swf/building6.swf?v=2010122001',
    STATIC_HOST . '/new_swf/building7.swf?v=2011011301',
    STATIC_HOST . '/new_swf/building8.swf?v=2011011301',
	STATIC_HOST . '/new_swf/building9.swf?v=2011011701',
	STATIC_HOST . '/new_swf/building10.swf?v=2011011701',
    STATIC_HOST . '/new_swf/island1.swf?v=2010111701',
    STATIC_HOST . '/new_swf/sky1.swf?v=2010122001',
    STATIC_HOST . '/new_swf/sea1.swf?v=2010111701',
    STATIC_HOST . '/new_swf/dock1.swf?v=2010111701',
    STATIC_HOST . '/new_swf/boat1.swf?v=2010111701',
    STATIC_HOST . '/new_swf/itemcard1.swf?v=2011012003',
    STATIC_HOST . '/new_swf/player1.swf?v=2010122001',
    STATIC_HOST . '/new_swf/sound1.swf?v=2010111701',
    STATIC_HOST . '/new_swf/chongzhiIcon.swf?v=2010112901',
    STATIC_HOST . '/new_swf/actIconSwc.swf?v=2010112901',
    STATIC_HOST . '/new_swf/signWinUi.swf?v=2010112901',
);

$otherSwfs = array(
    'localeTxt'         => '/',
    'help'              => 'new_swf/helpV2View.swf?v=2010111701',
	'news'				=> 'new_swf/news.swf?v=2010111701',
	'exmall'			=> 'new_swf/externalMall.swf?v=2011011901'
);

$mainswf = STATIC_HOST . '/new_swf/piao6Sns.swf?v=' . time();

$bgMusic = STATIC_HOST . '/new_swf/sound1.mp3?v=2010111701';

// interface list
$interface = array(
    'swfHostURL'        => STATIC_HOST . '/new_swf/',
    'jpgHostURL'        => STATIC_HOST . '/jpg/',
    'interfaceHostURL'  => HOST . '/',
    'loadFriends'       => 'api2/getfriends',
    'loadInit'          => 'api2/inituser?v=2011012101',
    'loadIsland'        => 'api2/initisland',
    'loadDock'          => 'api2/initdock',
    'recive'            => 'api2/receiveboat',
    'steal'             => 'api2/moochvisitor',
    'dockUpgrade'       => 'api2/addboat',
    'loadShop'          => 'api2/loadshop',
    'loadItems'         => 'api2/loaditems',
    'saleItems'         => 'api2/saleitem',
    'useItem'           => 'api2/usecard',
    'buyItem'           => 'api2/buyitem',
    'saveDiy'           => 'api2/diyisland',
    'loadDiary'         => 'api2/readfeed',
    'loadUserInfo'      => 'api2/inituserinfo',
    'changeHelp'        => 'api2/changehelp',
    'buildingPay'       => 'api2/harvestplant',
    'takeBuildingEvent' => 'api2/manageplant',
    'buildingUpgrade'   => 'api2/upgradeplant',
    'buildingSteal'     => 'api2/moochplant',
    'readTask'          => 'api2/readtask',
    'finishTask'        => 'api2/finishtask',
    'loadTitles'        => 'api2/readtitle',
    'selectTitle'       => 'api2/changetitle',
    'loadBoatClassState'=> 'api2/readship',
    'selectBoat'        => 'api2/changeship',
    'unLockBoat'        => 'api2/unlockship',
    'loadRemind'        => 'api2/readremind',
    'sendRemind'        => 'api2/addremind',
	'getGemNum'			=> 'api2/getgold',
	'getGiftList'		=> 'api2/getgiftpackagelist',
	'openPack'			=> 'api2/opengiftpackage',
	'updateGiftNum'		=> 'api2/getgiftpackagenum',
	'useAllPay'			=> 'api2/harvestallplant',
	'cdkExchange'		=> 'event/checkcdkey',
	'evtgainlevtengift'	=> 'event/tenlvlaward',
	'goldegg'			=> 'event/goldegg',
	'testGift'			=> 'event/testgift',
	'qqGet5DayAward'	=> 'event/active5day',
	'qqGetSignDay'		=> 'event/getactiveday',
	'collectCatsItems'	=> 'event/getkitteninfo',
	'exchangeCat'		=> 'event/exchangekitten',
	'exchangeFinal'		=> 'event/exchangekittenfinal',
	'readYaoQingState'	=> 'event/getinviteflowstate',
	'getYaoQingStepAward'	=> 'event/inviteaward',
	'OpenBrideToGetFBNums'     	=> 'event/loadnewyearitem',
	'OpenBrideToGetUsers'     	=> 'event/loadnewyearawardlist',
	'OpenBrideToOpenBride'     	=> 'event/opennewyearredpaper',
	'OpenBrideToCheckFLS'     	=> 'event/checknewyeargained',
	'OpenBrideToTranslate'     	=> 'event/exchangenewyearaward',
	'exChangeTuZiCdKey'			=> 'event/cdkeyrabbit',
	'buySalesPack'     			=> 'event/salemall',
	'caishenTodayInfo'     		=> 'event/getwealthgod',
	'caishen'     				=> 'event/wealthgod',
	'valentineActBegin'			=> 'event/loadvalentine',
	'vTransLateRose'			=> 'event/exchangevalentine',
	'toSendRose'				=> 'event/loadvalentinerose',
	'selectAndSendOutRose'		=> 'event/sendvalentinerose',
	'selectAndAskForRose'		=> 'event/askvalentinerose',
	'vToBuyRose'				=> 'event/buyvalentinerose',
	'vTogetRankList'			=> 'event/loadvalentinerank',
	'tanabataExchange'          => 'event/exchangeqixi',
	'tanabataGift'              =>'event/getqixigift',
	'exchangeFragment'			=>'event/exchangefragment',
);

$swfResult = array(
    'swfs'      => $swfList,
    'otherSwfs' => $otherSwfs,
    'mainswf'   => $mainswf,
    'bgMusic'	=> $bgMusic,
    'interface' => $interface
);

