<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>限时抢购</title>
		<script type="text/javascript" src="{% $staticUrl %}/js/jquery-1.4.3.min.js"></script>
	</head>
	<body>
		<div>
			<h5>
			{% foreach from=$datavo item=data %}
				<form action="{%$hostUrl%}/whoiscoin/panicupdate" method="post">
					序号:<input type="text" name="data[sale_id]" size="2" value="{%$data.sale_id%}" />
					<!--名字:<input type="text" name="data[sale_name]" size="5" value="{%$data.sale_name%}" />&nbsp;-->
					价格:<input type="text" name="data[sale_price]" size="5" value="{%$data.sale_price%}" />&nbsp;
					类型:<input type="text" name="data[sale_type]" size="4" value="{%$data.sale_type%}" />&nbsp;
					ID:<input type="text" name="data[cid]" size="15" value="{%$data.cid%}" />&nbsp;
					个数:<input type="text" name="data[num]" size="8" value="{%$data.num%}" />&nbsp;
					<!--宝石:<input type="text" name="data[gold]" size="4" value="{%$data.gold%}" />&nbsp;-->
					金币:<input type="text" name="data[coin]" size="5" value="{%$data.coin%}" />&nbsp;
					海星:<input type="text" name="data[starfish]" size="4" value="{%$data.starfish%}" />&nbsp;
					数量限制:<input type="text" name="data[sale_num]" size="4" value="{%$data.sale_num%}" />&nbsp;
					开始:<input type="text" name="data[start_time]" size="18" value="{%$data.start_time|date_format:'%Y-%m-%d %H:%M:%S'%}" />&nbsp;&nbsp;
					结束:<input type="text" name="data[end_time]" size="18" value="{%$data.end_time|date_format:'%Y-%m-%d %H:%M:%S'%}" />
					<input type="submit" value="更新" />
				</form>
				<br />
			{% /foreach %}
		</div>

		<form action="{%$hostUrl%}/whoiscoin/panicadd" method="post">
			<input type="submit" name="add" value="新加一条" />
		</form>
		<br/>

		<form action="{%$hostUrl%}/whoiscoin/clearpanic" method="post">
			<input type="submit" name="all" value="缓存清理" />
		</form>
		</h5>
	</body>
</html>