
<script type="text/javascript">
var HFApp = {
		appId: "{%$appId%}",
		appHost: "{%$hostUrl%}",

		loadHtml: function(url, method, pardata, dataType, id) {//require jquery api support
			if (!method) { //("POST"  or  "GET")
				method = 'GET';
			}
			if (!dataType) {//xml
				dataType = "text";
			}
			$.ajax({
                type: method,
                url: url,
                data: pardata,
                dataType: dataType,
                success: function(resp){
                	$("#" + id).html(resp);
                }
	 		});
		}
	}

//    function initInvite(show)
//    {
//    {% if $smarty.const.APP_ID==130346993713055 %}
//    	//$("#divWyxFrame").html('<iframe src="http://game.weibo.com/home/widget/selector?&target=self&appId=1142074347&mode=naf&action=http%3A%2F%2Fweibo-t1.happyfish001.com%2Finvite%2Fsend&excludeIds=&pageSize=12&content=%E6%B2%99%E6%BB%A9%E7%8B%82%E6%AC%A2%E3%80%81%E6%B5%B7%E5%B2%9B%E5%AF%BB%E5%AE%9D%EF%BC%81%E5%85%A8%E5%9B%BD%E7%AC%AC%E4%B8%80%E6%AC%BE%E6%B5%B7%E5%B2%9B%E6%A8%A1%E6%8B%9F%E7%BB%8F%E8%90%A5%E6%B8%B8%E6%88%8F%EF%BC%8C%E5%B8%A6%E4%BD%A0%E4%B9%90%E4%BA%AB%E6%B5%AA%E6%BC%AB%E6%B5%B7%E5%B2%9B%E7%94%9F%E6%B4%BB%EF%BC%8C%E4%B8%80%E8%B5%B7%E6%9D%A5%E7%8E%A9%E5%90%A7&callback=http%3A%2F%2Fgame.weibo.com%2Fisland_dev" width="95%" height="470px" frameborder="no"></iframe>');
//    	$("#divWyxFrame").html('<div class="requestForm"><form method="post" action="http://game.weibo.com/home/widget/requestForm" id="createToolFriend" target = "friendSelector"><input type="hidden" name="target" value="self" /><input type="hidden" name="appId" value="1142074347" /><input type="hidden" name="modes" value="all,af,naf" /><input type="hidden" name="selectedMode" value="naf" /><input type="hidden" name="action" value="http://weibo-t1.happyfish001.com/invite/send" /><input type="hidden" name="excludedIds" value="" /><input type="hidden" name="pageSize" value="16" /><input type="hidden" name="content" value="沙滩狂欢、海岛寻宝！全国第一款海岛模拟经营游戏，带你乐享浪漫海岛生活，一起来玩吧" /><input type="hidden" name="callback" value="http://game.weibo.com/island_dev/" /></form><iframe width="670px" height="470px" frameborder="0" src="" name="friendSelector" scrolling="no" id="friendSelector"></iframe></div>');
//    {% else %}
//    	//$("#divWyxFrame").html('<iframe src="http://game.weibo.com/home/widget/selector?&target=self&appId=401380203&mode=naf&action=http%3A%2F%2Ft.happyfishgame.com.cn%2Finvite%2Fsend&excludeIds=&pageSize=20&content=%E6%B2%99%E6%BB%A9%E7%8B%82%E6%AC%A2%E3%80%81%E6%B5%B7%E5%B2%9B%E5%AF%BB%E5%AE%9D%EF%BC%81%E5%85%A8%E5%9B%BD%E7%AC%AC%E4%B8%80%E6%AC%BE%E6%B5%B7%E5%B2%9B%E6%A8%A1%E6%8B%9F%E7%BB%8F%E8%90%A5%E6%B8%B8%E6%88%8F%EF%BC%8C%E5%B8%A6%E4%BD%A0%E4%B9%90%E4%BA%AB%E6%B5%AA%E6%BC%AB%E6%B5%B7%E5%B2%9B%E7%94%9F%E6%B4%BB%EF%BC%8C%E4%B8%80%E8%B5%B7%E6%9D%A5%E7%8E%A9%E5%90%A7&callback=http%3A%2F%2Fgame.weibo.com%2Fhappyisland" width="95%" height="470px" frameborder="no"></iframe>');
//    	$("#divWyxFrame").html('<div class="requestForm"><form method="post" action="http://game.weibo.com/home/widget/requestForm" id="createToolFriend" target = "friendSelector"><input type="hidden" name="target" value="self" /><input type="hidden" name="appId" value="401380203" /><input type="hidden" name="modes" value="all,af,naf" /><input type="hidden" name="selectedMode" value="naf" /><input type="hidden" name="action" value="http://t.happyfishgame.com.cn/invite/send" /><input type="hidden" name="excludedIds" value="" /><input type="hidden" name="pageSize" value="16" /><input type="hidden" name="content" value="沙滩狂欢、海岛寻宝！全国第一款海岛模拟经营游戏，带你乐享浪漫海岛生活，一起来玩吧" /><input type="hidden" name="callback" value="http://game.weibo.com/happyisland/" /></form><iframe width="670px" height="470px" frameborder="0" src="" name="friendSelector" scrolling="no" id="friendSelector"></iframe></div>');
//    {% /if %}
//
//    	//5document.getElementById("createToolFriend").submit();
//    	if ('1' == show) {
//    		showInvite();
//    	}
//    }
//
//    function showInvite()
//    {
//    	$("#selFriend").toggle('fast');
//    }
//
    /* about gift page -S */
    function showGift()
    {
    	if ($("#divGiftFrame").html() == '') {
    		topGift();
    	}
    	$("#giftBox").toggle('fast');
    }

    function topGift()
    {
    	var url = HFApp.appHost + "/gift/top";
		var pardata = {};
		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divGiftFrame');
    }

    function getGift()
    {
    	var url = HFApp.appHost + "/gift/get";
		var pardata = {};
		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divGiftFrame');
    }

    function postGift()
    {
    	var url = HFApp.appHost + "/gift/post";
		var pardata = {};
		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divGiftFrame');
    }

    function friendsGift(tid, gid)
    {
    	var url = HFApp.appHost + "/gift/friends";
		var pardata = {'tid':tid, 'gid':gid};
		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divGiftFrame');
    }

    function showGiftLogPost(page)
    {
    	var url = HFApp.appHost + "/gift/post";
		var pardata = {'page':page};
		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divGiftFrame');
    }

    function showGiftLogGet(page)
    {
    	var url = HFApp.appHost + "/gift/get";
		var pardata = {'page':page};
		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divGiftFrame');
    }
    /* about gift page -E */
    
//    function showPay()
//    {
//    	if ($("#divPayFrame").html() == '') {
//    		//topPay(connectSnsplus);
//    	}
//    	$("#payBox").toggle('fast');
//    }
//
//    function topPay(connectSnsplus)
//    {
//		var url = HFApp.appHost + "/pay/top";
//
//		if (connectSnsplus == '') {
//			var pardata = {};
//		} else {
//			var pardata = {'entrance' : 'connect'};
//		}
//		
//		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divPayFrame');
//    }
//
//    function payLog()
//    {
//    	var url = HFApp.appHost + "/pay/log";
//		var pardata = {};
//		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divPayFrame');
//    }
//
//    function paySystem()
//    {
//    	var url = HFApp.appHost + "/pay/system";
//		var pardata = {};
//		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divPayFrame');
//    }
//
//    function consGold()
//    {
//    	var url = HFApp.appHost + "/consumelogs/gold";
//		var pardata = {};
//		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divPayFrame');
//    }
//
//    function consCoin()
//    {
//    	var url = HFApp.appHost + "/consumelogs/coin";
//		var pardata = {};
//		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divPayFrame');
//    }
//
//	function goToPaySNS(connectSnsplus)
//	{
//		var url = HFApp.appHost + "/pay/pay";
//
//		if (connectSnsplus == '') {
//			var pardata = {};
//		} else {
//			var pardata = {'entrance' : 'connect'};
//		}
//			
//		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divPayFrame');
//	}
//    
//	function goToPay()
//	{
//		var url = HFApp.appHost + "/pay/pay";
//		var pardata = {};
//
//		HFApp.loadHtml(url, 'POST', pardata, 'text', 'divPayFrame');
//	}

    function initGameOther()
    {
    	//console.debug('init game other');
    	//initInvite();
	    //$("#mnuInvite,#mnuInviteCls,#mnuFan,#mnuFanCls,#mnuGift,#mnuGiftCls,#mnuPay,#mnuPayCls").unbind('click');
		$("#mnuGift,#mnuGiftCls").unbind('click');
	    //$("#mnuPay,#mnuPayCls").unbind('click');
	    //$("#mnuInvite").click(showInvite);
	    //$("#mnuInviteCls").click(showInvite);
	    //$("#mnuFan").click(showFanbox);
	    //$("#mnuFanCls").click(showFanbox);
	    $("#mnuGift").click(showGift);
	    $("#mnuGiftCls").click(showGift);
	    //$("#mnuPay").click(showPay);
	    //$("#mnuPayCls").click(showPay);
	    //$("#slider").html('<ul><li style="display:inline"><a href="#"><img src="{%$staticUrl%}/apps/island/images/slider/newitem-20110718-1.jpg" style="display:none;"/></a></li><li style="display:inline"><a href="#"><img src="{%$staticUrl%}/apps/island/images/slider/newitem-20110718-1.jpg" style="display:none;"/></a></li></ul>');
	    //$("#slider").flashSlider({controlsShow: false,vertical: true, speed: 1500, pause: 6000});
	    //$("#extfrmRank").html('<iframe src="http://game.weibo.com/home/widget/box?box=friend&appId=401380203&width=760&title=%E6%8E%92%E8%A1%8C%E6%A6%9C&select=2" width="760" height="186" frameborder="no"></iframe>');
    }

	$(document).ready(function() {
		if (typeof(IS_INDEX_PAGE) == "undefined") {
			initGameOther();
		}
	});
</script>