<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>

<div id="slider">
	<ul>
		<li style="display:inline"><a href='http://bangpai.taobao.com/group/thread/570689-270700611.htm' target="_blank"><img src="{%$staticUrl%}/apps/island/images/slider/newitem-2012051801.jpg" style="display:none;"/></a></li>
		<li style="display:inline"><a href='http://yingyong.taobao.com/show.htm?app_id=22001&from=daozhu' target="_blank"><img src="{%$staticUrl%}/apps/island/images/slider/newitem-2012051802.jpg" style="display:none;"/></a></li>
		<li style="display:inline"><a href='http://yingyong.taobao.com/show.htm?app_id=22001&from=kuailedaozhu' target="_blank"><img src="http://itry.try8.info/xfiles/misc/760x100.jpg" style="display:none;"/></a></li>
   </ul>
</div>
{%include file="cmscript.phtml"%}
<div class="title1">
	<div class="menu">
        <ul style="padding-left:170px;width:700px;">
        	<li style="width:76px;"><a href="http://yingyong.taobao.com/show.htm?app_id=73015" target="_top"><img src="{%$staticUrl%}/apps/island/images/menu/v2/home.gif" title="我的小岛" alt="我的小岛" /></a></li>
        	<!-- <li style="width:88px;"><a href="{%$baseUrl%}/invite/top"><img src="{%$staticUrl%}/apps/island/images/menu/v2/invite.gif" title="邀请好友" alt="邀请好友" /></a></li> -->
        	<li style="width:88px;"><a href="#" onclick="inviteFriend();"><img src="{%$staticUrl%}/apps/island/images/menu/v2/invite.gif" title="邀请好友" alt="邀请好友" /></a></li>
        	<!-- <li style="width:76px;"><a href="{%$baseUrl%}/gift/top"><img src="{%$staticUrl%}/apps/island/images/menu/v2/gift.gif" title="赠送礼物" alt="赠送礼物" /></a></li> -->
        	<li style="width:76px;"><a id="mnuGift" href="javascript:void(0);"><img src="{%$staticUrl%}/apps/island/images/menu/v2/gift.gif" title="赠送礼物" alt="赠送礼物" /></a></li>
        	<li style="width:95px; margin-top:-6px;"><a href="{%$baseUrl%}/pay/top"><img src="{%$staticUrl%}/apps/island/images/menu/v2/pay/pay_20120509.gif" title="兑换宝石" alt="兑换宝石" /></a></li>
        	<li style="width:68px;"><a href="http://bangpai.taobao.com/group/570689.htm" target="_blank"><img src="{%$staticUrl%}/apps/island/images/menu/v2/forum.gif" title="玩家论坛" alt="玩家论坛" /></a></li>
        	<li style="width:68px;"><a href="http://im.robot.aliapp.com/all/aliqzg/index.jsp?id=2&&page=KLDZ&ask=%E6%80%8E%E6%A0%B7%E6%89%A9%E5%A4%A7%E5%B2%9B%E5%B1%BF%EF%BC%9F" target="_blank"><img src="{%$staticUrl%}/apps/island/images/menu/v2/help.gif" title="帮助" alt="帮助" /></a></li>
        </ul>
	</div>
</div>
    {% if $showNotice == true %}
	  <div class="guang">
    	  <div class="guang_b" style="clear:both;">
    	<!-- <div style="display:block;float:right; padding-top:3px;"><iframe scrolling="no" frameborder="0" allowtransparency="true" src="http://www.connect.renren.com/like?url=http%3A%2F%2Fpage.renren.com%2Frrisland" style="width: 140px;height: 22px;"></iframe></div> -->
    	  </div>
    	  <div style="clear:both;"></div>
	  {% foreach from=$mainNotice item=data %}
    	  <div class="zleft guang_z">{%if $data.link%}<a href="{%$data.link%}" target="_blank">[{%$data.create_time|date_format:"%Y-%m-%d"%}]  {%$data.title%}</a>{%else%}[{%$data.create_time|date_format:"%Y-%m-%d"%}]  {%$data.title%}{%/if%}</div>
    	 {% /foreach %}
	</div>
{% /if %}
<script src="{%$staticUrl%}/js/jquery.flashSlider-1.0.min.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery("#slider").flashSlider({controlsShow: false,vertical: true, speed: 1500, pause: 6000});
    });
</script>
<div id="giftBox" style="width:750px; height:600px;position:absolute;top:140px;padding-top:86px;display:none;">
    <div style="color:blue;position: absolute; left:720px;top:75px;"><a id="mnuGiftCls" href="javascript:void(0);"><img src="{%$staticUrl%}/apps/island/images/common/btnClose.png" /></a></div>
    <div id="divGiftFrame" style=""></div>
</div>