<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>充值| 快乐岛主</title>
    <link href="{%$staticUrl%}/apps/island/main_2011041101.css?v=1.01" rel="stylesheet" type="text/css" />
    <link href="{%$staticUrl%}/apps/island/pay_2011031501.css?v=1.00" rel="stylesheet" type="text/css" />
    <style type="text/css">
        html, body { height:100%; }
        body { margin:0; }
    </style>
    <script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
</head>
<body>
<div class="main">
{%include file="menu.phtml"%}

	<div class="chongzhicontent">
		<img src="{%$user.face%}" width="59" height="60" />
		<div class="xinxi">
			<div class="cname">{%$user.name|escape%}</div>
			<div class="shuzi">宝石： <span style="color:#3c7e9a;font-weight:bold;">{%$user.gold%}</span></div>
			<div class="fhyx"><a href="http://yingyong.taobao.com/show.htm?app_id=73015" target="_top"><img style="border:medium none;" src="{%$staticUrl%}/apps/island/images/pay/back.gif" width="80" height="35" /></a></div>
		</div>
	</div>

	<div class="table">
		<ul>
		<li style="width:50px"></li>
		<li><a href="{%$baseUrl%}/pay/top"><div class="nav_01">充值宝石</div></a></li>
		<li><a href="{%$baseUrl%}/pay/log"><div class="nav_02">充值记录</div></a></li>
		<li><a href="{%$baseUrl%}/consumelogs/gold"><div class="nav_02">消费记录</div></a></li>
		<li><a href="{%$baseUrl%}/pay/listorder"><div class="nav_02">订单查询</div></a></li>
		</ul>
	</div>
{% if $changestatus == 2 %}
	<div class="content" style="padding-top:10px;padding-left:40px;width:740px;">
		<div style="color:red;padding:0 0 10px 0;">
			<br /><br />
			<font color="blue" size="2px;">
				一次性充值10元即可获赠“加送5宝石、大鱼炮x5”<br />
				一次性充值20元即可获赠“加送10宝石、大鱼炮x10、挣脱2x3, 超级加速符石5*3”<br />
				一次性充值50元即可获赠“加送80宝石、大鱼炮x25、挣脱2*9, 赛鱼卡-喷泉鲸,超级加速符石5*9”<br />
				一次性充值100元即可获赠“加送200宝石、大鱼炮x50、赛鱼卡-喷泉鲸,挣脱2*20, 超级加速符石5*20”<br />
			</font>
			<br />
			<font color="red" size="2px;">注：一次性充值一元参加“天天特价”专题活动！限时，限量！</font>
		</div>
		<form id="frmPayOrder" method="get" target="_blank" action="{%$baseUrl%}/pay/gopay" style="padding-top:20px">
			<div class="chongzhi" style="margin:40px 0 0 0;">
				<div align="center">
					<p><img src="{%$staticUrl%}/apps/island/images/pay/11_01.gif"  id="dm1" class="diamond" title="兑换10宝石" /><br />
						价格：1元<br />
						<input type="submit" name="btnOrder11" id="btnOrder11" value="充值" class="orderbtn" class="diamond" />
					</p>
					<label></label>
				</div>
			</div>
			<div class="chongzhi" style="margin:40px 0 0 0;">
				<div align="center">
					<p><img src="{%$staticUrl%}/apps/island/images/pay/v2012061901/pay100.gif"  id="dm1" class="diamond" title="兑换100宝石" /><br />
						价格：10元<br />
						<input type="submit" name="btnOrder1" id="btnOrder1" value="充值" class="orderbtn" class="diamond" />
					</p>
					<label></label>
				</div>
			</div>
			<div class="chongzhi" style="margin:40px 0 0 0;">
				<div align="center">
					<p><img src="{%$staticUrl%}/apps/island/images/pay/v2012061901/pay200.gif" id="dm2" class="diamond" title="兑换200宝石，送20宝石" /><br />
						价格：20元<br />
						<input type="submit" name="btnOrder2" id="btnOrder2" value="充值" class="orderbtn" class="diamond" />
					</p>
					<label></label>
				</div>
			</div>
			<div class="chongzhi" style="margin:40px 0 0 0 ;">
				<div align="center">
					<p><img src="{%$staticUrl%}/apps/island/images/pay/v2012061901/pay500.gif" id="dm3" class="diamond" title="兑换500宝石，送60宝石"/><br />
						价格：50元<br />
						<input type="submit" name="btnOrder3" id="btnOrder3" value="充值" class="orderbtn" class="diamond" />
					</p>
					<label></label>
				</div>
			</div>
			<div class="chongzhi" style="margin:40px 0 0 0;">
				<div align="center">
					<p><img src="{%$staticUrl%}/apps/island/images/pay/v2012061901/pay1000.gif" id="dm4" class="diamond" title="兑换1000宝石，送140宝石"/><br />
						价格：100元<br />
						<input type="submit" name="btnOrder4" id="btnOrder4" value="充值" class="orderbtn" class="diamond" />
					</p>
					<label></label>
				</div>
			</div>
		</form>
	</div>
{% else %}
	<div class="content" style="padding-top:10px;padding-left:40px;width:740px;">
		<div style="color:red;padding:0 0 10px 0;">
			<br />
			<font color="blue" size="2px;">
				一次性充值10元即可获赠“加送5宝石、高级化肥x10、5星大法师斯内普”<br />
				一次性充值20元即可获赠“加送10宝石、高级化肥x20、5星赫敏”<br />
				一次性充值50元即可获赠“加送80宝石、高级化肥x50、5星大法师斯内普 5星赫敏”<br />
				一次性充值100元即可获赠“加送200宝石、高级化肥x100、5星大法师斯内普 5星赫敏”<br />
			<br />
			</font>
			<font color="red" size="2px;">注：一次性充值一元参加“天天特价”专题活动！限时，限量！</font>
		</div>
		<form id="frmPayOrder" method="get" target="_blank" action="{%$baseUrl%}/pay/gopay" style="padding-top:20px">
			<div class="chongzhi" style="margin:40px 0 0 0;">
				<div align="center">
					<p><img src="{%$staticUrl%}/apps/island/images/pay/11_01.gif"  id="dm1" class="diamond" title="兑换10宝石" /><br />
						价格：1元<br />
						<input type="submit" name="btnOrder11" id="btnOrder11" value="充值" class="orderbtn" class="diamond" />
					</p>
					<label></label>
				</div>
			</div>
			<div class="chongzhi" style="margin:40px 0 0 0;">
				<div align="center">
					<p><img src="{%$staticUrl%}/apps/island/images/pay/0_44.gif"  id="dm1" class="diamond" title="兑换100宝石" /><br />
						价格：10元<br />
						<input type="submit" name="btnOrder1" id="btnOrder1" value="充值" class="orderbtn" class="diamond" />
					</p>
					<label></label>
				</div>
			</div>
			<div class="chongzhi" style="margin:40px 0 0 0;">
				<div align="center">
					<p><img src="{%$staticUrl%}/apps/island/images/pay/1_44.gif" id="dm2" class="diamond" title="兑换200宝石，送20宝石" /><br />
						价格：20元<br />
						<input type="submit" name="btnOrder2" id="btnOrder2" value="充值" class="orderbtn" class="diamond" />
					</p>
					<label></label>
				</div>
			</div>
			<div class="chongzhi" style="margin:40px 0 0 0 ;">
				<div align="center">
					<p><img src="{%$staticUrl%}/apps/island/images/pay/2_44.gif" id="dm3" class="diamond" title="兑换500宝石，送60宝石"/><br />
						价格：50元<br />
						<input type="submit" name="btnOrder3" id="btnOrder3" value="充值" class="orderbtn" class="diamond" />
					</p>
					<label></label>
				</div>
			</div>
			<div class="chongzhi" style="margin:40px 0 0 0;">
				<div align="center">
					<p><img src="{%$staticUrl%}/apps/island/images/pay/3_44.gif" id="dm4" class="diamond" title="兑换1000宝石，送140宝石"/><br />
						价格：100元<br />
						<input type="submit" name="btnOrder4" id="btnOrder4" value="充值" class="orderbtn" class="diamond" />
					</p>
					<label></label>
				</div>
			</div>
			<!--
			<div class="chongzhi" style="margin:40px 0 0 0;">
				<div align="center">
					<p><img src="{%$staticUrl%}/apps/island/images/pay/4_9.gif" id="dm5" class="diamond" onclick="payOrder('frmPayOrder', 500);" title="兑换5000宝石，送800宝石"/><br />
						价格：500元<br />
						<input type="button" name="btnOrder5" id="btnOrder5" onclick="payOrder('frmPayOrder', 500);" value="充值" class="orderbtn" class="diamond" />
					</p>
					<label></label>
				</div>
				</div>
				-->
		</form>
	</div>
{% /if %}
	<div style="color: grey;padding: 80px 10px 20px 40px;">
        <div style="background: url('{%$staticUrl%}/apps/island/images/alipay.gif') no-repeat scroll right bottom transparent;height:60px;">
        	客服提示：如果有支付相关的疑问，请旺旺联系我们的客服：
        	<a href="http://amos1.taobao.com/msg.ww?v=2&uid=快乐岛主乐乐&s=1" target="_blank"><img border="0" alt="快乐岛主乐乐" src="http://amos1.taobao.com/online.ww?v=2&uid=快乐岛主乐乐&s=1"></a>
        	<br>
        	您即将付款给本款应用的开发者 ，淘宝在此不参与任何收费分成。<br>
        	如遇应用故障或收费问题由开发者独立向您承担责任，淘宝不承担本款应用引发的责任。
        </div>
	</div>
	<script type="text/javascript" src="http://www.google-analytics.com/ga.js"></script>
	<script type="text/javascript">
    try {
    	var pageTracker = _gat._getTracker("UA-15390609-1");
    	pageTracker._trackPageview();
    } catch(err) {}
    </script>
</div>
</body>
</html>