<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>快乐岛主</title>
<!-- <script src="http://a.tbcdn.cn/apps/mytaobao/1.0/proxy.js" type="text/javascript"></script>  -->
<script src="http://a.tbcdn.cn/apps/stargate/ac/js/proxy.js" type="text/javascript"></script>
<script src="http://a.tbcdn.cn/s/kissy/1.2.0/kissy-min.js" type="text/javascript"></script>
<!-- <script src="http://a.tbcdn.cn/apps/snstaoshare/widget/ts/share/2.0/main.js?t=2011101" type="text/javascript" charset="GB2312"></script> -->
<script src="{%$staticUrl%}/js/hf-report.js?v=1.0" type="text/javascript"></script>
<script src="http://a.tbcdn.cn/apps/snstaoshare/widget/ts/ts-min.js"></script>
<link href="{%$staticUrl%}/apps/island/main_2011041101.css?v=1.02" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="http://assets.taobaocdn.com/app/matrix/js/cross_domain.js"></script>
<script src="{%$staticUrl%}/apps/island/js/nav.js?v=1.0" type="text/javascript"></script>
<style type="text/css">
<!--
body{
	overflow-x:hidden;
}

a img,:link img,:visited img {
	border: 0 none;
}

object#swfcontent {
	display: inline;
}

.box {
	border: 1px solid #CCCCCC;
}
-->
</style>
</head>
<body>

<script src="http://a.tbcdn.cn/apps/snstaoshare/widget/ts/share/2.0/main.js?t=2011101" type="text/javascript" charset="GB2312"></script>
<div class="main" style="height:830px;">
{%include file="menu.phtml"%}
<!-- <div style="display:block;float:right; width:118px;height:26px;"></div> -->
<!-- <iframe src="http://www.connect.renren.com/like?url=http%3A%2F%2Fpage%2Erenren%2Ecom%2Frrisland" style="width:135px;height:25px;" scrolling="no" frameborder="0" allowTransparency="true"></iframe> -->
<div style="clear:both;"></div>
	<div id="main_content">
		<div id="loadingdiv" style="position: absolute; left: 350px; top: 250px;"><img src="{%$staticUrl%}/apps/island/images/common/loading0.gif" /><br/>加载中......</div>
		<div id="flashdiv"></div>
		<script src="{%$staticUrl%}/js/swfobject.js" type="text/javascript"></script>
		<script type="text/javascript">
			var VIEWER_ID = {%$uid%};
			var OWNER_ID = VIEWER_ID;
			var FIRST_LOGIN = {%$newuser%};
			if (FIRST_LOGIN==1) {
				HFcLoadTm.setNewUser();
			}

			function getCookie(name) {
				var arr = document.cookie.match(new RegExp('(^| )'+name+'=([^;]*)(;|$)'));
				if(arr != null) return unescape(arr[2]); return null;
			}
			var hf_skey = getCookie('hf_skey');
			if (hf_skey) {
	        	var flashVars={"ver":"11","pNum":"11","uid":"{%$uid%}","loadingUi":"{%$staticUrl%}/swf/loadingUi2.swf?v=2011070801", "interfaceUrl":"{%$hostUrl%}/api/initswf?v=2012020301","snsType":"taobao","charge":"1","pic1":"{%$staticUrl%}/html/b/images/load05.jpg"};
	        	var params = { base: "{%$staticUrl%}/", allowScriptAccess: "always", menu:"false", wmode: "opaque", allowFullScreen: "true", bgcolor: "#ffffff", align: "middle", quality: "high"};
	        	var attrs = { id: "islandLoader", name: "islandLoader" };
	        	swfobject.embedSWF("{%$staticUrl%}/swf/islandLoader.swf?v=2011121601", "flashdiv",  "748", "600", "10.0.3", "{%$staticUrl%}/expressInstall.swf", flashVars, params, attrs, checkFlashable);
	        } else {
	        	var html = '<div style="padding-top:50px;color:red;font-size:14px;text-align:center;">检测到您的浏览器没有开启或接收Cookie！请尝试开启后，重新进入。</div>';
	        	$('#flashdiv').html(html);
	        	HFcLoadTm.nocookie();
	        }

			function checkFlashable(res) {
				if (!res.success) {
					var strhtml = '您没有安装Adobe Flash Player，或者Flash版本过低，建议安装10.0以上版本。<br/>请点击<a href="http://get.adobe.com/cn/flashplayer/" target="_blank">这里</a>进行安装。';
					$('#loadingdiv').css('left', '100px').css('top', '250px').css('color', 'red').html(strhtml);
					HFcLoadTm.noflash();
				}
			}

	        function hideLoading()
	        {
	        	$('#loadingdiv').hide();
	        	if (FIRST_LOGIN) {
	        		sendNormalFeed();
	        	}
	        	HFcLoadTm.flashStartLoad();
	        	if (window.console && console.debug) {
	    			console.debug('startload');
	      		}
	        }

	        function loadCompleted()
	        {
	        	HFcLoadTm.flashFinishLoad();
	        	if (window.console && console.debug) {
	    			console.debug('endload');
	      		}
	        }

	        function sendNormalFeed()
	    	{
	    		var ajaxurl = '{%$hostUrl%}/api/sendfeed';
	    		$.ajax({
	    				type: "post",
	    				url: ajaxurl,
	    				data: 'type=USER_JOIN',
	    				dataType: "text",
	    				success: function(msg){
	    					//alert(msg);
	    				}
	    			});
	    	}

	    	function addfans()
	    	{
	    		window.open('http://shuo.taobao.com/microshop/front.htm?userId=401149404&follow=true');
	    	}

	    	window.onload = function() {
				window.setTimeout(function(){CrossFrame.setHeight(1080);}, 700);
		    };
		</script>
	</div>
</div>
{%include file="footer.phtml"%}