<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
<script src="{%$staticUrl%}/apps/island/js/island.js?v=1.2" type="text/javascript"></script>
<script type="text/javascript">
	function goHome()
	{
		{% if $smarty.const.PLATFORM_SOURCE=="1" %}
		window.location.href='http://island.qzone.qzoneapp.com/?openid={%$openid%}&openkey={%$openkey%}&qz_width=760&qz_height=950&keyname=610&params=&qz_style=50&canvastype=home';
		{% else %}
		window.location.href='http://main.island.qzoneapp.com/?openid={%$openid%}&openkey={%$openkey%}';
		{% /if %}
	}
</script>
<div class="title">
	<div class="menu">
        <ul style="padding-left:160px;">
        	<li style="width:72px;"><a href="javascript:void(0);" onclick="goHome();return false;"><img src="{%$staticUrl%}/apps/island/images/menu/v2/home1.gif" title="我的小岛" alt="我的小岛" /></a></li>
        	<li style="width:85px;"><a href="/invite/top"><img src="{%$staticUrl%}/apps/island/images/menu/v2/invite1.gif" title="邀请好友" alt="邀请好友" /></a></li>
        	<li style="width:74px;"><a href="/gift/top"><img src="{%$staticUrl%}/apps/island/images/menu/v2/gift1.gif" title="赠送礼物" alt="赠送礼物" /></a></li>
        	<li style="width:78px;"><a href="#" onclick="HFApp.goQQPay();"><img src="{%$staticUrl%}/apps/island/images/menu/v2/qpoint1.gif" title="Q点充值" alt="Q点充值" /></a></li>
        	<li style="width:65px;"><a href="http://qbar.qq.com/opensns/l-1293437120.htm" target="_blank"><img src="{%$staticUrl%}/apps/island/images/menu/v2/forum1.gif" title="玩家论坛" alt="玩家论坛" /></a></li>
        	<li style="width:65px;"><a href="#" onclick="HFApp.goQQPayCheck();"><img src="{%$staticUrl%}/apps/island/images/menu/v2/qpoint2.gif" title="Q点查询" alt="Q点查询" /></a></li>
        	<li style="width:66px;"><a href="http://t.qq.com/hapyfish?preview" target="_blank"><img src="{%$staticUrl%}/apps/island/images/menu/v2/listen1.gif" title="收听微博" alt="收听微博" /></a></li>
        	<li style="width:83px;"><a href="{%$staticUrl%}/html/hz/hz.html" target="_blank"><img src="{%$staticUrl%}/apps/island/images/menu/v2/yellow.gif" title="QQ黄钻" alt="QQ黄钻" /></a></li>
        </ul>
	</div>
</div>



