<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>系统通知Feed发送-运营</title>
<link media="screen" type="text/css" rel="stylesheet" href="{%$staticUrl%}/a/gb_app.css">
<style type="text/css">
<!--
html{overflow:scroll!important;}

body,td,th {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #333333;
}

a img,:link img,:visited img {
	border: 0 none;
}
div,form,dl,dt,dd,img,h1,h2,h3,h4,h5,h6,ul,ol,li,p,span,table,th,td,a{margin:0;padding:0;border:0}
img{border:none;vertical-align:middle}
body{font-family:"宋体",Verdana,Arial,Helvetica,sans-serif;font-size:12px}
button{border:none;cursor:pointer;background:none;font-size:12px;text-align:center}

#msgboxDiv {display:none;position:absolute;}

-->
</style>
</head>
<body>
<div>
	<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
	<script src="{%$staticUrl%}/js/utils.js?v=1.0" type="text/javascript"></script>
	
	<div id="info_area" >
	<table style="width:1000px;">
	<tr>
	<th rowspan="2">门牌号：</th>
	<td><textarea id="uid" name="uids" style="width:540px;height:100px;"></textarea></td>
	</tr>
	<tr>
	<td>多个门牌号请用逗号( , )隔开</td>
	<tr style="height:70px;">
	<th rowspan="2">feed：</th>
	<td><textarea id="feed" name="feed" style="width:540px;height:60px;"></textarea></td>
	</tr>
	<tr>
	<td>可使用部分HTML标签和样式(<a target="_blank" href="http://livedocs.adobe.com/flash/9.0_cn/main/wwhelp/wwhimpl/common/html/wwhelp.htm?context=LiveDocs_Parts&file=00000907.html">参考说明</a>)</td>
	</tr>
	</table>
	<input type="button" value="发送" onclick="send();" id="button" style="margin:20px 300px;"/>
	</div>
	<div style="clear:both;"></div>
	<div style="width:417px;position:absolute;top:200px;left:100px;display:none;" class="layer_global" id="msgboxDiv">
		<div class="layer_global_main">
			<div class="layer_global_title"><h3 id="msgboxTitle"></h3><button title="关闭" id="closeQuery" onclick="closeQuery();"><span class="none">╳</span></button></div>
			<div class="layer_global_cont">
				<div style="margin: 20px;" class="wrap"><span id="msgboxContent"></span></div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">

function timeFormat(time)
{
	var timestamp = time*1000;
	return (new Date(timestamp)).format('Y-m-d H:i:s');
}

function msgbox(title, msg, x, y)
{
	if (!x) x = 50;
	if (!y) y = 100;
	$('#msgboxDiv').css({left: x, top: y});
	$('#msgboxTitle').html(title);
	$('#msgboxContent').html(msg);
	$('#msgboxDiv').show();
}

function closeQuery()
{
	$('#msgboxDiv').hide();
}

$.ajaxSetup({cache:false});

function send()
{
	var uid = $("#uid").val();
	var feed = $("#feed").val();
	var dt = {uid:uid, feed:feed};
	$.get('/maintenanceapi/sendfeed?platform={%$platform%}', dt, function(data) {
		if(data.num > 0){
			alert('发送成功');
		} else{
			alert('请检查');
		}
	}, "json");
}

/*
$().ready(function() {
	$('.layer_global').Drags({
		handler: '.layer_global_title'
	});
});*/

</script>
</body>
</html>
