<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>充值 | 快乐岛主</title>
<link href="{%$staticUrl%}/apps/island/main_2011041101.css?v=1.01" rel="stylesheet" type="text/css" />
<link href="{%$staticUrl%}/apps/island/pay_2011031501.css?v=1.00" rel="stylesheet" type="text/css" />
<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
<script src="{%$staticUrl%}/js/jquery.flashSlider-1.0.min.js" type="text/javascript"></script>
<style type="text/css">
<!--
a img,:link img,:visited img {
	border: 0 none;
}
-->
</style>
</head>
<body>
<div class="main">
    {%include file="menu.phtml"%}
    <div class="chongzhicontent">
    	<img src="{%$user.face%}" width="59" height="60" />
    	<div class="xinxi">
    		<div class="cname">{%$user.name|escape%}</div>
    		<div class="shuzi">宝石： <span style="color:#3c7e9a;font-weight:bold;">{%$user.gold%}</span></div>
    		<div class="fhyx"><a href="http://game.weibo.com/{%$smarty.const.APP_NAME%}/" target="_top"><img src="{%$staticUrl%}/apps/island/images/pay/back.gif" width="80" height="35" /></a></div>
    	</div>
    </div>

    <div class="table">
    	<ul>
        	<li style="width:50px"></li>
        	<li><a href="{%$baseUrl%}/pay/top"><div class="nav_01">充值宝石</div></a></li>
        	<li><a href="{%$baseUrl%}/pay/log"><div class="nav_02">充值记录</div></a></li>
        	<li><a href="{%$baseUrl%}/consumelogs/gold"><div class="nav_02">宝石消耗记录</div></a></li>
        	<li><a href="{%$baseUrl%}/consumelogs/coin"><div class="nav_02">金币消耗记录</div></a></li>
        	<li><a href="{%$baseUrl%}/pay/orderstatus"><div class="nav_02">订单查询</div></a></li>
    	</ul>
    </div>

	<form id="frmPayOrder" method="post" action="http://pay.weibo.com/wb/?c=pay" target="_top" style="display:none;">
		<input type="hidden" id="return_url" name="return_url" value="http://game.weibo.com/{%$smarty.const.APP_NAME%}/" />
		<input type="hidden" id="order_id" name="order_id" value="" />
		<input type="hidden" id="order_uid" name="order_uid" value="{%$platformUid%}" />
		<input type="hidden" id="desc" name="desc" value="" />
		<input type="hidden" id="appkey" name="appkey" value="{%$smarty.const.APP_ID%}"  />
		<input type="hidden" id="amount" name="amount" value="" />
		<input type="hidden" id="version" name="version" value="1.0" />
		<input type="hidden" id="token" name="token" value="" />
	</form>
	<div>
		<img src="{%$staticUrl%}/apps/island/images/pay/pay01.jpg" />
	</div>
	
	{% if $nowtime > $changetime %}
		<div style="color:red;padding:0 0 10px 0;">
			<br />
			<font color="blue">
				一次性充值20元即可获赠“宝箱钥匙*3，捕鱼卡*3”<br />
				一次性充值50元即可获赠“宝箱钥匙*3，捕鱼卡*5，5星建築－摄影棚”<br />
				一次性充值80元即可获赠“双倍经验卡*10，宝箱钥匙*10，5星建築－电影院”<br />
				一次性充值100元即可获赠“一键收取卡*10，双倍经验卡*10，宝箱钥匙*10，5星建築－明星红地毯”<br />

			</font>
		</div>
		<div id="paylist" style="height:350px">
	    	<div class="chongzhi" style="margin-top:0px;">
	    		<div align="center">
	    			<p><img id="dm1" src="{%$staticUrl%}/apps/island/images/pay/v2012011801/chongzhi_01.gif" width="143" height="156" class="diamond" onclick="payOrder(1);" title="10微币兑换100宝石" /><br />
	    				20 微币<br />
	    				<input type="button" name="btnOrder1" id="btnOrder1" value="兑换" class="orderbtn" class="diamond" onclick="payOrder(1);" />
	    			</p>
	    			<label></label>
	    		</div>
	    	</div>
	    	<div class="chongzhi" style="margin-top:0px;">
	    		<div align="center">
	    			<p><img id="dm2" src="{%$staticUrl%}/apps/island/images/pay/v2012011801/chongzhi_02.gif" width="143" height="156" class="diamond" onclick="payOrder(2);" title="20微币兑换220宝石" /><br />
	    				50 微币<br />
	    				<input type="button" name="btnOrder2" id="btnOrder2"  value="兑换" class="orderbtn" class="diamond" onclick="payOrder(2);" />
	    			</p>
	    			<label></label>
	    		</div>
	    	</div>
	    	<div class="chongzhi" style="margin-top:0px;">
	    		<div align="center">
	    			<p><img id="dm3" src="{%$staticUrl%}/apps/island/images/pay/v2012011801/chongzhi_03.gif" width="143" height="156" class="diamond" onclick="payOrder(3);" title="50微币兑换560宝石" /><br />
	    				80 微币<br />
	    				<input type="button" name="btnOrder3" id="btnOrder3" value="兑换" class="orderbtn" class="diamond" onclick="payOrder(3);" />
	    			</p>
	    			<label></label>
	    		</div>
	    	</div>
	    	<div class="chongzhi" style="margin-top:0px;">
	    		<div align="center">
	    			<p><img id="dm4" src="{%$staticUrl%}/apps/island/images/pay/v2012011801/chongzhi_04.gif" width="143" height="156" class="diamond" onclick="payOrder(4);" title="100微币兑换1140宝石" /><br />
	    				100 微币<br />
	    				<input type="button" name="btnOrder4" id="btnOrder4" value="兑换" class="orderbtn" class="diamond" onclick="payOrder(4);" />
	    			</p>
	    			<label></label>
	    		</div>
	    	</div>
		</div>
	{% else %}
		<div style="color:red;padding:0 0 10px 0;">
				<br />
					<b>充值送加码活动即时起至11月30日24点结束</b>
				</font><br /><br />
				<font color="blue">
				一次性充值10元即可获赠“10宝石、双倍经验卡*3、5星建筑驯鹿小店“<br />
				一次性充值20元即可获赠“30宝石、一键拾取卡*5、5星建筑爱心漂流瓶”<br />
				一次性充值50元即可获赠“100宝石、一键拾取卡*10、双倍经验卡*10、5星建筑驯鹿小店、5星建筑爱心漂流瓶”<br />
				一次性充值100元即可获赠“200宝石、一键拾取卡*20、双倍经验卡*20、5星驯鹿小店、5星建筑爱心漂流瓶”<br />

				</font>
		</div>
		<div id="paylist" style="height:350px">
	    	<div class="chongzhi" style="margin-top:0px;">
	    		<div align="center">
	    			<p><img id="dm1" src="{%$staticUrl%}/apps/island/images/pay/v2011112802/pay_01.gif" width="143" height="156" class="diamond" onclick="payOrder(1);" title="10微币兑换100宝石" /><br />
	    				10 微币<br />
	    				<input type="button" name="btnOrder1" id="btnOrder1" value="兑换" class="orderbtn" class="diamond" onclick="payOrder(1);" />
	    			</p>
	    			<label></label>
	    		</div>
	    	</div>
	    	<div class="chongzhi" style="margin-top:0px;">
	    		<div align="center">
	    			<p><img id="dm2" src="{%$staticUrl%}/apps/island/images/pay/v2011112802/pay_02.gif" width="143" height="156" class="diamond" onclick="payOrder(2);" title="20微币兑换220宝石" /><br />
	    				20 微币<br />
	    				<input type="button" name="btnOrder2" id="btnOrder2"  value="兑换" class="orderbtn" class="diamond" onclick="payOrder(2);" />
	    			</p>
	    			<label></label>
	    		</div>
	    	</div>
	    	<div class="chongzhi" style="margin-top:0px;">
	    		<div align="center">
	    			<p><img id="dm3" src="{%$staticUrl%}/apps/island/images/pay/v2011112802/pay_03.gif" width="143" height="156" class="diamond" onclick="payOrder(3);" title="50微币兑换560宝石" /><br />
	    				50 微币<br />
	    				<input type="button" name="btnOrder3" id="btnOrder3" value="兑换" class="orderbtn" class="diamond" onclick="payOrder(3);" />
	    			</p>
	    			<label></label>
	    		</div>
	    	</div>
	    	<div class="chongzhi" style="margin-top:0px;">
	    		<div align="center">
	    			<p><img id="dm4" src="{%$staticUrl%}/apps/island/images/pay/v2011112802/pay_04.gif" width="143" height="156" class="diamond" onclick="payOrder(4);" title="100微币兑换1140宝石" /><br />
	    				100 微币<br />
	    				<input type="button" name="btnOrder4" id="btnOrder4" value="兑换" class="orderbtn" class="diamond" onclick="payOrder(4);" />
	    			</p>
	    			<label></label>
	    		</div>
	    	</div>
		</div>
	{% /if %}	

	<br /><br /><br />
	<div style="clear:both;color:blue;margin:25px 0 10px 0;">
            友情小提示：成功充值后宝石即刻到账，部分用户可能因为网络原因，宝石约10分钟左右到帐！<br />
            如有问题请联系乐乐客服：<a href="http://weibo.com/2155826421" target="_blank">@快乐岛主乐乐</a>
    </div>
</div>

{%include file="cmscript.phtml"%}
<script type="text/javascript">
    function payOrder(type)
    {
        if (type<1 || type>4) {
			return false;
        }

    	setBtnEnable(false);

    	var title = $("#dm"+type).attr("title");
    	if (window.confirm('确定要用'+title+'？')) {
    		requestAndSubmit(type);
    	}
    	else {
    		setBtnEnable(true);
    	}
    	return true;
    }

    function requestAndSubmit(type)
    {
    	$.ajax({
        	type: 'post',
			url: '{%$baseUrl%}/pay/order',
			data: 'type='+type,
			dataType: 'json',
			success:function(data){
				/*alert(data);
    			$.each(data, function(i, n){
        	    	alert( "Item #" + i + ": " + n );
        	    });*/

				if(data != '' && data.info && data.status==1) {
					$('#order_id').val(data.info.order_id);
					$('#desc').val(data.info.desc);
					$('#amount').val(data.info.amount);
                	$('#token').val(data.info.token);
                	$('#frmPayOrder').submit();
				} else{
					alert("[出现错误啦]: 暂时无法提交订单，请稍后重试。");
					setBtnEnable(true);
				}
			},
			error:function(){
				alert("[出现错误啦]: 暂时无法提交订单，请稍后重试。");
				setBtnEnable(true);
			}
		});
    }

    function setBtnEnable(enable)
    {
    	/*document.getElementById('btnOrder1').disabled = enable;
    	document.getElementById('btnOrder2').disabled = enable;
    	document.getElementById('btnOrder3').disabled = enable;
    	document.getElementById('btnOrder4').disabled = enable;*/
    	var val = !enable ? 'disabled' : '';
    	$('#btnOrder1').attr("disabled", val);
    	$('#btnOrder2').attr("disabled", val);
    	$('#btnOrder3').attr("disabled", val);
    	$('#btnOrder4').attr("disabled", val);
    }
</script>
</body>
</html>