<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>一元店后台</title>
</head>
<body>
	<br /><br />
	&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% $hostUrl %}/operate/index"><b>返回首页</b></a>&nbsp;&nbsp;&nbsp;&nbsp;
	<span><a href="{% $hostUrl %}/operate/onegoldindex">一元店数值</a></span>&nbsp;&nbsp;
	<span><a href="{% $hostUrl %}/operate/onegoldbox">一元店宝箱</a></span>
</body>
</html>