<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>一元店后台</title>
</head>
<body>
	<br />
	&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% $hostUrl %}/operate/index"><b>返回首页</b></a>
	<br /><br />
	<div>
		{% foreach from=$datavo item=data %}
		<form action="{%$hostUrl%}/operate/onegoldupdate" method="post">
			ID:<input type="text" name="operate[id]" size="4" value="{%$data.id%}" />&nbsp;&nbsp;
			物品:<input type="text" name="operate[cid]" size="10" value="{%$data.cid%}" />&nbsp;&nbsp;
			宝石:<input type="text" name="operate[gold]" size="4" value="{%$data.gold%}" />&nbsp;&nbsp;
			金币:<input type="text" name="operate[coin]" size="8" value="{%$data.coin%}" />&nbsp;&nbsp;
			海星:<input type="text" name="operate[starfish]" size="4" value="{%$data.starfish%}" />&nbsp;&nbsp;
			限制数量:<input type="text" name="operate[num]" size="4" value="{%$data.num%}" />&nbsp;&nbsp;
			开始时间:<input type="text" name="operate[start_time]" size="20" value="{%$data.start_time|date_format:'%Y-%m-%d %H:%M:%S'%}" />&nbsp;&nbsp;
			结束时间:<input type="text" name="operate[end_time]" size="20" value="{%$data.end_time|date_format:'%Y-%m-%d %H:%M:%S'%}" />
			<input type="submit" value="更新" />
			<br /><br />
		</form>
		{% /foreach %}
	</div><br />
	<form action="{%$hostUrl%}/operate/onegoldaddnew" method="post">
		<input type="submit" name="add" value="新加一条" />
	</form>
	<br />
	<form action="{%$hostUrl%}/operate/onegoldclearnum" method="post">
		<input type="submit" name="clearnum" value="清除数量" />
	</form>
	<br />
	<form action="{%$hostUrl%}/operate/onegoldstatus" method="post">
		<input type="text" size="5" name="id" value="1" />
		<input type="submit" name="add" value="去除过期数据" />(输入ID)
	</form>
</body>
</html>