<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>那个什么年代的什么人</title>
</head>
<body>
	<form action="{%$hostUrl%}/unlockship/unlockship" method="post">
		用户UID：<input type="text" name="uid" value="{%$sex%}" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<input type="submit" value="执行" />
	</form>
</body>
</html>